# Generated by Django 5.2.17 on 2026-09-07 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('starter_monthly', 'Axom AI Starter Monthly'), ('pro_monthly', 'Axom AI Pro Monthly'), ('business_monthly', 'Axom AI Business Monthly'), ('starter_yearly', 'Axom AI Starter Yearly'), ('pro_yearly', 'Axom AI Pro Yearly'), ('business_yearly', 'Axom AI Business Yearly')], max_length=32)),
                ('amount', models.IntegerField(help_text='amount in paise')),
                ('currency', models.CharField(default='INR', max_length=8)),
                ('razorpay_order_id', models.CharField(max_length=64, unique=True)),
                ('razorpay_payment_id', models.CharField(blank=True, default='', max_length=64)),
                ('razorpay_signature', models.CharField(blank=True, default='', max_length=128)),
                ('status', models.CharField(choices=[('created', 'created'), ('paid', 'paid'), ('failed', 'failed')], default='created', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='UserPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('starter_monthly', 'Axom AI Starter Monthly'), ('pro_monthly', 'Axom AI Pro Monthly'), ('business_monthly', 'Axom AI Business Monthly'), ('starter_yearly', 'Axom AI Starter Yearly'), ('pro_yearly', 'Axom AI Pro Yearly'), ('business_yearly', 'Axom AI Business Yearly')], max_length=32)),
                ('started_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'active'), ('expired', 'expired'), ('pending', 'pending')], default='active', max_length=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
