# Generated by Django 5.2.17 on 2026-09-08 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_razorpay_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='coupon_code',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('paid', 'paid'), ('failed', 'failed'), ('refunded', 'refunded')], default='created', max_length=16),
        ),
    ]
