import type { ToolPageData } from '../toolPageTypes';

const toolData: ToolPageData = {
  slug: 'excel-to-pdf',
  metaTitle: 'Excel to PDF Converter Online Free — Convert XLSX, XLS, CSV, ODS to PDF | Axom AI',
  metaDescription:
    'Convert Excel XLSX, XLS, ODS spreadsheets and CSV files to PDF online for free. No watermark, no sign-up. Preserves tables, formatting, and formulas. Powered by Axom AI.',
  canonicalUrl: 'https://aiaxom.co.in/tools/excel-to-pdf',
  keywords: [
    'excel to pdf', 'xlsx to pdf', 'xls to pdf', 'csv to pdf', 'ods to pdf',
    'convert excel to pdf', 'excel to pdf converter', 'excel to pdf online free',
    'xlsx to pdf converter online', 'convert xlsx to pdf free', 'xls to pdf converter',
    'csv to pdf converter online', 'ods to pdf converter', 'spreadsheet to pdf',
    'excel to pdf no watermark', 'excel to pdf without sign up', 'free excel to pdf',
    'online excel to pdf converter', 'convert spreadsheet to pdf online',
    'excel to pdf high quality', 'excel to pdf preserve formatting',
    'how to convert excel to pdf', 'how to convert xlsx to pdf online free',
    'what is the best free excel to pdf converter', 'how to convert csv to pdf',
    'can I convert excel to pdf without microsoft office', 'how to convert ods to pdf',
    'best excel to pdf converter 2025', 'excel to pdf converter no registration',
    'ai excel to pdf converter', 'ai powered spreadsheet converter',
    'excel to pdf converter india', 'xlsx to pdf assamese', 'excel to pdf hindi',
    'excel to pdf bengali', 'convert spreadsheet to pdf india',
    'excel to pdf for students india', 'excel to pdf for accountants',
    'free excel to pdf converter for business', 'excel to pdf for government',
    'excel to pdf no ads', 'excel to pdf no email required',
    'secure excel to pdf converter', 'private excel to pdf converter',
    'excel to pdf browser based', 'excel to pdf mobile', 'convert excel to pdf on phone',
    'excel to pdf android', 'libreoffice excel to pdf', 'server side xlsx to pdf',
    'batch excel to pdf', 'excel to pdf table formatting', 'excel to pdf columns',
    'axom ai excel to pdf', 'axom ai spreadsheet converter',
    'excel to pdf converter tool', 'xlsx to pdf free tool', 'excel pdf export online',
  ],
  breadcrumbName: 'Excel to PDF Converter',
  heroBadgeText: 'Free Excel to PDF Converter — No Watermark',
  heroHeadingPrefix: 'Convert',
  heroHeadingHighlight: 'Excel to PDF',
  heroHeadingSuffix: 'Instantly Online',
  heroDescription:
    'Transform XLSX, XLS, ODS spreadsheets and CSV files into clean, print-ready PDF documents. No software, no watermark, no account needed — 100% free on Axom AI.',
  heroTags: [
    'XLSX, XLS, CSV & ODS Supported',
    '100% Free Daily Quota',
    'No Watermark or Branding',
    'Tables & Formatting Preserved',
  ],
  aeoTitle: 'What is Axom AI Excel to PDF Converter?',
  aeoDescription:
    '<strong>Axom AI Excel to PDF Converter</strong> is a free, browser-based tool that converts Microsoft Excel (<code>.xlsx</code>, <code>.xls</code>), LibreOffice Calc (<code>.ods</code>), and CSV files into high-quality PDF documents. The conversion uses a server-side <strong>LibreOffice rendering engine</strong> that preserves tables, cell formatting, column widths, merged cells, and Unicode text — including <strong>Assamese</strong>, <strong>Hindi</strong>, and <strong>Bengali</strong> scripts. No watermark is added, no account is required, and files are deleted immediately after conversion. Built as part of <strong>India\'s sovereign AI platform</strong>.',
  aeoHighlights: [
    '100% Free Daily Conversions',
    'No Watermark Added',
    'Tables & Formatting Preserved',
    'Supports Indic Unicode Scripts',
  ],
  steps: [
    {
      title: 'Upload Your Spreadsheet',
      description: 'Select or drag and drop your XLSX, XLS, ODS, or CSV file. Files up to 50 MB are supported.',
    },
    {
      title: 'Convert to PDF',
      description: 'Click Convert. Our LibreOffice engine renders your spreadsheet with all tables, formulas, and formatting intact.',
    },
    {
      title: 'Download Your PDF',
      description: 'Your PDF is ready in seconds. Download instantly — clean, print-ready, and watermark-free.',
    },
  ],
  benefits: [],
  useCases: [],
  comparisonRows: [
    { feature: 'Price', axom: 'Free (daily quota)', other: 'Free but limited', paid: '$9–20/mo', axom_check: true, other_check: false },
    { feature: 'Watermark-Free Output', axom: 'Always', other: 'Often watermarked', paid: 'Yes', axom_check: true, other_check: false },
    { feature: 'CSV Support', axom: 'Yes — auto-formatted tables', other: 'Rarely', paid: 'Sometimes', axom_check: true, other_check: false },
    { feature: 'Indic Script Support', axom: 'Assamese, Hindi, Bengali', other: 'Rarely', paid: 'Partial', axom_check: true, other_check: false },
    { feature: 'Sign-Up Required', axom: 'No', other: 'Usually yes', paid: 'Yes', axom_check: true, other_check: false },
    { feature: 'File Privacy', axom: 'Deleted after conversion', other: 'Stored on servers', paid: 'Varies', axom_check: true, other_check: false },
  ],
  techSpecs: [
    { label: 'Supported Input Formats', value: 'XLSX, XLS, ODS, CSV' },
    { label: 'Output Format', value: 'PDF (ISO 32000)' },
    { label: 'Max File Size', value: '50 MB' },
    { label: 'Conversion Engine', value: 'LibreOffice Calc (server-side)' },
    { label: 'Unicode Support', value: 'Full — Assamese, Hindi, Bengali, Tamil, etc.' },
    { label: 'Processing Time', value: 'Typically under 10 seconds' },
  ],
  regionalTitle: 'Excel to PDF for Accountants, Students & Businesses in India',
  regionalDescription:
    'Axom AI is built in <strong>Assam, India</strong> and designed for Indian workflows. Our Excel to PDF converter handles <strong>Assamese (অসমীয়া)</strong>, <strong>Hindi (हिन्दी)</strong>, and <strong>Bengali (বাংলা)</strong> Unicode text in spreadsheets — GST invoices, financial reports, student mark sheets, and government data exports all convert perfectly. Low-latency Indian servers ensure fast processing for users across the country.',
  regionalBadge: "🇮🇳 India's Sovereign AI & Document Platform",
  faqs: [
    { q: 'Is the Excel to PDF converter free?', a: 'Yes, Axom AI provides free daily conversions. No watermark, no sign-up, and no credit card is required.' },
    { q: 'What spreadsheet formats are supported?', a: 'We support XLSX (Excel 2007+), XLS (legacy Excel 97-2003), ODS (LibreOffice Calc / OpenDocument Spreadsheet), and CSV (comma-separated values).' },
    { q: 'Will my table formatting be preserved?', a: 'Yes. Cell borders, merged cells, column widths, colors, fonts, and number formatting are all faithfully rendered in the PDF output.' },
    { q: 'Can I convert CSV files to PDF?', a: 'Yes. CSV files are automatically parsed and rendered as a clean formatted table in the PDF. No manual formatting needed.' },
    { q: 'Does it handle Assamese and Hindi text in cells?', a: 'Absolutely. Axom AI has full Unicode support for all major Indic scripts including Assamese, Hindi, Bengali, Tamil, and Telugu.' },
    { q: 'Do I need Microsoft Excel installed?', a: 'No. The conversion happens entirely on our servers using LibreOffice. You just need a web browser.' },
    { q: 'Is my spreadsheet data kept private?', a: 'Yes. Uploaded files and generated PDFs are deleted immediately after conversion. We never store, share, or analyze your data.' },
    { q: 'What is the maximum file size?', a: 'You can upload spreadsheets up to 50 MB. Most Excel files are well within this limit.' },
    { q: 'Can I convert multi-sheet Excel workbooks?', a: 'Yes. All sheets in your workbook are included in the PDF output, each starting on a new page.' },
    { q: 'Does it work on mobile devices?', a: 'Yes. Axom AI is fully responsive and works on Android, iOS, and all modern mobile browsers.' },
  ],
  ctaTitle: 'Convert Your Spreadsheets to PDF Now',
  ctaDescription: 'Fast, free, and private Excel to PDF conversion — tables preserved, no watermark. Trusted across India.',
  ctaPrimaryText: 'Open Excel to PDF Converter',
  ctaPrimaryUrl: '/tools',
  ctaSecondaryText: 'Explore All Document Tools',
  ctaSecondaryUrl: '/tools',
  appName: 'Axom AI Excel to PDF Converter',
  appAlternateNames: ['Axom AI XLSX to PDF', 'Axom AI Spreadsheet to PDF', 'Axom AI CSV to PDF Converter'],
  appDescription: 'Free online tool to convert Excel XLSX, XLS, ODS, and CSV files to PDF without watermark. Powered by Axom AI.',
  appCategory: 'BusinessApplication, UtilitiesApplication',
  appFeatureList: [
    'Convert XLSX to PDF', 'Convert XLS to PDF', 'Convert ODS to PDF', 'Convert CSV to PDF',
    'No watermark', 'No sign-up required', 'Preserves table formatting',
    'Indic Unicode support', 'Privacy-first', 'Mobile-friendly',
  ],
  appRatingValue: '4.8',
  appReviewCount: '2560',
  howToSchemaName: 'How to Convert Excel to PDF Online Free',
  howToSchemaDescription: 'Upload an XLSX, XLS, ODS, or CSV file to Axom AI and download a formatted PDF in seconds.',
  howToTotalTime: 'PT15S',
  howToToolName: 'Axom AI Excel to PDF Converter',
};

export default toolData;
