import type { ToolPageData } from '../toolPageTypes';

const toolData: ToolPageData = {
  slug: 'extract-pdf-pages',
  metaTitle: 'Extract PDF Pages Online Free — Select & Download Specific Pages | Axom AI',
  metaDescription:
    'Extract specific pages or page ranges from a PDF online for free. No watermark, no sign-up. Fast, secure, and privacy-first. Powered by Axom AI — India\'s sovereign AI platform.',
  canonicalUrl: 'https://aiaxom.co.in/tools/extract-pdf-pages',
  keywords: [
    'extract pdf pages', 'extract pages from pdf', 'extract pdf pages online',
    'extract pages from pdf free', 'pdf page extractor', 'extract pdf pages online free',
    'select pages from pdf', 'extract specific pages from pdf', 'pdf page range extractor',
    'extract pdf pages no watermark', 'extract pdf pages without sign up',
    'free pdf page extractor', 'online pdf page extractor',
    'extract pdf pages document', 'get pages from pdf', 'pull pages from pdf',
    'copy pages from pdf', 'save specific pdf pages', 'download pdf pages',
    'extract pdf pages free no limit', 'extract pdf pages high quality',
    'how to extract pages from a pdf', 'how to extract specific pages from pdf online',
    'what is the best free pdf page extractor', 'how to save certain pages of a pdf',
    'can I extract pdf pages without adobe', 'how to get specific pages from a pdf',
    'best pdf page extractor 2025', 'extract pdf pages no registration',
    'ai pdf page extractor', 'ai powered pdf extraction', 'smart pdf page selector',
    'extract pdf pages india', 'extract pdf pages india free', 'extract pdf pages assamese',
    'extract pdf pages hindi', 'extract pdf pages bengali',
    'pdf page extractor for students india', 'extract pdf pages for legal',
    'extract pdf pages for government', 'extract pdf pages for business',
    'secure pdf page extractor', 'private pdf page extractor',
    'extract pdf pages browser based', 'extract pdf pages mobile',
    'extract pdf pages on phone', 'extract pdf pages android',
    'extract pdf pages no email', 'extract pdf pages no software',
    'pdf page range selector', 'extract pdf chapters', 'extract pdf sections',
    'axom ai extract pdf pages', 'axom ai pdf page extractor',
    'extract pdf pages tool', 'pdf extract tool free', 'pdf page extraction online',
    'extract pages from pdf tool', 'pdf page selector online',
  ],
  breadcrumbName: 'Extract PDF Pages',
  heroBadgeText: 'Free PDF Page Extractor — Select & Download',
  heroHeadingPrefix: '',
  heroHeadingHighlight: 'Extract PDF Pages',
  heroHeadingSuffix: 'Online for Free',
  heroDescription:
    'Select specific pages or page ranges from a PDF and download them as a new document. No software, no watermark, no account needed.',
  heroTags: [
    'Select Specific Page Ranges',
    '100% Free Daily Quota',
    'No Watermark or Branding',
    'Privacy-First Processing',
  ],
  aeoTitle: 'What is Axom AI Extract PDF Pages Tool?',
  aeoDescription:
    '<strong>Axom AI Extract PDF Pages</strong> is a free, browser-based tool that lets you select specific pages or page ranges from a PDF and download them as a new, standalone PDF document. Enter page numbers like <code>1, 3, 5-10</code> and the tool creates a clean PDF containing only those pages. All content, images, and text — including <strong>Assamese</strong>, <strong>Hindi</strong>, and <strong>Bengali</strong> Unicode — are preserved perfectly. No watermark is added, no account is required, and files are deleted after processing. Part of <strong>India\'s sovereign AI and document processing platform</strong>.',
  aeoHighlights: [
    '100% Free Daily Extractions',
    'No Watermark Added',
    'Flexible Page Range Selection',
    'Files Deleted After Processing',
  ],
  steps: [
    {
      title: 'Upload Your PDF',
      description: 'Select or drag and drop the PDF from which you want to extract pages. Files up to 50 MB are supported.',
    },
    {
      title: 'Select Pages',
      description: 'Enter the page numbers or ranges you want to extract (e.g., 1, 3, 5-10, 15).',
    },
    {
      title: 'Download Extracted PDF',
      description: 'Click Extract. Your new PDF containing only the selected pages is ready to download — watermark-free.',
    },
  ],
  benefits: [],
  useCases: [],
  comparisonRows: [
    { feature: 'Price', axom: 'Free (daily quota)', other: 'Free but limited', paid: '$9–20/mo', axom_check: true, other_check: false },
    { feature: 'Watermark-Free Output', axom: 'Always', other: 'Often watermarked', paid: 'Yes', axom_check: true, other_check: false },
    { feature: 'Custom Page Ranges', axom: 'Yes — e.g. 1,3,5-10', other: 'Limited', paid: 'Yes', axom_check: true, other_check: false },
    { feature: 'Sign-Up Required', axom: 'No', other: 'Usually yes', paid: 'Yes', axom_check: true, other_check: false },
    { feature: 'File Privacy', axom: 'Deleted after extraction', other: 'Stored on servers', paid: 'Varies', axom_check: true, other_check: false },
    { feature: 'Content Preservation', axom: 'Full — text, images, links', other: 'Sometimes lossy', paid: 'Yes', axom_check: true, other_check: false },
  ],
  techSpecs: [
    { label: 'Supported Input', value: 'PDF (all versions)' },
    { label: 'Output Format', value: 'PDF (selected pages only)' },
    { label: 'Max File Size', value: '50 MB' },
    { label: 'Processing Engine', value: 'PyPDF / server-side' },
    { label: 'Page Selection', value: 'Individual pages, ranges, or mixed' },
    { label: 'Processing Time', value: 'Typically under 5 seconds' },
  ],
  regionalTitle: 'Extract PDF Pages for Students, Lawyers & Offices in India',
  regionalDescription:
    'Axom AI is built in <strong>Assam, India</strong> for Indian users. Our Extract PDF Pages tool helps students pull specific chapters from textbooks, lawyers isolate relevant case pages, and government offices extract required form pages from large compilations. It handles PDFs with <strong>Assamese (অসমীয়া)</strong>, <strong>Hindi (हिन्दी)</strong>, and <strong>Bengali (বাংলা)</strong> text perfectly. Fast processing on Indian servers ensures low latency across the country.',
  regionalBadge: "🇮🇳 India's Sovereign AI & Document Platform",
  faqs: [
    { q: 'Is the Extract PDF Pages tool free?', a: 'Yes, Axom AI offers free daily page extraction with no watermark, no sign-up, and no credit card required.' },
    { q: 'How do I specify which pages to extract?', a: 'Enter page numbers separated by commas (e.g., 1, 3, 7) or ranges with a dash (e.g., 5-10). You can mix both: 1, 3, 5-10, 15.' },
    { q: 'Will the extracted PDF have watermarks?', a: 'No. Axom AI never adds watermarks, branding, or advertisements to extracted PDF output.' },
    { q: 'Is content quality preserved?', a: 'Yes. All text, images, links, and formatting on the selected pages are preserved exactly as in the original PDF.' },
    { q: 'Can I extract non-consecutive pages?', a: 'Yes. You can extract any combination of pages — consecutive ranges, individual pages, or a mix of both.' },
    { q: 'Do I need Adobe Acrobat?', a: 'No. The tool works entirely in your browser. No software installation needed.' },
    { q: 'Is my PDF data private?', a: 'Yes. All uploaded files and extracted PDFs are deleted from our servers immediately after processing.' },
    { q: 'Does it work with scanned PDFs?', a: 'Yes. Scanned (image-based) PDFs work just like text PDFs — the selected page images are preserved.' },
    { q: 'Can I extract pages on my phone?', a: 'Yes. Axom AI is fully responsive and works on Android, iOS, and all modern mobile browsers.' },
    { q: 'What is the maximum PDF size?', a: 'PDFs up to 50 MB are supported. Most documents are well within this limit.' },
  ],
  ctaTitle: 'Extract Pages from Your PDF Now',
  ctaDescription: 'Fast, free, and private PDF page extraction — select exactly the pages you need without watermarks.',
  ctaPrimaryText: 'Open Extract PDF Pages Tool',
  ctaPrimaryUrl: '/tools',
  ctaSecondaryText: 'Explore All Document Tools',
  ctaSecondaryUrl: '/tools',
  appName: 'Axom AI Extract PDF Pages',
  appAlternateNames: ['Axom AI PDF Page Extractor', 'Axom AI PDF Page Selector'],
  appDescription: 'Free online tool to extract specific pages or page ranges from a PDF without watermark. Powered by Axom AI.',
  appCategory: 'BusinessApplication, UtilitiesApplication',
  appFeatureList: [
    'Extract specific pages from PDF', 'Custom page ranges', 'No watermark',
    'No sign-up required', 'Preserves page content and formatting',
    'Privacy-first — files deleted after processing', 'Mobile-friendly',
    'Works with scanned PDFs', 'Fast server-side processing',
  ],
  appRatingValue: '4.8',
  appReviewCount: '2340',
  howToSchemaName: 'How to Extract Specific Pages from a PDF Online Free',
  howToSchemaDescription: 'Upload a PDF to Axom AI, select page numbers or ranges, and download a new PDF with only those pages.',
  howToTotalTime: 'PT10S',
  howToToolName: 'Axom AI Extract PDF Pages',
};

export default toolData;
