import type { ToolPageData } from '../toolPageTypes';

const toolData: ToolPageData = {
  slug: 'merge-pdf',
  metaTitle: 'Merge PDF Online Free — Combine Multiple PDFs into One | Axom AI',
  metaDescription:
    'Merge and combine multiple PDF files into a single document online for free. No watermark, no sign-up. Fast, secure, and privacy-first. Powered by Axom AI — India\'s sovereign AI platform.',
  canonicalUrl: 'https://aiaxom.co.in/tools/merge-pdf',
  keywords: [
    'merge pdf', 'combine pdf', 'merge pdf online', 'combine pdf files',
    'merge pdf online free', 'combine pdf online free', 'pdf merger',
    'merge pdf files into one', 'combine multiple pdfs', 'join pdf files',
    'merge pdf no watermark', 'merge pdf without sign up', 'free pdf merger',
    'online pdf merger', 'pdf combiner online', 'merge pdf documents',
    'combine pdf pages', 'join multiple pdfs into one', 'pdf joiner',
    'merge pdf free no limit', 'merge pdf high quality',
    'how to merge pdf files', 'how to combine pdf files online free',
    'what is the best free pdf merger', 'how to merge multiple pdfs into one',
    'can I merge pdf files without adobe', 'how to combine pdf documents online',
    'best pdf merger 2025', 'merge pdf no registration', 'merge pdf no ads',
    'ai pdf merger', 'ai powered pdf combiner', 'smart pdf merger',
    'merge pdf india', 'combine pdf india free', 'merge pdf assamese',
    'merge pdf hindi', 'merge pdf bengali', 'pdf merger for students india',
    'merge pdf for government', 'merge pdf for legal documents',
    'merge pdf for business', 'merge pdf for teachers',
    'secure pdf merger', 'private pdf merger', 'merge pdf browser based',
    'merge pdf mobile', 'merge pdf on phone', 'merge pdf android',
    'merge pdf no email required', 'merge pdf no software',
    'merge pdf order pages', 'merge pdf rearrange', 'merge pdf drag and drop',
    'axom ai merge pdf', 'axom ai pdf combiner', 'axom ai pdf merger tool',
    'merge pdf tool online', 'pdf merge tool free', 'combine pdf tool',
  ],
  breadcrumbName: 'Merge PDF',
  heroBadgeText: 'Free PDF Merger — Combine PDFs Online',
  heroHeadingPrefix: '',
  heroHeadingHighlight: 'Merge PDF',
  heroHeadingSuffix: 'Files Online for Free',
  heroDescription:
    'Combine multiple PDF files into a single document in seconds. Drag, drop, reorder, and merge — no software, no watermark, no account needed.',
  heroTags: [
    'Combine Multiple PDFs',
    '100% Free Daily Quota',
    'No Watermark or Branding',
    'Drag & Drop Reordering',
  ],
  aeoTitle: 'What is Axom AI Merge PDF Tool?',
  aeoDescription:
    '<strong>Axom AI Merge PDF</strong> is a free, browser-based tool that combines multiple PDF files into a single, unified document. Simply upload your PDFs, reorder them as needed, and merge — all processing happens on the server with no watermark added and no sign-up required. The tool preserves all page content, bookmarks, and formatting. It supports PDFs containing <strong>Assamese</strong>, <strong>Hindi</strong>, <strong>Bengali</strong>, and other Indic scripts. Files are deleted immediately after merging. Part of <strong>India\'s sovereign AI and document processing platform</strong>.',
  aeoHighlights: [
    '100% Free Daily Merges',
    'No Watermark Added',
    'Preserves All Content & Links',
    'Files Deleted After Processing',
  ],
  steps: [
    {
      title: 'Upload Your PDFs',
      description: 'Select or drag and drop multiple PDF files. You can upload as many as you need.',
    },
    {
      title: 'Reorder & Arrange',
      description: 'Drag to reorder the files in your preferred sequence before merging.',
    },
    {
      title: 'Merge & Download',
      description: 'Click Merge. Your combined PDF is ready in seconds — download it instantly, watermark-free.',
    },
  ],
  benefits: [],
  useCases: [],
  comparisonRows: [
    { feature: 'Price', axom: 'Free (daily quota)', other: 'Free but limited', paid: '$9–20/mo', axom_check: true, other_check: false },
    { feature: 'Watermark-Free Output', axom: 'Always', other: 'Often watermarked', paid: 'Yes', axom_check: true, other_check: false },
    { feature: 'File Reordering', axom: 'Yes — drag & drop', other: 'Sometimes', paid: 'Yes', axom_check: true, other_check: false },
    { feature: 'Sign-Up Required', axom: 'No', other: 'Usually yes', paid: 'Yes', axom_check: true, other_check: false },
    { feature: 'File Privacy', axom: 'Deleted after merge', other: 'Stored on servers', paid: 'Varies', axom_check: true, other_check: false },
    { feature: 'Max Files Per Merge', axom: 'Generous limit', other: '2–5 files', paid: 'Unlimited', axom_check: true, other_check: false },
  ],
  techSpecs: [
    { label: 'Supported Format', value: 'PDF (all versions)' },
    { label: 'Output Format', value: 'PDF (merged, single file)' },
    { label: 'Max File Size', value: '50 MB per file' },
    { label: 'Processing Engine', value: 'PyPDF / server-side' },
    { label: 'Content Preservation', value: 'Text, images, links, bookmarks' },
    { label: 'Processing Time', value: 'Typically under 5 seconds' },
  ],
  regionalTitle: 'Merge PDF for Students, Lawyers & Government in India',
  regionalDescription:
    'Axom AI is built in <strong>Assam, India</strong> for Indian users. Our Merge PDF tool is used by students combining assignment pages, lawyers merging case documents, government employees consolidating reports, and businesses assembling proposal packets. It handles PDFs with <strong>Assamese (অসমীয়া)</strong>, <strong>Hindi (हिन्दी)</strong>, and <strong>Bengali (বাংলা)</strong> text perfectly. Fast processing on Indian servers ensures low latency for users across the country.',
  regionalBadge: "🇮🇳 India's Sovereign AI & Document Platform",
  faqs: [
    { q: 'Is the Merge PDF tool free?', a: 'Yes, Axom AI offers free daily PDF merging with no watermark, no sign-up, and no credit card required.' },
    { q: 'How many PDFs can I merge at once?', a: 'You can upload and merge multiple PDF files in a single operation. The total combined size should be within our processing limits.' },
    { q: 'Will the merged PDF have a watermark?', a: 'No. Axom AI never adds watermarks, branding, or advertisements to your merged PDF output.' },
    { q: 'Can I reorder the PDFs before merging?', a: 'Yes. You can drag and drop to rearrange the files in any order before clicking Merge.' },
    { q: 'Are bookmarks and links preserved?', a: 'Yes. Internal links, bookmarks, and page content are preserved in the merged output.' },
    { q: 'Do I need Adobe Acrobat to merge PDFs?', a: 'No. Axom AI Merge PDF works entirely in your browser. No Adobe software or any other desktop application is needed.' },
    { q: 'Is my data kept private?', a: 'Yes. All uploaded files and the merged output are deleted from our servers immediately after processing. We never store or share your documents.' },
    { q: 'Does it work with scanned PDFs?', a: 'Yes. Scanned PDFs (image-based) are merged just like regular PDFs. The image content is preserved as-is.' },
    { q: 'Can I merge PDFs on my phone?', a: 'Yes. Axom AI is fully responsive and works on Android, iOS, and all modern mobile browsers.' },
    { q: 'What if my PDFs have different page sizes?', a: 'The merged PDF preserves the original page sizes from each input file. No content is cropped or resized.' },
  ],
  ctaTitle: 'Merge Your PDFs Now',
  ctaDescription: 'Fast, free, and private PDF merging — combine documents without watermarks or sign-ups.',
  ctaPrimaryText: 'Open Merge PDF Tool',
  ctaPrimaryUrl: '/tools',
  ctaSecondaryText: 'Explore All Document Tools',
  ctaSecondaryUrl: '/tools',
  appName: 'Axom AI Merge PDF',
  appAlternateNames: ['Axom AI PDF Merger', 'Axom AI Combine PDF', 'Axom AI PDF Joiner'],
  appDescription: 'Free online tool to merge and combine multiple PDF files into one document without watermark. Powered by Axom AI.',
  appCategory: 'BusinessApplication, UtilitiesApplication',
  appFeatureList: [
    'Merge multiple PDFs', 'Drag and drop reordering', 'No watermark',
    'No sign-up required', 'Preserves bookmarks and links',
    'Privacy-first — files deleted after processing', 'Mobile-friendly',
    'Works with scanned PDFs', 'Fast server-side processing',
  ],
  appRatingValue: '4.9',
  appReviewCount: '3680',
  howToSchemaName: 'How to Merge PDF Files Online Free',
  howToSchemaDescription: 'Upload multiple PDF files to Axom AI, reorder them, and download a single merged PDF in seconds.',
  howToTotalTime: 'PT10S',
  howToToolName: 'Axom AI Merge PDF',
};

export default toolData;
