import type { ToolPageData } from '../toolPageTypes';

const toolData: ToolPageData = {
  slug: 'office-to-pdf',
  metaTitle: 'ODT, HTML, EPUB, RTF to PDF Converter Online Free — Office to PDF | Axom AI',
  metaDescription:
    'Convert ODT, HTML, EPUB, and RTF documents to PDF online for free. No watermark, no sign-up. Preserves formatting and Unicode text. Powered by Axom AI — India\'s sovereign AI platform.',
  canonicalUrl: 'https://aiaxom.co.in/tools/office-to-pdf',
  keywords: [
    'odt to pdf', 'html to pdf', 'epub to pdf', 'rtf to pdf', 'office to pdf',
    'convert odt to pdf', 'odt to pdf converter', 'odt to pdf online free',
    'html to pdf converter online', 'convert html to pdf free', 'epub to pdf converter',
    'rtf to pdf converter online', 'document to pdf', 'convert document to pdf online',
    'odt to pdf no watermark', 'html to pdf without sign up', 'free odt to pdf converter',
    'online office to pdf', 'convert epub to pdf online free', 'rtf to pdf free',
    'odt to pdf high quality', 'html to pdf preserve formatting',
    'how to convert odt to pdf', 'how to convert html to pdf online',
    'what is the best free odt to pdf converter', 'how to convert epub to pdf',
    'how to convert rtf to pdf online', 'can I convert odt to pdf without libreoffice',
    'best odt to pdf converter 2025', 'office to pdf converter no registration',
    'ai document converter', 'ai powered office to pdf', 'generative ai pdf converter',
    'odt to pdf converter india', 'html to pdf assamese', 'epub to pdf hindi',
    'rtf to pdf bengali', 'convert document to pdf india', 'odt to pdf for students',
    'html to pdf for developers', 'epub to pdf for readers', 'rtf to pdf for legal',
    'office to pdf no ads', 'odt to pdf no email required',
    'secure odt to pdf converter', 'private html to pdf converter',
    'office to pdf browser based', 'odt to pdf mobile', 'convert html to pdf on phone',
    'libreoffice odt to pdf', 'server side html to pdf', 'batch document to pdf',
    'odt to pdf formatting', 'html to pdf rendering', 'epub to pdf chapters',
    'axom ai office to pdf', 'axom ai document converter',
    'office to pdf tool', 'odt pdf export', 'html pdf export online',
    'open document to pdf', 'opendocument to pdf converter',
  ],
  breadcrumbName: 'Office to PDF Converter',
  heroBadgeText: 'Free ODT / HTML / EPUB / RTF to PDF Converter',
  heroHeadingPrefix: 'Convert',
  heroHeadingHighlight: 'Office Documents to PDF',
  heroHeadingSuffix: 'Instantly Online',
  heroDescription:
    'Transform ODT, HTML, EPUB, and RTF documents into perfectly formatted PDF files. No software, no watermark, no account — 100% free on Axom AI.',
  heroTags: [
    'ODT, HTML, EPUB & RTF Supported',
    '100% Free Daily Quota',
    'No Watermark or Branding',
    'Full Unicode & Formatting',
  ],
  aeoTitle: 'What is Axom AI Office to PDF Converter?',
  aeoDescription:
    '<strong>Axom AI Office to PDF Converter</strong> is a free, browser-based tool that converts <code>.odt</code> (OpenDocument Text), <code>.html</code>, <code>.epub</code> (e-books), and <code>.rtf</code> (Rich Text Format) documents into high-quality PDF files. The server-side <strong>LibreOffice rendering engine</strong> preserves text formatting, images, tables, headers, footers, and Unicode text — including <strong>Assamese</strong>, <strong>Hindi</strong>, and <strong>Bengali</strong>. No watermark, no sign-up, and files are deleted after conversion. Part of <strong>India\'s sovereign AI and document processing platform</strong>.',
  aeoHighlights: [
    '100% Free Daily Conversions',
    'No Watermark Added',
    'ODT, HTML, EPUB & RTF Supported',
    'Full Indic Unicode Support',
  ],
  steps: [
    {
      title: 'Upload Your Document',
      description: 'Select or drag and drop your ODT, HTML, EPUB, or RTF file. Files up to 50 MB are supported.',
    },
    {
      title: 'Convert to PDF',
      description: 'Click Convert. Our LibreOffice engine renders your document with full formatting fidelity.',
    },
    {
      title: 'Download Your PDF',
      description: 'Your PDF is ready in seconds. Download it instantly — no watermark, no email required.',
    },
  ],
  benefits: [],
  useCases: [],
  comparisonRows: [
    { feature: 'Price', axom: 'Free (daily quota)', other: 'Free but limited', paid: '$9–20/mo', axom_check: true, other_check: false },
    { feature: 'Watermark-Free Output', axom: 'Always', other: 'Often watermarked', paid: 'Yes', axom_check: true, other_check: false },
    { feature: 'EPUB Support', axom: 'Yes — full chapter rendering', other: 'Rarely', paid: 'Sometimes', axom_check: true, other_check: false },
    { feature: 'Indic Script Support', axom: 'Assamese, Hindi, Bengali', other: 'Rarely', paid: 'Partial', axom_check: true, other_check: false },
    { feature: 'Sign-Up Required', axom: 'No', other: 'Usually yes', paid: 'Yes', axom_check: true, other_check: false },
    { feature: 'File Privacy', axom: 'Deleted after conversion', other: 'Stored on servers', paid: 'Varies', axom_check: true, other_check: false },
  ],
  techSpecs: [
    { label: 'Supported Input Formats', value: 'ODT, HTML, EPUB, RTF' },
    { label: 'Output Format', value: 'PDF (ISO 32000)' },
    { label: 'Max File Size', value: '50 MB' },
    { label: 'Conversion Engine', value: 'LibreOffice (server-side)' },
    { label: 'Unicode Support', value: 'Full — Assamese, Hindi, Bengali, Tamil, etc.' },
    { label: 'Processing Time', value: 'Typically under 10 seconds' },
  ],
  regionalTitle: 'ODT, HTML & EPUB to PDF for Users Across India',
  regionalDescription:
    'Axom AI is built in <strong>Assam, India</strong> for Indian users. Our Office to PDF converter handles <strong>Assamese (অসমীয়া)</strong>, <strong>Hindi (हिन्दी)</strong>, and <strong>Bengali (বাংলা)</strong> Unicode text perfectly. Government employees converting ODT documents, developers exporting HTML reports, students converting EPUB textbooks, and lawyers processing RTF filings — all benefit from fast, private, and accurate conversions on Indian servers.',
  regionalBadge: "🇮🇳 India's Sovereign AI & Document Platform",
  faqs: [
    { q: 'Is the Office to PDF converter free?', a: 'Yes, Axom AI provides free daily conversions with no watermark, no sign-up, and no credit card required.' },
    { q: 'What document formats are supported?', a: 'We support ODT (OpenDocument Text), HTML web pages, EPUB e-books, and RTF (Rich Text Format) documents.' },
    { q: 'Will formatting be preserved in the PDF?', a: 'Yes. Text styles, images, tables, headers, footers, and page layouts are faithfully rendered by our LibreOffice engine.' },
    { q: 'Can I convert EPUB e-books to PDF?', a: 'Yes. EPUB files are fully rendered with chapters, images, and formatting intact in the PDF output.' },
    { q: 'Does it support Assamese and Hindi text?', a: 'Absolutely. Full Unicode support for Assamese, Hindi, Bengali, Tamil, Telugu, and all major Indic scripts.' },
    { q: 'Do I need any software installed?', a: 'No. Everything runs in your browser — no plugins, no desktop software needed.' },
    { q: 'Are my files kept private?', a: 'Yes. Uploaded files and generated PDFs are deleted immediately after conversion. We never store or share your data.' },
    { q: 'Can I convert HTML pages to PDF?', a: 'Yes. HTML files are rendered with CSS styling preserved. This is ideal for converting web reports, invoices, or documentation to PDF.' },
    { q: 'What is the maximum file size?', a: 'Files up to 50 MB are supported. Most documents are well within this limit.' },
    { q: 'Does it work on mobile devices?', a: 'Yes. Axom AI is fully responsive and works on all modern mobile browsers including Android and iOS.' },
  ],
  ctaTitle: 'Convert Your Documents to PDF Now',
  ctaDescription: 'Fast, free, and private ODT, HTML, EPUB & RTF to PDF conversion — no watermark, no sign-up.',
  ctaPrimaryText: 'Open Office to PDF Converter',
  ctaPrimaryUrl: '/tools',
  ctaSecondaryText: 'Explore All Document Tools',
  ctaSecondaryUrl: '/tools',
  appName: 'Axom AI Office to PDF Converter',
  appAlternateNames: ['Axom AI ODT to PDF', 'Axom AI HTML to PDF', 'Axom AI EPUB to PDF', 'Axom AI RTF to PDF'],
  appDescription: 'Free online tool to convert ODT, HTML, EPUB, and RTF documents to PDF without watermark. Powered by Axom AI.',
  appCategory: 'BusinessApplication, UtilitiesApplication',
  appFeatureList: [
    'Convert ODT to PDF', 'Convert HTML to PDF', 'Convert EPUB to PDF', 'Convert RTF to PDF',
    'No watermark', 'No sign-up required', 'Full formatting preservation',
    'Indic Unicode support', 'Privacy-first', 'Mobile-friendly',
  ],
  appRatingValue: '4.8',
  appReviewCount: '1980',
  howToSchemaName: 'How to Convert ODT, HTML, EPUB or RTF to PDF Online Free',
  howToSchemaDescription: 'Upload an ODT, HTML, EPUB, or RTF file to Axom AI and download a formatted PDF in seconds.',
  howToTotalTime: 'PT15S',
  howToToolName: 'Axom AI Office to PDF Converter',
};

export default toolData;
