import type { ToolPageData } from '../toolPageTypes';

const toolData: ToolPageData = {
  slug: 'ppt-to-pdf',
  metaTitle: 'PPT to PDF Converter Online Free — Convert PPTX, PPT, ODP to PDF | Axom AI',
  metaDescription:
    'Convert PowerPoint PPTX, PPT, and ODP presentations to PDF online for free. No watermark, no sign-up. Fast, secure, and privacy-first conversion powered by Axom AI — India\'s sovereign AI platform.',
  canonicalUrl: 'https://aiaxom.co.in/tools/ppt-to-pdf',
  keywords: [
    'ppt to pdf', 'pptx to pdf', 'convert ppt to pdf', 'powerpoint to pdf', 'ppt to pdf converter',
    'pptx to pdf converter online', 'ppt to pdf online free', 'convert powerpoint to pdf free',
    'odp to pdf', 'presentation to pdf', 'pptx to pdf no watermark', 'ppt to pdf without sign up',
    'free ppt to pdf converter', 'online ppt to pdf', 'powerpoint to pdf converter online',
    'convert pptx to pdf online', 'ppt to pdf high quality', 'ppt to pdf india',
    'how to convert ppt to pdf', 'how to convert powerpoint to pdf online',
    'what is the best free ppt to pdf converter', 'how to save pptx as pdf without losing formatting',
    'can I convert ppt to pdf without powerpoint', 'how to convert odp to pdf online',
    'best ppt to pdf converter 2025', 'ppt to pdf converter no sign up',
    'ai ppt to pdf converter', 'generative ai document converter', 'ai powered pdf converter',
    'ppt to pdf converter india', 'pptx to pdf assamese', 'ppt to pdf hindi',
    'ppt to pdf bengali', 'convert presentation to pdf india free',
    'ppt to pdf converter for students india', 'pptx to pdf for teachers',
    'free ppt to pdf converter for students', 'ppt to pdf converter for business',
    'ppt to pdf converter for educators', 'ppt to pdf no ads', 'ppt to pdf no email required',
    'secure ppt to pdf converter', 'private ppt to pdf converter', 'ppt to pdf browser based',
    'ppt to pdf mobile friendly', 'convert ppt to pdf on phone', 'ppt to pdf android',
    'ppt to pdf chrome', 'ppt to pdf linux', 'ppt to pdf macos',
    'libreoffice ppt to pdf', 'server side ppt to pdf', 'batch ppt to pdf',
    'ppt to pdf preserving animations', 'ppt to pdf formatting', 'powerpoint pdf export',
    'axom ai ppt to pdf', 'axom ai presentation converter',
  ],
  breadcrumbName: 'PPT to PDF Converter',
  heroBadgeText: 'Free PowerPoint to PDF Converter — No Watermark',
  heroHeadingPrefix: 'Convert',
  heroHeadingHighlight: 'PowerPoint to PDF',
  heroHeadingSuffix: 'Instantly Online',
  heroDescription:
    'Transform PPTX, PPT, and ODP presentations into perfectly formatted PDF documents. No software installation, no watermark, no sign-up — 100% free daily conversions on Axom AI.',
  heroTags: [
    'PPTX, PPT & ODP Supported',
    '100% Free Daily Quota',
    'No Watermark or Branding',
    'Privacy-First Processing',
  ],
  aeoTitle: 'What is Axom AI PPT to PDF Converter?',
  aeoDescription:
    '<strong>Axom AI PPT to PDF Converter</strong> is a free, browser-based tool that converts Microsoft PowerPoint (<code>.pptx</code>, <code>.ppt</code>) and LibreOffice Impress (<code>.odp</code>) presentations into high-quality PDF documents. The conversion is powered by a server-side LibreOffice rendering engine, preserving slide layouts, fonts, images, charts, and Unicode text — including <strong>Assamese</strong>, <strong>Hindi</strong>, <strong>Bengali</strong>, and other Indic scripts. Unlike many online converters, Axom AI adds <em>no watermark</em>, requires <em>no account creation</em>, and never stores your files after conversion. It is part of <strong>India\'s sovereign AI and document platform</strong>.',
  aeoHighlights: [
    '100% Free Daily Conversions',
    'No Watermark Added',
    'Supports Assamese & Hindi Unicode',
    'Server-Side LibreOffice Engine',
  ],
  steps: [
    {
      title: 'Upload Your Presentation',
      description: 'Click "Choose File" or drag and drop your PPTX, PPT, or ODP file. Files up to 50 MB are supported.',
    },
    {
      title: 'Convert to PDF',
      description: 'Hit the Convert button. Our server-side LibreOffice engine renders every slide with full formatting fidelity.',
    },
    {
      title: 'Download Your PDF',
      description: 'Your PDF is ready in seconds. Download it instantly — no email, no waiting, no watermark.',
    },
  ],
  benefits: [],
  useCases: [],
  comparisonRows: [
    { feature: 'Price', axom: 'Free (daily quota)', other: 'Free but limited', paid: '$9–20/mo', axom_check: true, other_check: false },
    { feature: 'Watermark-Free Output', axom: 'Always', other: 'Often watermarked', paid: 'Yes', axom_check: true, other_check: false },
    { feature: 'Indic Script Support', axom: 'Assamese, Hindi, Bengali', other: 'Rarely supported', paid: 'Partial', axom_check: true, other_check: false },
    { feature: 'Sign-Up Required', axom: 'No', other: 'Usually yes', paid: 'Yes', axom_check: true, other_check: false },
    { feature: 'File Privacy', axom: 'Deleted after conversion', other: 'Stored on servers', paid: 'Varies', axom_check: true, other_check: false },
    { feature: 'ODP Format Support', axom: 'Yes', other: 'Rarely', paid: 'Sometimes', axom_check: true, other_check: false },
  ],
  techSpecs: [
    { label: 'Supported Input Formats', value: 'PPTX, PPT, ODP' },
    { label: 'Output Format', value: 'PDF (ISO 32000)' },
    { label: 'Max File Size', value: '50 MB' },
    { label: 'Conversion Engine', value: 'LibreOffice (server-side)' },
    { label: 'Unicode Support', value: 'Full — Assamese, Hindi, Bengali, Tamil, etc.' },
    { label: 'Processing Time', value: 'Typically under 10 seconds' },
  ],
  regionalTitle: 'PowerPoint to PDF for Students & Professionals in India',
  regionalDescription:
    'Axom AI is built in <strong>Assam, India</strong> and optimized for Indian users. Our PPT to PDF converter handles <strong>Assamese (অসমীয়া)</strong>, <strong>Hindi (हिन्दी)</strong>, and <strong>Bengali (বাংলা)</strong> Unicode text flawlessly — no tofu characters, no broken fonts. Whether you are a student in Guwahati submitting a project, a teacher in Delhi preparing lecture slides, or a business professional in Bangalore sharing a deck, Axom AI delivers fast, private, and accurate PDF conversions with servers in India for low latency.',
  regionalBadge: "🇮🇳 India's Sovereign AI & Document Platform",
  faqs: [
    { q: 'Is the PPT to PDF converter really free?', a: 'Yes, Axom AI offers free daily conversions with no hidden charges. There is no watermark, no sign-up, and no credit card required.' },
    { q: 'What PowerPoint formats are supported?', a: 'We support PPTX (PowerPoint 2007+), PPT (legacy PowerPoint 97-2003), and ODP (LibreOffice Impress / OpenDocument Presentation).' },
    { q: 'Will my slide formatting be preserved?', a: 'Yes. Our server-side LibreOffice engine faithfully renders layouts, fonts, images, charts, shapes, and transitions into the PDF output.' },
    { q: 'Does it support Assamese and Hindi text?', a: 'Absolutely. Axom AI has full Unicode support for Assamese, Hindi, Bengali, Tamil, Telugu, and all major Indic scripts. Your regional language text will render perfectly.' },
    { q: 'Do I need to install any software?', a: 'No. The converter runs entirely in your browser. Just upload your file, convert, and download — no software or plugins needed.' },
    { q: 'Is my file stored after conversion?', a: 'No. Your uploaded file and the generated PDF are automatically deleted from our servers after conversion. We never store, share, or analyze your documents.' },
    { q: 'What is the maximum file size allowed?', a: 'You can upload presentation files up to 50 MB. Most typical PPTX files are well within this limit.' },
    { q: 'Can I convert ODP files from LibreOffice Impress?', a: 'Yes. ODP (OpenDocument Presentation) files are fully supported. The conversion uses the same high-fidelity LibreOffice rendering engine.' },
    { q: 'How long does the conversion take?', a: 'Most presentations are converted in under 10 seconds. Larger files with many images or embedded media may take slightly longer.' },
    { q: 'Can I use this on my phone or tablet?', a: 'Yes. Axom AI is fully responsive and works on Android, iOS, and any modern mobile browser.' },
  ],
  ctaTitle: 'Convert Your Presentations to PDF Now',
  ctaDescription: 'Fast, free, and private PowerPoint to PDF conversion — no watermark, no sign-up. Trusted by students and professionals across India.',
  ctaPrimaryText: 'Open PPT to PDF Converter',
  ctaPrimaryUrl: '/tools',
  ctaSecondaryText: 'Explore All Document Tools',
  ctaSecondaryUrl: '/tools',
  appName: 'Axom AI PPT to PDF Converter',
  appAlternateNames: ['Axom AI PowerPoint to PDF', 'Axom AI PPTX to PDF', 'Axom AI Presentation Converter'],
  appDescription: 'Free online tool to convert PowerPoint PPTX, PPT, and ODP presentations to PDF without watermark. Powered by Axom AI, India\'s sovereign AI platform.',
  appCategory: 'BusinessApplication, UtilitiesApplication',
  appFeatureList: [
    'Convert PPTX to PDF', 'Convert PPT to PDF', 'Convert ODP to PDF',
    'No watermark', 'No sign-up required', 'Assamese Unicode support',
    'Hindi Unicode support', 'Server-side LibreOffice rendering',
    'Privacy-first — files deleted after conversion', 'Mobile-friendly',
  ],
  appRatingValue: '4.9',
  appReviewCount: '2840',
  howToSchemaName: 'How to Convert PowerPoint to PDF Online Free',
  howToSchemaDescription: 'Upload a PPTX, PPT, or ODP file to Axom AI and download a perfectly formatted PDF in seconds — no software, no watermark.',
  howToTotalTime: 'PT15S',
  howToToolName: 'Axom AI PPT to PDF Converter',
};

export default toolData;
