import type { ToolPageData } from '../toolPageTypes';

const toolData: ToolPageData = {
  slug: 'split-pdf',
  metaTitle: 'Split PDF Online Free — Separate PDF into Individual Pages | Axom AI',
  metaDescription:
    'Split a PDF into individual pages online for free. No watermark, no sign-up. Fast, secure, and privacy-first. Powered by Axom AI — India\'s sovereign AI platform.',
  canonicalUrl: 'https://aiaxom.co.in/tools/split-pdf',
  keywords: [
    'split pdf', 'split pdf online', 'split pdf free', 'split pdf into pages',
    'pdf splitter', 'split pdf online free', 'separate pdf pages',
    'split pdf into individual pages', 'pdf page separator', 'divide pdf',
    'split pdf no watermark', 'split pdf without sign up', 'free pdf splitter',
    'online pdf splitter', 'split pdf document', 'split pdf file',
    'break pdf into pages', 'pdf page extractor', 'split pdf pages online',
    'split pdf free no limit', 'split pdf high quality',
    'how to split a pdf', 'how to split pdf into separate pages online',
    'what is the best free pdf splitter', 'how to separate pdf pages',
    'can I split a pdf without adobe', 'how to divide a pdf into individual pages',
    'best pdf splitter 2025', 'split pdf no registration', 'split pdf no ads',
    'ai pdf splitter', 'ai powered pdf separator', 'smart pdf splitter',
    'split pdf india', 'split pdf india free', 'split pdf assamese',
    'split pdf hindi', 'split pdf bengali', 'pdf splitter for students india',
    'split pdf for government', 'split pdf for legal',
    'split pdf for business', 'split pdf for teachers',
    'secure pdf splitter', 'private pdf splitter', 'split pdf browser based',
    'split pdf mobile', 'split pdf on phone', 'split pdf android',
    'split pdf no email required', 'split pdf no software',
    'split pdf download individual pages', 'split pdf zip download',
    'axom ai split pdf', 'axom ai pdf splitter', 'axom ai pdf separator',
    'split pdf tool online', 'pdf split tool free',
  ],
  breadcrumbName: 'Split PDF',
  heroBadgeText: 'Free PDF Splitter — Separate Pages Online',
  heroHeadingPrefix: '',
  heroHeadingHighlight: 'Split PDF',
  heroHeadingSuffix: 'into Individual Pages',
  heroDescription:
    'Separate a PDF into individual pages instantly. Upload, split, and download — no software, no watermark, no account needed.',
  heroTags: [
    'Split into Individual Pages',
    '100% Free Daily Quota',
    'No Watermark or Branding',
    'Privacy-First Processing',
  ],
  aeoTitle: 'What is Axom AI Split PDF Tool?',
  aeoDescription:
    '<strong>Axom AI Split PDF</strong> is a free, browser-based tool that separates a PDF document into individual single-page PDF files. Upload your PDF and receive each page as a separate downloadable file. The tool preserves all page content, images, and text — including <strong>Assamese</strong>, <strong>Hindi</strong>, and <strong>Bengali</strong> Unicode. No watermark is added, no account is required, and files are deleted after processing. Part of <strong>India\'s sovereign AI and document processing platform</strong>.',
  aeoHighlights: [
    '100% Free Daily Splits',
    'No Watermark Added',
    'Each Page as Separate PDF',
    'Files Deleted After Processing',
  ],
  steps: [
    {
      title: 'Upload Your PDF',
      description: 'Select or drag and drop the PDF file you want to split. Files up to 50 MB are supported.',
    },
    {
      title: 'Split Pages',
      description: 'Click Split. Each page is separated into its own individual PDF file.',
    },
    {
      title: 'Download Results',
      description: 'Download individual pages or all pages as a ZIP file — instantly, watermark-free.',
    },
  ],
  benefits: [],
  useCases: [],
  comparisonRows: [
    { feature: 'Price', axom: 'Free (daily quota)', other: 'Free but limited', paid: '$9–20/mo', axom_check: true, other_check: false },
    { feature: 'Watermark-Free Output', axom: 'Always', other: 'Often watermarked', paid: 'Yes', axom_check: true, other_check: false },
    { feature: 'Individual Page Downloads', axom: 'Yes', other: 'Sometimes', paid: 'Yes', axom_check: true, other_check: false },
    { feature: 'Sign-Up Required', axom: 'No', other: 'Usually yes', paid: 'Yes', axom_check: true, other_check: false },
    { feature: 'File Privacy', axom: 'Deleted after split', other: 'Stored on servers', paid: 'Varies', axom_check: true, other_check: false },
    { feature: 'ZIP Download Option', axom: 'Yes', other: 'Rarely', paid: 'Yes', axom_check: true, other_check: false },
  ],
  techSpecs: [
    { label: 'Supported Input', value: 'PDF (all versions)' },
    { label: 'Output Format', value: 'Individual PDF pages' },
    { label: 'Max File Size', value: '50 MB' },
    { label: 'Processing Engine', value: 'PyPDF / server-side' },
    { label: 'Content Preservation', value: 'Text, images, links per page' },
    { label: 'Processing Time', value: 'Typically under 5 seconds' },
  ],
  regionalTitle: 'Split PDF for Students, Offices & Courts in India',
  regionalDescription:
    'Axom AI is built in <strong>Assam, India</strong> for Indian users. Our Split PDF tool helps students extract specific assignment pages, government offices separate multi-page forms, and courts isolate individual case documents. It handles PDFs with <strong>Assamese (অসমীয়া)</strong>, <strong>Hindi (हिन्दी)</strong>, and <strong>Bengali (বাংলা)</strong> text flawlessly. Low-latency Indian servers ensure fast processing across the country.',
  regionalBadge: "🇮🇳 India's Sovereign AI & Document Platform",
  faqs: [
    { q: 'Is the Split PDF tool free?', a: 'Yes, Axom AI offers free daily PDF splitting with no watermark, no sign-up, and no credit card required.' },
    { q: 'How does PDF splitting work?', a: 'Upload your PDF and click Split. Each page is separated into its own individual PDF file, which you can download separately or as a ZIP archive.' },
    { q: 'Will the split pages have watermarks?', a: 'No. Axom AI never adds watermarks, branding, or advertisements to your output files.' },
    { q: 'Can I download all pages at once?', a: 'Yes. You can download individual pages or all split pages as a single ZIP file for convenience.' },
    { q: 'Is page content preserved after splitting?', a: 'Yes. All text, images, links, and formatting on each page are preserved exactly as in the original PDF.' },
    { q: 'Do I need Adobe Acrobat?', a: 'No. The tool works entirely in your browser. No Adobe software or desktop application is needed.' },
    { q: 'Is my PDF data kept private?', a: 'Yes. All uploaded files and split pages are deleted from our servers immediately after processing.' },
    { q: 'Does it work with scanned PDFs?', a: 'Yes. Scanned PDFs are split just like regular PDFs — each page image is preserved in its own file.' },
    { q: 'Can I split PDFs on mobile?', a: 'Yes. Axom AI is fully responsive and works on Android, iOS, and all modern mobile browsers.' },
    { q: 'What is the maximum PDF size?', a: 'You can upload PDFs up to 50 MB. Most documents are well within this limit.' },
  ],
  ctaTitle: 'Split Your PDF Now',
  ctaDescription: 'Fast, free, and private PDF splitting — separate pages without watermarks or sign-ups.',
  ctaPrimaryText: 'Open Split PDF Tool',
  ctaPrimaryUrl: '/tools',
  ctaSecondaryText: 'Explore All Document Tools',
  ctaSecondaryUrl: '/tools',
  appName: 'Axom AI Split PDF',
  appAlternateNames: ['Axom AI PDF Splitter', 'Axom AI PDF Page Separator'],
  appDescription: 'Free online tool to split a PDF into individual pages without watermark. Powered by Axom AI.',
  appCategory: 'BusinessApplication, UtilitiesApplication',
  appFeatureList: [
    'Split PDF into individual pages', 'ZIP download option', 'No watermark',
    'No sign-up required', 'Preserves page content',
    'Privacy-first — files deleted after processing', 'Mobile-friendly',
    'Works with scanned PDFs', 'Fast server-side processing',
  ],
  appRatingValue: '4.9',
  appReviewCount: '2920',
  howToSchemaName: 'How to Split a PDF into Individual Pages Online Free',
  howToSchemaDescription: 'Upload a PDF to Axom AI and download each page as a separate PDF file in seconds.',
  howToTotalTime: 'PT10S',
  howToToolName: 'Axom AI Split PDF',
};

export default toolData;
