# Generated by Django 5.2.17 on 2026-08-26 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_qapair'),
    ]

    operations = [
        migrations.AddField(
            model_name='qapair',
            name='embedding',
            field=models.TextField(blank=True),
        ),
    ]
