# Generated by Django 5.2.17 on 2026-08-26 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0004_chatsession_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
