# Generated by Django 5.2.17 on 2026-08-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0005_chatsession_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='qapair',
            name='answer_assamese',
            field=models.TextField(blank=True),
        ),
    ]
