# Generated by Django 5.2.17 on 2026-08-29 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0007_feedback_unansweredquery'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgedocument',
            name='source_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='source_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='qapair',
            name='source_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='qapair',
            name='source_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
