# Generated by Django 5.2.17 on 2026-09-09 07:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_label', models.CharField(default='NEW', max_length=50)),
                ('message', models.CharField(default='Axom AI 2.0 is now live with enhanced Assamese intelligence and image tools!', max_length=300)),
                ('action_text', models.CharField(default='Try Now →', max_length=100)),
                ('action_url', models.CharField(default='https://chat.aiaxom.co.in', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Announcement Banner',
                'verbose_name_plural': 'Announcement Banners',
            },
        ),
        migrations.CreateModel(
            name='InsightArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=320, unique=True)),
                ('category', models.CharField(choices=[('ai_research', 'AI Research'), ('product_update', 'Product Update'), ('culture_language', 'Culture & Language'), ('guides_tutorials', 'Guides & Tutorials'), ('community', 'Community')], default='product_update', max_length=50)),
                ('excerpt', models.TextField(help_text='Short 2-3 line summary shown on the landing cards')),
                ('content', models.TextField(blank=True, help_text='Full markdown or HTML content of the article')),
                ('read_time', models.CharField(default='4 min read', max_length=50)),
                ('cover_image_url', models.CharField(blank=True, help_text='Image URL or gradient preset', max_length=500, null=True)),
                ('gradient_from', models.CharField(default='#a855f7', help_text='Hex or Tailwind color for banner', max_length=50)),
                ('gradient_to', models.CharField(default='#ec4899', help_text='Hex or Tailwind color for banner', max_length=50)),
                ('author_name', models.CharField(default='Axom AI Team', max_length=100)),
                ('external_link', models.CharField(blank=True, help_text='Optional direct link to external article or blog', max_length=500)),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('published_at', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Insight & Blog Article',
                'verbose_name_plural': 'Insights & Blog Articles',
                'ordering': ['order', '-published_at'],
            },
        ),
        migrations.CreateModel(
            name='LandingFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('category', models.CharField(choices=[('general', 'General'), ('features', 'Features & AI Models'), ('pricing', 'Pricing & Payments'), ('privacy', 'Data & Privacy')], default='general', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Landing FAQ',
                'verbose_name_plural': 'Landing FAQs',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LandingFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('tagline', models.CharField(default='Native Assamese Intelligence', max_length=100)),
                ('description', models.TextField()),
                ('badge', models.CharField(blank=True, default='Core Engine', max_length=50)),
                ('icon_class', models.CharField(default='fa-solid fa-brain', help_text='FontAwesome icon class', max_length=80)),
                ('gradient_color', models.CharField(default='from-purple-500 to-indigo-500', max_length=100)),
                ('action_url', models.CharField(default='https://chat.aiaxom.co.in', max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Landing Feature Card',
                'verbose_name_plural': 'Landing Feature Cards',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LandingUseCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience_key', models.CharField(choices=[('students', 'Students & Learners'), ('professionals', 'Working Professionals'), ('business', 'Local Businesses & Shops'), ('creators', 'Content Creators & Writers'), ('researchers', 'Historians & Researchers'), ('developers', 'Developers & Builders')], max_length=50, unique=True)),
                ('tab_title', models.CharField(max_length=100)),
                ('headline', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('bullet_points', models.TextField(help_text='Enter points separated by newlines')),
                ('icon_class', models.CharField(default='fa-solid fa-graduation-cap', max_length=80)),
                ('cta_text', models.CharField(default='Start for Free', max_length=100)),
                ('cta_url', models.CharField(default='https://chat.aiaxom.co.in', max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Use Case Tab',
                'verbose_name_plural': 'Use Case Tabs',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteHeroConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_text', models.CharField(default='অসমৰ নিজা AI প্লেটফৰ্ম • Axom AI 2.0', max_length=200)),
                ('badge_link', models.CharField(default='#tools', max_length=255)),
                ('main_heading_prefix', models.CharField(default='The Power of AI,', max_length=200)),
                ('main_heading_highlight', models.CharField(default='Rooted in Assam.', max_length=200)),
                ('subheading_assamese', models.TextField(default='অসমৰ প্ৰথমটো থলুৱা কৃত্ৰিম বুদ্ধিমত্তা সহায়ক — যিয়ে অসমীয়া ভাষা আৰু সংস্কৃতি সঠিকভাৱে বুজি পায়।')),
                ('subheading_english', models.TextField(default='From fluent Assamese chat to instant image generation, document intelligence and automated workflows — built for the next generation of Assam.')),
                ('cta_primary_text', models.CharField(default='Start Chatting Free', max_length=100)),
                ('cta_primary_url', models.CharField(default='https://chat.aiaxom.co.in', max_length=255)),
                ('cta_secondary_text', models.CharField(default='Explore AI Tools', max_length=100)),
                ('cta_secondary_url', models.CharField(default='#tools', max_length=255)),
                ('stat_users', models.CharField(default='15,000+', max_length=50)),
                ('stat_users_label', models.CharField(default='Active Users in Assam', max_length=100)),
                ('stat_accuracy', models.CharField(default='99.4%', max_length=50)),
                ('stat_accuracy_label', models.CharField(default='Assamese Dialect Accuracy', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Section Configuration',
                'verbose_name_plural': 'Hero Section Configuration',
            },
        ),
        migrations.CreateModel(
            name='SiteSEOSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(default="Axom AI — The Power of AI for Everyone | Assam's Native AI Platform", max_length=200)),
                ('meta_description', models.TextField(default="Axom AI is Assam's first indigenous AI platform. Chat in native Assamese, generate AI images, summarize PDFs, and search live web with world-class AI.")),
                ('meta_keywords', models.CharField(default='Axom AI, Assamese AI, Assam AI Assistant, Assamese ChatGPT, Assamese OCR, AI in Assam, Axom LLM', max_length=500)),
                ('og_title', models.CharField(default="Axom AI — Assam's Own AI Platform", max_length=200)),
                ('og_description', models.TextField(default='Native Assamese intelligence, ChatGPT-grade reasoning, image generation, and document tools built for Assam.')),
                ('og_image_url', models.CharField(default='https://aiaxom.co.in/static/dist/hero/assam.avif', max_length=500)),
                ('gtm_container_id', models.CharField(default='GTM-K4N88ZBR', max_length=50)),
                ('footer_tagline', models.CharField(default='অসমৰ প্ৰথমটো থলুৱা AI প্লেটফৰ্ম • Made with ❤️ for Assam', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SEO & Meta Settings',
                'verbose_name_plural': 'SEO & Meta Settings',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('role_designation', models.CharField(help_text='e.g., Student, Cotton University / Entrepreneur, Guwahati', max_length=200)),
                ('avatar_initials', models.CharField(default='AK', max_length=10)),
                ('quote_assamese', models.TextField()),
                ('quote_english', models.TextField(blank=True)),
                ('rating', models.PositiveIntegerField(default=5)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Testimonial Review',
                'verbose_name_plural': 'Testimonial Reviews',
                'ordering': ['order', 'id'],
            },
        ),
    ]
