# Generated by Django 5.2.17 on 2026-09-09 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentcms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteheroconfig',
            name='stat_accuracy',
        ),
        migrations.RemoveField(
            model_name='siteheroconfig',
            name='stat_accuracy_label',
        ),
        migrations.RemoveField(
            model_name='siteheroconfig',
            name='stat_users',
        ),
        migrations.RemoveField(
            model_name='siteheroconfig',
            name='stat_users_label',
        ),
        migrations.AddField(
            model_name='siteheroconfig',
            name='trust_badge_1',
            field=models.CharField(default='No credit card required', max_length=100),
        ),
        migrations.AddField(
            model_name='siteheroconfig',
            name='trust_badge_2',
            field=models.CharField(default='Fast & secure', max_length=100),
        ),
        migrations.AddField(
            model_name='siteheroconfig',
            name='trust_badge_3',
            field=models.CharField(default='Accessible for everyone', max_length=100),
        ),
    ]
