# Generated by Django on 2026-09-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentcms', '0002_remove_siteheroconfig_stat_accuracy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Partner / Tech name e.g. Google Gemini, Groq', max_length=150)),
                ('logo_image_url', models.CharField(blank=True, help_text='Optional Image URL (if blank, text is shown)', max_length=500, null=True)),
                ('website_url', models.CharField(blank=True, help_text='Optional link', max_length=300, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Partner / Tech Logo',
                'verbose_name_plural': 'Partner / Tech Logos',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='siteheroconfig',
            name='logo_strip_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='siteheroconfig',
            name='logo_strip_headline',
            field=models.CharField(default='Built with the best', max_length=150),
        ),
    ]
