# Generated by Django on 2026-09-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentcms', '0003_partnerlogo_siteheroconfig_logo_strip_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteheroconfig',
            name='explore_badge',
            field=models.CharField(default='Explore', max_length=100),
        ),
        migrations.AddField(
            model_name='siteheroconfig',
            name='explore_title_prefix',
            field=models.CharField(default='A Complete AI Toolkit', max_length=200),
        ),
        migrations.AddField(
            model_name='siteheroconfig',
            name='explore_title_highlight',
            field=models.CharField(default='for Modern Needs', max_length=200),
        ),
        migrations.AddField(
            model_name='siteheroconfig',
            name='explore_subheading',
            field=models.TextField(default='Everything you need to be more productive, creative and informed — in one powerful platform.'),
        ),
        migrations.AddField(
            model_name='siteheroconfig',
            name='explore_section_active',
            field=models.BooleanField(default=True),
        ),
    ]
