# Generated by Django on 2026-09-09
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentcms', '0004_add_explore_section_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteheroconfig',
            name='usecases_badge',
            field=models.CharField(default='Use Cases', max_length=100),
        ),
        migrations.AddField(
            model_name='siteheroconfig',
            name='usecases_title_prefix',
            field=models.CharField(default='Built for', max_length=200),
        ),
        migrations.AddField(
            model_name='siteheroconfig',
            name='usecases_title_highlight',
            field=models.CharField(default='Real People, Real Impact', max_length=200),
        ),
        migrations.AddField(
            model_name='siteheroconfig',
            name='usecases_subheading',
            field=models.TextField(default="Whoever you are, wherever you're from — Axom AI adapts to your work."),
        ),
        migrations.AddField(
            model_name='siteheroconfig',
            name='usecases_section_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='landingusecase',
            name='card_1_title',
            field=models.CharField(default='Assignment Helper', max_length=150),
        ),
        migrations.AddField(
            model_name='landingusecase',
            name='card_1_desc',
            field=models.TextField(default='Get instant explanations in Assamese, Hindi or English for any subject.'),
        ),
        migrations.AddField(
            model_name='landingusecase',
            name='card_1_icon',
            field=models.CharField(default='fa-solid fa-graduation-cap', max_length=80),
        ),
        migrations.AddField(
            model_name='landingusecase',
            name='card_1_color',
            field=models.CharField(default='text-fuchsia-400', max_length=50),
        ),
        migrations.AddField(
            model_name='landingusecase',
            name='card_2_title',
            field=models.CharField(default='Study Summaries', max_length=150),
        ),
        migrations.AddField(
            model_name='landingusecase',
            name='card_2_desc',
            field=models.TextField(default='Turn 100-page PDFs into concise notes in 3 lengths and 3 languages.'),
        ),
        migrations.AddField(
            model_name='landingusecase',
            name='card_2_icon',
            field=models.CharField(default='fa-solid fa-file-pdf', max_length=80),
        ),
        migrations.AddField(
            model_name='landingusecase',
            name='card_2_color',
            field=models.CharField(default='text-purple-400', max_length=50),
        ),
        migrations.AddField(
            model_name='landingusecase',
            name='card_3_title',
            field=models.CharField(default='Essay & Report', max_length=150),
        ),
        migrations.AddField(
            model_name='landingusecase',
            name='card_3_desc',
            field=models.TextField(default='Draft essays and research reports with source citations.'),
        ),
        migrations.AddField(
            model_name='landingusecase',
            name='card_3_icon',
            field=models.CharField(default='fa-solid fa-pen-nib', max_length=80),
        ),
        migrations.AddField(
            model_name='landingusecase',
            name='card_3_color',
            field=models.CharField(default='text-pink-400', max_length=50),
        ),
        migrations.AlterField(
            model_name='landingusecase',
            name='audience_key',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
