# Generated by Django 5.2.17 on 2026-09-10 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentcms', '0010_add_logo_dimensions'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQPageConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge', models.CharField(default='Help Center & FAQs', max_length=100)),
                ('title_prefix', models.CharField(default='Frequently Asked', max_length=200)),
                ('title_highlight', models.CharField(default='Questions', max_length=200)),
                ('subheading', models.TextField(default='Everything you need to know about Axom AI, our Assamese language intelligence, tools, subscriptions and data privacy.')),
                ('search_placeholder', models.CharField(default='Search questions (e.g., pricing, Assamese AI, file limits)...', max_length=200)),
                ('support_box_title', models.CharField(default='Still have questions?', max_length=200)),
                ('support_box_desc', models.TextField(default="Can't find the answer you're looking for? Our support team and community are here to help.")),
                ('support_button_text', models.CharField(default='Contact Support', max_length=100)),
                ('support_button_url', models.CharField(default='https://user.aiaxom.co.in/support/', max_length=300)),
                ('chat_button_text', models.CharField(default='Ask Axom AI', max_length=100)),
                ('chat_button_url', models.CharField(default='https://chat.aiaxom.co.in', max_length=300)),
                ('meta_title', models.CharField(default='FAQs & Help Center — Axom AI', max_length=255)),
                ('meta_description', models.TextField(default='Find answers to common questions about Axom AI models, word limits, plans, and Assamese features.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ Page Configuration',
                'verbose_name_plural': 'FAQ Page Configuration',
            },
        ),
        migrations.RemoveField(
            model_name='siteheroconfig',
            name='trust_badge_3',
        ),
        migrations.AddField(
            model_name='landingfaq',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='landingfaq',
            name='show_on_homepage',
            field=models.BooleanField(default=True, help_text='Display in the homepage FAQ section'),
        ),
        migrations.AddField(
            model_name='landingfaq',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='logo_image_url',
            field=models.CharField(default='/axom-logo.svg', max_length=500),
        ),
        migrations.AlterField(
            model_name='headersettings',
            name='logo_image_url',
            field=models.CharField(default='/axom-logo.svg', max_length=500),
        ),
        migrations.AlterField(
            model_name='landingusecase',
            name='bullet_points',
            field=models.TextField(blank=True, default='', help_text='Optional points'),
        ),
        migrations.AlterField(
            model_name='landingusecase',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='landingusecase',
            name='headline',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
