# Generated by Django 5.2.17 on 2026-09-14 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentcms', '0012_aboutpageconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordToPdfToolConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_badge_text', models.CharField(default='⚡ Free: 20 Files / Day • 👑 Pro: Batch Convert 20 Files at Once', max_length=255)),
                ('hero_heading_prefix', models.CharField(default='Free', max_length=150)),
                ('hero_heading_highlight', models.CharField(default='Word to PDF', max_length=150)),
                ('hero_heading_suffix', models.CharField(default='Converter Online', max_length=150)),
                ('hero_description', models.TextField(default='Convert your Microsoft Word (.DOCX, .DOC), Rich Text, and text files into professional, print-ready PDF documents instantly. Free accounts can convert up to 20 files per day. Upgrade to Premium for unlimited daily conversions and Pro Batch Mode to convert up to 20 files simultaneously in 1 click!')),
                ('free_daily_limit', models.IntegerField(default=20, help_text='Number of files free users can convert per day')),
                ('pro_batch_limit', models.IntegerField(default=20, help_text='Max files in one batch for Pro users')),
                ('max_file_size_mb', models.IntegerField(default=25, help_text='Max file size in MB')),
                ('how_it_works_title', models.CharField(default='How to Convert Word to PDF in 3 Easy Steps', max_length=255)),
                ('how_it_works_subheading', models.TextField(default='No complex software installation or account creation required. Fast and frictionless.')),
                ('step_1_title', models.CharField(default='Upload Document', max_length=150)),
                ('step_1_desc', models.TextField(default='Drag and drop your DOCX or DOC file into the converter box above or choose it from your local storage.')),
                ('step_2_title', models.CharField(default='Instant Processing', max_length=150)),
                ('step_2_desc', models.TextField(default='Click Convert. Our high-fidelity document engine parses structures, styles, margins, and media in seconds.')),
                ('step_3_title', models.CharField(default='Download PDF', max_length=150)),
                ('step_3_desc', models.TextField(default='Download your clean, publication-ready PDF document directly to your device. No watermarks, ever.')),
                ('why_title', models.CharField(default='Why Axom AI Word to PDF is the Superior Choice', max_length=255)),
                ('why_subheading', models.TextField(default='Engineered for students, educators, legal professionals, and businesses who demand accuracy and privacy.')),
                ('benefit_1_title', models.CharField(default='Lossless Layout Fidelity', max_length=150)),
                ('benefit_1_desc', models.TextField(default='Headers, footers, footnotes, complex tables, embedded charts, and custom fonts stay strictly aligned without shifting pages.')),
                ('benefit_2_title', models.CharField(default='Zero Watermarks, 100% Free', max_length=150)),
                ('benefit_2_desc', models.TextField(default='No hidden subscription traps or promotional watermarks stamped across your pages. Clean documents ready for official submissions.')),
                ('benefit_3_title', models.CharField(default='Automatic File Purging', max_length=150)),
                ('benefit_3_desc', models.TextField(default='Documents are processed securely via SSL encryption and purged automatically from our server memory right after conversion.')),
                ('benefit_4_title', models.CharField(default='Universal Device Support', max_length=150)),
                ('benefit_4_desc', models.TextField(default='Works seamlessly on iOS, Android, macOS, Windows, and Linux. No apps or browser extensions needed.')),
                ('benefit_5_title', models.CharField(default='Sub-3-Second Speed', max_length=150)),
                ('benefit_5_desc', models.TextField(default='High-speed optimized micro-services convert standard documents in less than 3 seconds with minimal bandwidth usage.')),
                ('benefit_6_title', models.CharField(default='Multi-Format Compatibility', max_length=150)),
                ('benefit_6_desc', models.TextField(default='Handles DOCX, DOC, RTF, TXT, and ODT with automatic format detection and smart structure extraction.')),
                ('comparison_badge', models.CharField(default='Direct Feature Comparison', max_length=150)),
                ('comparison_title', models.CharField(default='Axom AI vs. Traditional Word to PDF Converters', max_length=255)),
                ('comparison_subheading', models.TextField(default='See why users choose Axom AI over paywalled and ad-heavy alternatives.')),
                ('comparison_matrix_json', models.TextField(blank=True, default='[\n  {\n    "feature": "Daily Limit & Cost",\n    "axom": "Free 20 files/day (Unlimited on Pro)",\n    "other": "1-2 files per day limit",\n    "paid": "$10 - $20 / month",\n    "axom_check": true,\n    "other_check": false\n  },\n  {\n    "feature": "Batch Conversion",\n    "axom": "Up to 20 files at once (Pro)",\n    "other": "Single file only",\n    "paid": "Supported (Paid only)",\n    "axom_check": true,\n    "other_check": false\n  },\n  {\n    "feature": "Watermarks",\n    "axom": "Never (100% Clean)",\n    "other": "Added to PDF",\n    "paid": "Clean (Paid only)",\n    "axom_check": true,\n    "other_check": false\n  },\n  {\n    "feature": "Account / Registration",\n    "axom": "No signup needed",\n    "other": "Often forced signup",\n    "paid": "Required signup + Card",\n    "axom_check": true,\n    "other_check": false\n  },\n  {\n    "feature": "Document Privacy",\n    "axom": "Auto-purged immediately",\n    "other": "Stored up to 24 hours",\n    "paid": "Cloud stored",\n    "axom_check": true,\n    "other_check": false\n  },\n  {\n    "feature": "Typography & Tables",\n    "axom": "High-precision rendering",\n    "other": "Frequent alignment errors",\n    "paid": "High-precision",\n    "axom_check": true,\n    "other_check": false\n  }\n]', help_text='Custom comparison rows JSON')),
                ('tech_spec_title', models.CharField(default='Technical Specifications & Supported Standards', max_length=255)),
                ('tech_spec_inputs', models.CharField(default='.docx, .doc, .rtf, .txt, .odt', max_length=200)),
                ('tech_spec_output', models.CharField(default='PDF 1.7 / ISO 32000-1 (Vector)', max_length=200)),
                ('tech_spec_max_size', models.CharField(default='25 Megabytes (MB)', max_length=100)),
                ('tech_spec_security', models.CharField(default='TLS 1.3 / SSL 256-bit', max_length=100)),
                ('faq_section_title', models.CharField(default='Frequently Asked Questions', max_length=255)),
                ('faq_section_subheading', models.TextField(default='Got questions about Word to PDF conversion? Find verified answers below.')),
                ('cta_title', models.CharField(default='Convert Your Word Documents in Seconds', max_length=255)),
                ('cta_desc', models.TextField(default='Experience fast, private, and watermark-free conversions trusted by users across Assam and India.')),
                ('cta_btn_primary_text', models.CharField(default='Upload Word File Now', max_length=100)),
                ('cta_btn_primary_url', models.CharField(default='#converter', max_length=300)),
                ('cta_btn_secondary_text', models.CharField(default='Explore All AI & Document Tools', max_length=100)),
                ('cta_btn_secondary_url', models.CharField(default='https://chat.aiaxom.co.in/tools', max_length=300)),
                ('meta_title', models.CharField(default='Free Word to PDF Converter Online — Convert DOCX to PDF | Axom AI', max_length=255)),
                ('meta_description', models.TextField(default='Convert Microsoft Word (.docx, .doc) to PDF online for free in seconds. Preserve original formatting, tables, fonts, and images. 100% secure with automatic file deletion.')),
                ('meta_keywords', models.TextField(default='Word to PDF, Word to PDF converter, convert word to pdf online free, docx to pdf converter, doc to pdf, convert word document to pdf, best free word to pdf converter, word to pdf without watermark, axom ai tools, assam ai document converter, free docx to pdf high quality')),
                ('canonical_url', models.CharField(default='https://aiaxom.co.in/tools/word-to-pdf/', max_length=300)),
                ('og_image_url', models.CharField(default='https://aiaxom.co.in/static/dist/hero/assam.avif', max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Word to PDF Tool Configuration',
                'verbose_name_plural': 'Word to PDF Tool Configuration',
            },
        ),
        migrations.CreateModel(
            name='WordToPdfFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tool_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='contentcms.wordtopdftoolconfig')),
            ],
            options={
                'verbose_name': 'Word to PDF FAQ',
                'verbose_name_plural': 'Word to PDF FAQs',
                'ordering': ['order', 'id'],
            },
        ),
    ]
