# Generated by Django 5.2.17 on 2026-09-23 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentcms', '0014_convertertoolconfig_alter_headermegamenuitem_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteheroconfig',
            name='entity_attr1_label',
            field=models.CharField(default='Headquarters', max_length=100),
        ),
        migrations.AddField(
            model_name='siteheroconfig',
            name='entity_attr1_value',
            field=models.CharField(default='Guwahati, Assam (781001)', max_length=200),
        ),
        migrations.AddField(
            model_name='siteheroconfig',
            name='entity_attr2_label',
            field=models.CharField(default='Languages Supported', max_length=100),
        ),
        migrations.AddField(
            model_name='siteheroconfig',
            name='entity_attr2_value',
            field=models.CharField(default='Assamese, English, Hindi', max_length=200),
        ),
        migrations.AddField(
            model_name='siteheroconfig',
            name='entity_attr3_label',
            field=models.CharField(default='Core Architecture', max_length=100),
        ),
        migrations.AddField(
            model_name='siteheroconfig',
            name='entity_attr3_value',
            field=models.CharField(default='Assamese RAG & IndicTrans2', max_length=200),
        ),
        migrations.AddField(
            model_name='siteheroconfig',
            name='entity_attr4_label',
            field=models.CharField(default='Pricing in India', max_length=100),
        ),
        migrations.AddField(
            model_name='siteheroconfig',
            name='entity_attr4_value',
            field=models.CharField(default='₹0 Free Tier • UPI via Razorpay', max_length=200),
        ),
        migrations.AddField(
            model_name='siteheroconfig',
            name='entity_badge_text',
            field=models.CharField(default="Assam's Sovereign AI Entity Profile", max_length=150),
        ),
        migrations.AddField(
            model_name='siteheroconfig',
            name='entity_description',
            field=models.TextField(default='<strong>Axom AI</strong> (stylized as <strong>AI Axom</strong>, Assamese: <strong class="font-assamese">অসম এআই</strong>, also commonly referred to as <strong>Assam AI</strong>) is Assam\'s flagship indigenous artificial intelligence platform headquartered in Guwahati, Assam, India. Founded by AI researcher <strong>Samarjit Kashyap</strong>, the platform delivers authentic Assamese Large Language Model (LLM) reasoning, scanned document OCR, 20+ file utilities, generative image synthesis, and live web search for students, researchers, businesses, and creators across Northeast India.', help_text='HTML allowed (e.g. <strong>bold</strong>) — rendered as-is on the homepage.'),
        ),
        migrations.AddField(
            model_name='siteheroconfig',
            name='entity_heading',
            field=models.CharField(default='What is Axom AI? (Assam AI Definition & Architecture)', max_length=250),
        ),
        migrations.AddField(
            model_name='siteheroconfig',
            name='entity_section_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='siteheroconfig',
            name='entity_verified_text',
            field=models.CharField(default='Official Verified Platform', max_length=100),
        ),
    ]
