# Generated by Django 5.2.17 on 2026-10-07 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentcms', '0015_siteheroconfig_entity_attr1_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteheroconfig',
            name='pricing_glance_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='siteheroconfig',
            name='pricing_glance_badge',
            field=models.CharField(default='Zero Foreign Markups', max_length=100),
        ),
        migrations.AddField(
            model_name='siteheroconfig',
            name='pricing_glance_text',
            field=models.TextField(blank=True, default='Free (₹0/mo) Ideal for casual queries, students & basic Assamese chat. Starter (₹199/mo or ₹159 billed yearly) Perfect for researchers, creators and daily regular users. Pro (₹499/mo or ₹399 billed yearly) Unleash full power: advanced models, OCR & 20+ file tools. Business (₹1499/mo or ₹1199 billed yearly) For offices, institutions & teams needing high volume & API.'),
        ),
        migrations.AddField(
            model_name='siteheroconfig',
            name='pricing_glance_title',
            field=models.CharField(default='Axom AI Pricing at a Glance', max_length=200),
        ),
    ]
