# Generated by Django 5.2.17 on 2026-10-07 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentcms', '0016_siteheroconfig_pricing_glance_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingComparisonCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Core AI Models & Intelligence', max_length=150)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Pricing Comparison Category',
                'verbose_name_plural': 'Pricing Comparison Categories',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='siteheroconfig',
            name='pricing_comparison_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='siteheroconfig',
            name='pricing_comparison_badge',
            field=models.CharField(default='Full Plan Comparison', max_length=100),
        ),
        migrations.AddField(
            model_name='siteheroconfig',
            name='pricing_comparison_subheading',
            field=models.TextField(default='Detailed breakdown of models, tools, limits, and enterprise capabilities across all Axom AI tiers.'),
        ),
        migrations.AddField(
            model_name='siteheroconfig',
            name='pricing_comparison_title',
            field=models.CharField(default='Compare Every Feature Side-by-Side', max_length=200),
        ),
        migrations.CreateModel(
            name='PricingComparisonRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(help_text='e.g. Monthly Word Quota', max_length=200)),
                ('free_val', models.CharField(default='true', help_text="Can be 'true', 'false', or text like '5,000 words'", max_length=150)),
                ('starter_val', models.CharField(default='true', max_length=150)),
                ('pro_val', models.CharField(default='true', max_length=150)),
                ('business_val', models.CharField(default='true', max_length=150)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='contentcms.pricingcomparisoncategory')),
            ],
            options={
                'verbose_name': 'Pricing Comparison Row',
                'verbose_name_plural': 'Pricing Comparison Rows',
                'ordering': ['order', 'id'],
            },
        ),
    ]
