# Generated by Django 5.2.17 on 2026-10-07 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentcms', '0017_pricingcomparisoncategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteheroconfig',
            name='pricing_bottom_cta_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='siteheroconfig',
            name='pricing_bottom_cta_heading',
            field=models.CharField(default='Experience the Future of Assamese AI', max_length=250),
        ),
        migrations.AddField(
            model_name='siteheroconfig',
            name='pricing_bottom_cta_primary_text',
            field=models.CharField(default='Start Chatting Free', max_length=100),
        ),
        migrations.AddField(
            model_name='siteheroconfig',
            name='pricing_bottom_cta_primary_url',
            field=models.CharField(default='https://chat.aiaxom.co.in/', max_length=300),
        ),
        migrations.AddField(
            model_name='siteheroconfig',
            name='pricing_bottom_cta_secondary_text',
            field=models.CharField(default='Explore 20+ Tools', max_length=100),
        ),
        migrations.AddField(
            model_name='siteheroconfig',
            name='pricing_bottom_cta_secondary_url',
            field=models.CharField(default='https://aiaxom.co.in/tools', max_length=300),
        ),
        migrations.AddField(
            model_name='siteheroconfig',
            name='pricing_bottom_cta_subheading',
            field=models.TextField(default='Join thousands of students, researchers, creators and businesses across Assam accelerating their workflow with Axom AI.'),
        ),
        migrations.AddField(
            model_name='siteheroconfig',
            name='pricing_callouts_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='siteheroconfig',
            name='pricing_enterprise_badge',
            field=models.CharField(default='Enterprises & Government', max_length=100),
        ),
        migrations.AddField(
            model_name='siteheroconfig',
            name='pricing_enterprise_btn_text',
            field=models.CharField(default='Talk to Enterprise Sales', max_length=100),
        ),
        migrations.AddField(
            model_name='siteheroconfig',
            name='pricing_enterprise_btn_url',
            field=models.CharField(default='mailto:support@aiaxom.co.in?subject=Enterprise%20and%20Government%20Inquiry%20-%20Axom%20AI', max_length=300),
        ),
        migrations.AddField(
            model_name='siteheroconfig',
            name='pricing_enterprise_desc',
            field=models.TextField(default='Need on-premise private deployment, customized RAG knowledge bases for regional government departments, news agencies, or bank compliant Assamese document pipelines? Our Guwahati engineering team builds turnkey solutions.'),
        ),
        migrations.AddField(
            model_name='siteheroconfig',
            name='pricing_enterprise_title',
            field=models.CharField(default='Custom LLM & Sovereign AI', max_length=200),
        ),
        migrations.AddField(
            model_name='siteheroconfig',
            name='pricing_student_badge',
            field=models.CharField(default='Education & Research', max_length=100),
        ),
        migrations.AddField(
            model_name='siteheroconfig',
            name='pricing_student_btn_text',
            field=models.CharField(default='Request Student Discount', max_length=100),
        ),
        migrations.AddField(
            model_name='siteheroconfig',
            name='pricing_student_btn_url',
            field=models.CharField(default='mailto:support@aiaxom.co.in?subject=Student%20Discount%20Inquiry%20-%20Axom%20AI', max_length=300),
        ),
        migrations.AddField(
            model_name='siteheroconfig',
            name='pricing_student_desc',
            field=models.TextField(default='Are you a student preparing for APSC, UPSC, Assam Police, or studying at Gauhati University, Cotton University, Tezpur University, or IIT Guwahati? We provide special educational subsidies and group lab licensing across Assam.'),
        ),
        migrations.AddField(
            model_name='siteheroconfig',
            name='pricing_student_title',
            field=models.CharField(default='Student & Academic Rebates', max_length=200),
        ),
        migrations.AddField(
            model_name='siteheroconfig',
            name='pricing_trust_card1_desc',
            field=models.TextField(default='Pay seamlessly with Google Pay, PhonePe, Paytm, BHIM UPI, RuPay, Visa, MasterCard, and Netbanking from 50+ Indian banks.'),
        ),
        migrations.AddField(
            model_name='siteheroconfig',
            name='pricing_trust_card1_icon',
            field=models.CharField(default='fa-solid fa-credit-card', max_length=100),
        ),
        migrations.AddField(
            model_name='siteheroconfig',
            name='pricing_trust_card1_tags',
            field=models.CharField(default='UPI Autopay, RuPay, Razorpay Secured', max_length=255),
        ),
        migrations.AddField(
            model_name='siteheroconfig',
            name='pricing_trust_card1_title',
            field=models.CharField(default='100% Indian Payment Methods', max_length=200),
        ),
        migrations.AddField(
            model_name='siteheroconfig',
            name='pricing_trust_card2_desc',
            field=models.TextField(default='Add your company GSTIN during checkout to receive automated tax invoices for full Input Tax Credit (ITC) claiming.'),
        ),
        migrations.AddField(
            model_name='siteheroconfig',
            name='pricing_trust_card2_icon',
            field=models.CharField(default='fa-solid fa-file-invoice-dollar', max_length=100),
        ),
        migrations.AddField(
            model_name='siteheroconfig',
            name='pricing_trust_card2_tags',
            field=models.CharField(default='Instant PDF Invoices, B2B Friendly', max_length=255),
        ),
        migrations.AddField(
            model_name='siteheroconfig',
            name='pricing_trust_card2_title',
            field=models.CharField(default='GST Compliant Invoicing', max_length=200),
        ),
        migrations.AddField(
            model_name='siteheroconfig',
            name='pricing_trust_card3_desc',
            field=models.TextField(default='No hidden phone calls or dark patterns. Upgrade, downgrade, or cancel your subscription instantly from your settings dashboard.'),
        ),
        migrations.AddField(
            model_name='siteheroconfig',
            name='pricing_trust_card3_icon',
            field=models.CharField(default='fa-solid fa-rotate-left', max_length=100),
        ),
        migrations.AddField(
            model_name='siteheroconfig',
            name='pricing_trust_card3_tags',
            field=models.CharField(default='Zero Lock-in, Immediate Downgrade', max_length=255),
        ),
        migrations.AddField(
            model_name='siteheroconfig',
            name='pricing_trust_card3_title',
            field=models.CharField(default='Cancel Anytime with 1 Click', max_length=200),
        ),
        migrations.AddField(
            model_name='siteheroconfig',
            name='pricing_trust_cards_active',
            field=models.BooleanField(default=True),
        ),
    ]
