# Generated by Django 5.2.17 on 2026-10-07 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentcms', '0018_siteheroconfig_pricing_bottom_cta_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pricing FAQ',
                'verbose_name_plural': 'Pricing FAQs',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='siteheroconfig',
            name='pricing_faq_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='siteheroconfig',
            name='pricing_faq_badge',
            field=models.CharField(default='Pricing FAQ', max_length=100),
        ),
        migrations.AddField(
            model_name='siteheroconfig',
            name='pricing_faq_subheading',
            field=models.TextField(default='Clear answers regarding our billing cycles, word quotas, payment methods, and cancellation policy.'),
        ),
        migrations.AddField(
            model_name='siteheroconfig',
            name='pricing_faq_title',
            field=models.CharField(default='Frequently Asked Questions', max_length=200),
        ),
    ]
