# Generated by Django 5.2.17 on 2026-10-07 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentcms', '0019_pricingfaq_siteheroconfig_pricing_faq_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UseCasesPageConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_badge_text', models.CharField(default='⚡ Real People • Real Impact • Sovereign Assamese AI', max_length=255)),
                ('hero_heading_prefix', models.CharField(default='Built for', max_length=200)),
                ('hero_heading_highlight', models.CharField(default='Real People, Real Impact', max_length=200)),
                ('hero_heading_suffix', models.CharField(blank=True, default='', max_length=200)),
                ('hero_subtitle', models.TextField(default='From school classrooms in Dibrugarh to administrative offices in Dispur and tech startups in Guwahati — discover how Axom AI is driving everyday productivity, academic success, and regional empowerment across Assam and Northeast India.')),
                ('aeo_badge', models.CharField(default='AEO Direct Summary • Generative Engine Overview', max_length=200)),
                ('aeo_title', models.CharField(default='What are the Practical Use Cases of Axom AI?', max_length=255)),
                ('aeo_description', models.TextField(default='Axom AI is designed as a sovereign, multi-purpose artificial intelligence ecosystem specifically customized for the linguistic, cultural, and professional requirements of Assam and Northeast India. Key use cases include bilingual academic tutoring for students, APSC civil services preparation with authentic regional General Knowledge, business communication automation for regional MSMEs, bilingual land and legal record analysis, healthcare outreach translation, and full-stack code development — all delivered over low-latency Indian cloud infrastructure with 100% data sovereignty.')),
                ('aeo_point1', models.CharField(default='15M+ Assamese Speakers Served', max_length=200)),
                ('aeo_point2', models.CharField(default='SEBA, AHSEC & APSC Aligned', max_length=200)),
                ('aeo_point3', models.CharField(default='DPDP Act 2023 Compliant', max_length=200)),
                ('stat_1_val', models.CharField(default='15M+', max_length=50)),
                ('stat_1_label', models.CharField(default='Assamese Speakers Empowered', max_length=150)),
                ('stat_2_val', models.CharField(default='30+', max_length=50)),
                ('stat_2_label', models.CharField(default='Integrated AI & Document Tools', max_length=150)),
                ('stat_3_val', models.CharField(default='99.2%', max_length=50)),
                ('stat_3_label', models.CharField(default='Assamese Grammatical Accuracy', max_length=150)),
                ('stat_4_val', models.CharField(default='<0.8s', max_length=50)),
                ('stat_4_label', models.CharField(default='Domestic Indian Cloud Latency', max_length=150)),
                ('sectors_badge', models.CharField(default='In-Depth Industry Solutions', max_length=150)),
                ('sectors_title', models.CharField(default='Explore How Axom AI Powers Every Sector', max_length=255)),
                ('sectors_subtitle', models.TextField(default='Detailed breakdowns of practical workflows, problem-solving capabilities, and proven results.')),
                ('comparison_badge', models.CharField(default='The Sovereign Advantage', max_length=150)),
                ('comparison_title', models.CharField(default='Why Axom AI is Unmatched for Assam & Regional Workflows', max_length=255)),
                ('comparison_subtitle', models.TextField(default='Comparing Axom AI against generic international chatbots and fragmented software.')),
                ('authority_badge', models.CharField(default='Sovereign AI for Assam & Northeast India', max_length=150)),
                ('authority_title', models.CharField(default='Built in Assam, Serving Millions Worldwide', max_length=255)),
                ('authority_description', models.TextField(default='Headquartered in Guwahati, Assam, Axom AI is committed to building sovereign regional artificial intelligence infrastructure. By developing localized linguistic benchmarks and integrating domestic cloud processing, we ensure that technological advancement preserves our heritage while empowering the next generation of researchers, leaders, and entrepreneurs.')),
                ('faq_badge', models.CharField(default='Answers to Common Questions', max_length=150)),
                ('faq_title', models.CharField(default='Frequently Asked Questions about Axom AI Use Cases', max_length=255)),
                ('faq_subtitle', models.TextField(default='Got questions about how Axom AI fits your specific daily workflow or organization? Find verified answers below.')),
                ('cta_badge', models.CharField(default='Get Started in 10 Seconds — No Credit Card Required', max_length=150)),
                ('cta_heading', models.CharField(default='Experience the Impact of Sovereign AI Today', max_length=255)),
                ('cta_subheading', models.TextField(default='Join thousands of students, civil servants, business owners, and creators leveraging Axom AI every single day.')),
                ('cta_primary_btn_text', models.CharField(default='Launch AI Chat Workspace', max_length=100)),
                ('cta_primary_btn_url', models.CharField(default='https://chat.aiaxom.co.in/', max_length=300)),
                ('cta_secondary_btn_text', models.CharField(default='Explore All AI & Document Tools', max_length=100)),
                ('cta_secondary_btn_url', models.CharField(default='/tools', max_length=300)),
                ('meta_title', models.CharField(default='Axom AI Use Cases — Real-World AI Solutions for Assam & India | Students, Business & Creators', max_length=255)),
                ('meta_description', models.TextField(default='Discover how students, APSC aspirants, businesses, legal experts, healthcare pros, and creators use Axom AI across Assam & Northeast India. Native Assamese AI with real impact.')),
                ('meta_keywords', models.TextField(default='Axom AI use cases, Assam AI use cases, Assamese AI applications, AI in Assam, AI for students Assam, APSC exam AI preparation, AI for Assam government jobs, AI for businesses in Assam, Assamese document translator AI, Assamese legal AI, AI in healthcare Assam, AI for content creators Assamese, sovereign AI India use cases, Northeast India AI solutions')),
                ('og_image_url', models.CharField(default='https://aiaxom.co.in/static/dist/hero/assam.avif', max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Use Cases Page Configuration',
                'verbose_name_plural': 'Use Cases Page Configuration',
            },
        ),
        migrations.CreateModel(
            name='UseCaseSector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector_id', models.CharField(default='students', help_text='Unique slug e.g. students, aspirants, businesses', max_length=100)),
                ('badge', models.CharField(default='Academic Excellence', max_length=150)),
                ('icon_name', models.CharField(default='GraduationCap', help_text='Lucide icon name (GraduationCap, BookOpen, Briefcase, Scale, Stethoscope, Palette, Code2)', max_length=80)),
                ('color_gradient', models.CharField(default='from-fuchsia-500 to-purple-600', max_length=150)),
                ('text_color', models.CharField(default='text-fuchsia-700 dark:text-fuchsia-400', max_length=150)),
                ('border_color', models.CharField(default='border-fuchsia-500/30', max_length=150)),
                ('title', models.CharField(default='Students, Schools & Higher Education', max_length=255)),
                ('tagline', models.CharField(default='Personalized 24/7 bilingual tutoring in Assamese and English', max_length=255)),
                ('description', models.TextField(default='')),
                ('capabilities_raw', models.TextField(default='', help_text='One bullet capability per line')),
                ('impact_metric', models.CharField(default='40% Time Saved in Study Preparation', max_length=150)),
                ('cta_text', models.CharField(default='Start Studying with AI Tutor', max_length=100)),
                ('cta_url', models.CharField(default='https://chat.aiaxom.co.in/', max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sectors', to='contentcms.usecasespageconfig')),
            ],
            options={
                'verbose_name': 'Use Case Sector',
                'verbose_name_plural': 'Use Case Sectors',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UseCaseFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=350)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='contentcms.usecasespageconfig')),
            ],
            options={
                'verbose_name': 'Use Case FAQ',
                'verbose_name_plural': 'Use Case FAQs',
                'ordering': ['order', 'id'],
            },
        ),
    ]
