# Generated by Django 5.2.17 on 2026-10-07 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentcms', '0020_usecasespageconfig_usecasesector_usecasefaq'),
    ]

    operations = [
        migrations.AddField(
            model_name='usecasesector',
            name='short_title',
            field=models.CharField(blank=True, default='', help_text='Short label for top quick jump pill bar, e.g. Students, APSC, MSMEs', max_length=100),
        ),
    ]
