# Generated by Django 5.2.17 on 2026-10-07 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentcms', '0022_contactpageconfig_contactfaqitem_contactchannelitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpageconfig',
            name='og_image_url',
            field=models.CharField(default='https://aiaxom.co.in/static/dist/hero/assam.avif', max_length=500),
        ),
        migrations.AddField(
            model_name='faqpageconfig',
            name='og_image_url',
            field=models.CharField(default='https://aiaxom.co.in/static/dist/hero/assam.avif', max_length=500),
        ),
    ]
