# Generated by Django 5.2.17 on 2026-10-08 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentcms', '0023_aboutpageconfig_og_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insightarticle',
            name='faqs',
            field=models.JSONField(blank=True, default=list, help_text='List of FAQs for this article [{"question": "...", "answer": "..."}]'),
        ),
    ]
