# Generated by Django 5.2.17 on 2026-10-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentcms', '0025_privacypageconfig_termspageconfig_privacyfaqitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CMSLoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(db_index=True, max_length=64)),
                ('username', models.CharField(blank=True, db_index=True, max_length=150)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('last_failed_at', models.DateTimeField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'CMS Login Security Record',
                'verbose_name_plural': 'CMS Login Security Records',
                'indexes': [models.Index(fields=['ip_address', 'is_locked'], name='contentcms__ip_addr_3bbc02_idx'), models.Index(fields=['username', 'is_locked'], name='contentcms__usernam_138f26_idx')],
            },
        ),
    ]
