# Generated by Django 5.2.17 on 2026-09-17 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0005_seed_language_rules'),
    ]

    operations = [
        migrations.CreateModel(
            name='AITool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(db_index=True, max_length=64, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Convert', 'Convert'), ('Office', 'Office'), ('Organize', 'Organize'), ('Optimize', 'Optimize'), ('Security', 'Security'), ('OCR', 'OCR'), ('AI Tools', 'AI Tools'), ('Edit', 'Edit')], default='AI Tools', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('hint', models.CharField(blank=True, default='', max_length=150)),
                ('badge', models.CharField(blank=True, default='', max_length=50)),
                ('icon_class', models.CharField(blank=True, default='fa-solid fa-sparkles', max_length=100)),
                ('lucide_icon', models.CharField(blank=True, default='Sparkles', max_length=100)),
                ('color', models.CharField(blank=True, default='#ec4899', max_length=50)),
                ('color_class', models.CharField(blank=True, default='text-fuchsia-400', max_length=50)),
                ('endpoint_type', models.CharField(blank=True, default='', max_length=50)),
                ('operation', models.CharField(blank=True, default='', max_length=50)),
                ('target', models.CharField(blank=True, default='', max_length=50)),
                ('param_type', models.CharField(blank=True, default='', max_length=50)),
                ('accept_types', models.CharField(blank=True, default='', max_length=255)),
                ('is_multi_file', models.BooleanField(default=False)),
                ('handler_type', models.CharField(blank=True, default='', max_length=50)),
                ('custom_url', models.CharField(blank=True, default='', max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AlterField(
            model_name='languagerule',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
