from django.db import migrations

INITIAL_TOOLS = [
    {
        'slug': 'word2pdf',
        'name': 'Word → PDF',
        'category': 'Convert',
        'icon_class': 'fa-solid fa-file-word',
        'lucide_icon': 'FileType2',
        'color': '#3b82f6',
        'color_class': 'text-blue-400',
        'endpoint_type': 'convert',
        'operation': '',
        'target': 'pdf',
        'param_type': '',
        'accept_types': '.docx,.doc,.txt,.rtf,.md',
        'is_multi_file': False,
        'hint': 'DOCX, DOC, TXT, RTF, MD',
        'desc': 'Convert Microsoft Word and text documents into high-quality PDF files instantly.',
        'custom_url': '/tools/word-to-pdf',
        'order': 1,
    },
    {
        'slug': 'pdf2word',
        'name': 'PDF → Word',
        'category': 'Convert',
        'icon_class': 'fa-solid fa-file-word',
        'lucide_icon': 'FileType2',
        'color': '#3b82f6',
        'color_class': 'text-blue-400',
        'endpoint_type': 'convert',
        'operation': '',
        'target': 'docx',
        'param_type': '',
        'accept_types': '.pdf',
        'is_multi_file': False,
        'hint': 'PDF file',
        'desc': 'Turn any PDF file into an editable Microsoft Word document (.docx).',
        'custom_url': '/tools/pdf-to-word',
        'order': 2,
    },
    {
        'slug': 'img2pdf',
        'name': 'Image → PDF',
        'category': 'Convert',
        'icon_class': 'fa-solid fa-image',
        'lucide_icon': 'ImageIcon',
        'color': '#3b82f6',
        'color_class': 'text-blue-400',
        'endpoint_type': 'convert',
        'operation': '',
        'target': 'pdf',
        'param_type': '',
        'accept_types': '.png,.jpg,.jpeg,.webp',
        'is_multi_file': True,
        'hint': 'PNG, JPG, WEBP (one or many)',
        'desc': 'Convert one or multiple image files into a single structured PDF document.',
        'custom_url': '/tools/image-to-pdf',
        'order': 3,
    },
    {
        'slug': 'pdf2jpg',
        'name': 'PDF → JPG',
        'category': 'Convert',
        'icon_class': 'fa-solid fa-file-image',
        'lucide_icon': 'ImageIcon',
        'color': '#3b82f6',
        'color_class': 'text-blue-400',
        'endpoint_type': 'convert',
        'operation': '',
        'target': 'jpg',
        'param_type': '',
        'accept_types': '.pdf',
        'is_multi_file': False,
        'hint': 'PDF file',
        'desc': 'Extract PDF pages into clear, high-resolution JPEG image files.',
        'custom_url': '/tools/pdf-to-jpg',
        'order': 4,
    },
    {
        'slug': 'pdf2png',
        'name': 'PDF → PNG',
        'category': 'Convert',
        'icon_class': 'fa-solid fa-file-image',
        'lucide_icon': 'ImageIcon',
        'color': '#3b82f6',
        'color_class': 'text-blue-400',
        'endpoint_type': 'convert',
        'operation': '',
        'target': 'png',
        'param_type': '',
        'accept_types': '.pdf',
        'is_multi_file': False,
        'hint': 'PDF file',
        'desc': 'Extract PDF pages as lossless, transparent PNG graphic files.',
        'custom_url': '/tools/pdf-to-png',
        'order': 5,
    },
    {
        'slug': 'imgconvert',
        'name': 'Image Format Converter',
        'category': 'Convert',
        'icon_class': 'fa-solid fa-rotate',
        'lucide_icon': 'RefreshCw',
        'color': '#3b82f6',
        'color_class': 'text-blue-400',
        'endpoint_type': '',
        'operation': '',
        'target': '',
        'param_type': '',
        'accept_types': '.jfif,.webp,.svg,.bmp,.tiff,.tif,.gif,.ico,.avif,.heic,.heif,.png,.jpg,.jpeg',
        'is_multi_file': False,
        'handler_type': 'imgconverter',
        'hint': 'JFIF, WebP, SVG, BMP, TIFF, AVIF, GIF, ICO',
        'desc': 'Convert any image format — JFIF to PNG, WebP to PNG, SVG to PNG, and more.',
        'custom_url': '/tools/image-format-converter',
        'order': 6,
    },
    {
        'slug': 'ppt2pdf',
        'name': 'PowerPoint → PDF',
        'category': 'Office',
        'icon_class': 'fa-solid fa-file-powerpoint',
        'lucide_icon': 'Presentation',
        'color': '#f59e0b',
        'color_class': 'text-amber-400',
        'endpoint_type': 'convert',
        'operation': '',
        'target': 'pdf',
        'param_type': '',
        'accept_types': '.pptx,.ppt,.odp',
        'is_multi_file': False,
        'hint': 'PPTX, PPT, ODP',
        'desc': 'Convert PowerPoint presentations into clean, shareable PDF slides.',
        'order': 7,
    },
    {
        'slug': 'excel2pdf',
        'name': 'Excel → PDF',
        'category': 'Office',
        'icon_class': 'fa-solid fa-file-excel',
        'lucide_icon': 'FileSpreadsheet',
        'color': '#f59e0b',
        'color_class': 'text-amber-400',
        'endpoint_type': 'convert',
        'operation': '',
        'target': 'pdf',
        'param_type': '',
        'accept_types': '.xlsx,.xls,.ods,.csv',
        'is_multi_file': False,
        'hint': 'XLSX, XLS, ODS, CSV',
        'desc': 'Turn Excel spreadsheets and CSV tables into neatly formatted PDF documents.',
        'order': 8,
    },
    {
        'slug': 'office2pdf',
        'name': 'ODT / HTML / EPUB → PDF',
        'category': 'Office',
        'icon_class': 'fa-solid fa-file-lines',
        'lucide_icon': 'FileType2',
        'color': '#f59e0b',
        'color_class': 'text-amber-400',
        'endpoint_type': 'convert',
        'operation': '',
        'target': 'pdf',
        'param_type': '',
        'accept_types': '.odt,.html,.htm,.epub,.rtf',
        'is_multi_file': False,
        'hint': 'ODT, HTML, EPUB, RTF',
        'desc': 'Convert open formats, e-books, and web pages into readable PDF documents.',
        'order': 9,
    },
    {
        'slug': 'merge',
        'name': 'Merge PDF',
        'category': 'Organize',
        'icon_class': 'fa-solid fa-object-group',
        'lucide_icon': 'Combine',
        'color': '#8b5cf6',
        'color_class': 'text-purple-400',
        'endpoint_type': 'pdf',
        'operation': 'merge',
        'target': '',
        'param_type': '',
        'accept_types': '.pdf',
        'is_multi_file': True,
        'hint': 'Two or more PDFs',
        'desc': 'Combine multiple PDF files into one complete, perfectly ordered document.',
        'order': 10,
    },
    {
        'slug': 'split',
        'name': 'Split PDF',
        'category': 'Organize',
        'icon_class': 'fa-solid fa-scissors',
        'lucide_icon': 'Scissors',
        'color': '#8b5cf6',
        'color_class': 'text-purple-400',
        'endpoint_type': 'pdf',
        'operation': 'split',
        'target': '',
        'param_type': '',
        'accept_types': '.pdf',
        'is_multi_file': False,
        'hint': 'PDF file',
        'desc': 'Split a large PDF file into separate single-page PDF files.',
        'order': 11,
    },
    {
        'slug': 'extract',
        'name': 'Extract Pages',
        'category': 'Organize',
        'icon_class': 'fa-solid fa-file-export',
        'lucide_icon': 'FileOutput',
        'color': '#8b5cf6',
        'color_class': 'text-purple-400',
        'endpoint_type': 'pdf',
        'operation': 'extract',
        'target': '',
        'param_type': 'pages',
        'accept_types': '.pdf',
        'is_multi_file': False,
        'hint': 'PDF file',
        'desc': 'Extract specific page ranges (e.g. 1, 3-5) into an independent PDF.',
        'order': 12,
    },
    {
        'slug': 'compress',
        'name': 'Compress PDF',
        'category': 'Optimize',
        'icon_class': 'fa-solid fa-compress',
        'lucide_icon': 'Minimize2',
        'color': '#10b981',
        'color_class': 'text-emerald-400',
        'endpoint_type': '',
        'operation': '',
        'target': '',
        'param_type': '',
        'accept_types': '.pdf',
        'is_multi_file': False,
        'handler_type': 'compressor',
        'hint': 'PDF file',
        'desc': 'Reduce PDF file size without noticeable loss of visual quality.',
        'order': 13,
    },
    {
        'slug': 'video_compress',
        'name': 'Video Compressor',
        'category': 'Optimize',
        'icon_class': 'fa-solid fa-video',
        'lucide_icon': 'Video',
        'color': '#10b981',
        'color_class': 'text-emerald-400',
        'endpoint_type': '',
        'operation': '',
        'target': '',
        'param_type': '',
        'accept_types': '.mp4,.mov,.mkv,.webm',
        'is_multi_file': False,
        'handler_type': 'videocompressor',
        'hint': 'MP4, MOV, MKV, WebM',
        'desc': 'Compress videos efficiently with H.264 presets (WhatsApp, Instagram, YouTube HD).',
        'order': 14,
    },
    {
        'slug': 'watermark',
        'name': 'Watermark PDF',
        'category': 'Optimize',
        'icon_class': 'fa-solid fa-droplet',
        'lucide_icon': 'Droplets',
        'color': '#10b981',
        'color_class': 'text-emerald-400',
        'endpoint_type': 'pdf',
        'operation': 'watermark',
        'target': '',
        'param_type': 'text',
        'accept_types': '.pdf',
        'is_multi_file': False,
        'hint': 'PDF file',
        'desc': 'Add a custom text watermark — colour, opacity, size, rotation and position.',
        'order': 15,
    },
    {
        'slug': 'wmremove',
        'name': 'Remove Watermark',
        'category': 'Optimize',
        'icon_class': 'fa-solid fa-eraser',
        'lucide_icon': 'Eraser',
        'color': '#10b981',
        'color_class': 'text-emerald-400',
        'endpoint_type': '',
        'operation': '',
        'target': '',
        'param_type': '',
        'accept_types': '.pdf',
        'is_multi_file': False,
        'handler_type': 'wmeditor',
        'hint': 'PDF file',
        'desc': 'Open a visual editor: auto-scan for watermarks, box any watermark and erase it.',
        'order': 16,
    },
    {
        'slug': 'protect',
        'name': 'Protect PDF',
        'category': 'Security',
        'icon_class': 'fa-solid fa-lock',
        'lucide_icon': 'Lock',
        'color': '#ef4444',
        'color_class': 'text-rose-400',
        'endpoint_type': 'pdf',
        'operation': 'protect',
        'target': '',
        'param_type': 'password',
        'accept_types': '.pdf',
        'is_multi_file': False,
        'hint': 'PDF file',
        'desc': 'Encrypt and secure sensitive PDF documents with robust password protection.',
        'order': 17,
    },
    {
        'slug': 'unlock',
        'name': 'Unlock PDF',
        'category': 'Security',
        'icon_class': 'fa-solid fa-unlock',
        'lucide_icon': 'Unlock',
        'color': '#ef4444',
        'color_class': 'text-rose-400',
        'endpoint_type': 'pdf',
        'operation': 'unlock',
        'target': '',
        'param_type': 'password',
        'accept_types': '.pdf',
        'is_multi_file': False,
        'hint': 'Password-protected PDF',
        'desc': 'Remove security passwords and restrictions from your protected PDF files.',
        'order': 18,
    },
    {
        'slug': 'ocr',
        'name': 'OCR — Make Searchable',
        'category': 'OCR',
        'icon_class': 'fa-solid fa-magnifying-glass-plus',
        'lucide_icon': 'ScanText',
        'color': '#eab308',
        'color_class': 'text-yellow-400',
        'endpoint_type': 'pdf',
        'operation': 'ocr',
        'target': '',
        'param_type': '',
        'accept_types': '.pdf',
        'is_multi_file': False,
        'hint': 'Scanned PDF',
        'desc': 'Convert scanned image PDFs into searchable, selectable text (English, Assamese & Hindi).',
        'order': 19,
    },
    {
        'slug': 'chatpdf',
        'name': 'Chat with PDF',
        'category': 'AI Tools',
        'icon_class': 'fa-solid fa-comments',
        'lucide_icon': 'MessagesSquare',
        'color': '#ec4899',
        'color_class': 'text-fuchsia-400',
        'endpoint_type': 'ai',
        'operation': 'chat',
        'target': '',
        'param_type': 'question',
        'accept_types': '.pdf',
        'is_multi_file': False,
        'hint': 'PDF file',
        'desc': 'Ask questions and get instant, intelligent answers directly from your PDF document.',
        'is_featured': True,
        'order': 20,
    },
    {
        'slug': 'summarize',
        'name': 'Summarize',
        'category': 'AI Tools',
        'icon_class': 'fa-solid fa-wand-magic-sparkles',
        'lucide_icon': 'Sparkles',
        'color': '#ec4899',
        'color_class': 'text-fuchsia-400',
        'endpoint_type': '',
        'operation': '',
        'target': '',
        'param_type': '',
        'accept_types': '',
        'is_multi_file': False,
        'handler_type': 'summarizer',
        'hint': 'PDF · DOCX · TXT · pasted text',
        'desc': 'Summarise a document or pasted text — short, medium or detailed, in Assamese, English or Hindi.',
        'order': 21,
    },
    {
        'slug': 'translatepdf',
        'name': 'Translate PDF',
        'category': 'AI Tools',
        'icon_class': 'fa-solid fa-language',
        'lucide_icon': 'Languages',
        'color': '#ec4899',
        'color_class': 'text-fuchsia-400',
        'endpoint_type': 'ai',
        'operation': 'translate',
        'target': '',
        'param_type': 'lang',
        'accept_types': '.pdf',
        'is_multi_file': False,
        'hint': 'PDF file',
        'desc': 'Translate PDF text into Assamese, Hindi, English, and more with AI.',
        'order': 22,
    },
    {
        'slug': 'imagegen',
        'name': 'Generate Image',
        'category': 'AI Tools',
        'icon_class': 'fa-solid fa-palette',
        'lucide_icon': 'ImagePlus',
        'color': '#ec4899',
        'color_class': 'text-fuchsia-400',
        'endpoint_type': '',
        'operation': '',
        'target': '',
        'param_type': '',
        'accept_types': '',
        'is_multi_file': False,
        'handler_type': 'imagegen',
        'hint': 'Prompt → image',
        'desc': 'Turn a text prompt into a stunning AI image with Google Gemini.',
        'is_featured': True,
        'order': 23,
    },
    {
        'slug': 'imagefinder',
        'name': 'AI Image Finder',
        'category': 'AI Tools',
        'icon_class': 'fa-solid fa-images',
        'lucide_icon': 'Images',
        'color': '#ec4899',
        'color_class': 'text-fuchsia-400',
        'endpoint_type': '',
        'operation': '',
        'target': '',
        'param_type': '',
        'accept_types': '',
        'is_multi_file': False,
        'handler_type': 'imagefinder',
        'hint': 'Keywords → 4K Stock & AI Photos',
        'desc': 'Search, explore and download millions of free high-resolution 4K stock and creative photos powered by Pexels.',
        'order': 24,
    },
    {
        'slug': 'videofinder',
        'name': 'AI Video Finder',
        'category': 'AI Tools',
        'icon_class': 'fa-solid fa-film',
        'lucide_icon': 'Video',
        'color': '#ec4899',
        'color_class': 'text-fuchsia-400',
        'endpoint_type': '',
        'operation': '',
        'target': '',
        'param_type': '',
        'accept_types': '',
        'is_multi_file': False,
        'handler_type': 'videofinder',
        'hint': 'Keywords → 4K & HD Stock Videos',
        'desc': 'Search, preview and download free high-resolution 4K & HD stock footage and motion clips powered by Pexels.',
        'order': 25,
    },
    {
        'slug': 'diagramgen',
        'name': 'AI Diagram Generator',
        'category': 'AI Tools',
        'icon_class': 'fa-solid fa-diagram-project',
        'lucide_icon': 'Network',
        'color': '#ec4899',
        'color_class': 'text-fuchsia-400',
        'endpoint_type': '',
        'operation': '',
        'target': '',
        'param_type': '',
        'accept_types': '',
        'is_multi_file': False,
        'handler_type': 'diagramgen',
        'hint': 'Prompt → Flowchart, Sequence, Architecture',
        'desc': 'Generate flowcharts, sequence diagrams, cloud architectures & ER diagrams with Mermaid AI.',
        'order': 26,
    },
    {
        'slug': 'qrgen',
        'name': 'QR Code Generator',
        'category': 'Edit',
        'icon_class': 'fa-solid fa-qrcode',
        'lucide_icon': 'QrCode',
        'color': '#06b6d4',
        'color_class': 'text-cyan-400',
        'endpoint_type': '',
        'operation': '',
        'target': '',
        'param_type': '',
        'accept_types': '',
        'is_multi_file': False,
        'handler_type': 'qrgen',
        'hint': 'URL, Text, WiFi, UPI, vCard',
        'desc': 'Generate QR codes from URLs, text, WiFi, UPI payments, contacts, WhatsApp, email or phone.',
        'order': 27,
    },
    {
        'slug': 'screenshot2code',
        'name': 'Screenshot to Code',
        'category': 'AI Tools',
        'icon_class': 'fa-solid fa-code',
        'lucide_icon': 'Code',
        'color': '#ec4899',
        'color_class': 'text-fuchsia-400',
        'endpoint_type': '',
        'operation': '',
        'target': '',
        'param_type': '',
        'accept_types': '',
        'is_multi_file': False,
        'handler_type': 'screenshot2code',
        'hint': 'Image → HTML/CSS code',
        'desc': 'Upload a screenshot or UI design and let Gemini AI generate pixel-perfect HTML/CSS code.',
        'order': 28,
    },
    {
        'slug': 'memegen',
        'name': 'Meme Generator',
        'category': 'Edit',
        'icon_class': 'fa-solid fa-face-laugh-squint',
        'lucide_icon': 'Laugh',
        'color': '#06b6d4',
        'color_class': 'text-cyan-400',
        'endpoint_type': '',
        'operation': '',
        'target': '',
        'param_type': '',
        'accept_types': '',
        'is_multi_file': False,
        'handler_type': 'memegen',
        'hint': 'Templates, text, fonts, download',
        'desc': 'Create hilarious memes — pick a template or upload your own image, add top/bottom text, and download.',
        'order': 29,
    },
    {
        'slug': 'bgremover',
        'name': 'Background Remover',
        'category': 'AI Tools',
        'icon_class': 'fa-solid fa-scissors',
        'lucide_icon': 'Scissors',
        'color': '#ec4899',
        'color_class': 'text-fuchsia-400',
        'endpoint_type': '',
        'operation': '',
        'target': '',
        'param_type': '',
        'accept_types': '',
        'is_multi_file': False,
        'handler_type': 'bgremover',
        'hint': 'Image → transparent PNG',
        'desc': 'Remove image backgrounds instantly with AI — download transparent PNG or replace with any solid color.',
        'order': 30,
    },
    {
        'slug': 'palettegen',
        'name': 'Color Palette Generator',
        'category': 'Edit',
        'icon_class': 'fa-solid fa-swatchbook',
        'lucide_icon': 'Palette',
        'color': '#06b6d4',
        'color_class': 'text-cyan-400',
        'endpoint_type': '',
        'operation': '',
        'target': '',
        'param_type': '',
        'accept_types': '',
        'is_multi_file': False,
        'handler_type': 'palettegen',
        'hint': 'Random, image extract, harmony',
        'desc': 'Generate beautiful color palettes — random, analogous, complementary, triadic — or extract dominant colors from any image.',
        'order': 31,
    },
    {
        'slug': 'svgeditor',
        'name': 'SVG Editor',
        'category': 'Edit',
        'icon_class': 'fa-solid fa-pen-nib',
        'lucide_icon': 'PenTool',
        'color': '#06b6d4',
        'color_class': 'text-cyan-400',
        'endpoint_type': '',
        'operation': '',
        'target': '',
        'param_type': '',
        'accept_types': '',
        'is_multi_file': False,
        'handler_type': 'svgeditor',
        'hint': 'Draw, edit & export SVG',
        'desc': 'Create and edit vector graphics — shapes, text, freehand drawing with layers, zoom, grid and SVG/PNG/JPG export.',
        'order': 32,
    },
    {
        'slug': 'edit',
        'name': 'Edit PDF',
        'category': 'Edit',
        'icon_class': 'fa-solid fa-pen-to-square',
        'lucide_icon': 'PenTool',
        'color': '#06b6d4',
        'color_class': 'text-cyan-400',
        'endpoint_type': '',
        'operation': '',
        'target': '',
        'param_type': '',
        'accept_types': '.pdf',
        'is_multi_file': False,
        'handler_type': 'editor',
        'hint': 'PDF file',
        'desc': 'Annotate, draw, insert shapes, highlight and edit pages in a full interactive canvas.',
        'order': 33,
    },
    {
        'slug': 'sign',
        'name': 'Sign PDF',
        'category': 'Edit',
        'icon_class': 'fa-solid fa-signature',
        'lucide_icon': 'Signature',
        'color': '#06b6d4',
        'color_class': 'text-cyan-400',
        'endpoint_type': '',
        'operation': '',
        'target': '',
        'param_type': '',
        'accept_types': '.pdf',
        'is_multi_file': False,
        'handler_type': 'editor',
        'hint': 'PDF file',
        'desc': 'Draw or insert your electronic signature and place it anywhere on your PDF.',
        'order': 34,
    },
]

def seed_tools(apps, schema_editor):
    AITool = apps.get_model('superadmin', 'AITool')
    for item in INITIAL_TOOLS:
        AITool.objects.update_or_create(
            slug=item['slug'],
            defaults={
                'name': item['name'],
                'category': item['category'],
                'icon_class': item.get('icon_class', 'fa-solid fa-sparkles'),
                'lucide_icon': item.get('lucide_icon', 'Sparkles'),
                'color': item.get('color', '#ec4899'),
                'color_class': item.get('color_class', 'text-fuchsia-400'),
                'endpoint_type': item.get('endpoint_type', ''),
                'operation': item.get('operation', ''),
                'target': item.get('target', ''),
                'param_type': item.get('param_type', ''),
                'accept_types': item.get('accept_types', ''),
                'is_multi_file': item.get('is_multi_file', False),
                'handler_type': item.get('handler_type', ''),
                'hint': item.get('hint', ''),
                'description': item.get('desc', ''),
                'custom_url': item.get('custom_url', ''),
                'order': item.get('order', 0),
                'is_active': True,
                'is_featured': item.get('is_featured', False),
            }
        )

def unseed_tools(apps, schema_editor):
    AITool = apps.get_model('superadmin', 'AITool')
    slugs = [t['slug'] for t in INITIAL_TOOLS]
    AITool.objects.filter(slug__in=slugs).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0006_aitool_alter_languagerule_id'),
    ]

    operations = [
        migrations.RunPython(seed_tools, unseed_tools),
    ]
