# Generated by Django 5.2.17 on 2026-09-27 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0009_seed_canva_tool'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCustomQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_per_day', models.IntegerField(default=-1, help_text='-1 to use plan default, -2 for unlimited, or specific number')),
                ('images_per_day', models.IntegerField(default=-1, help_text='-1 to use plan default, -2 for unlimited, or specific number')),
                ('searches_per_day', models.IntegerField(default=-1, help_text='-1 to use plan default, -2 for unlimited, or specific number')),
                ('pdf_per_day', models.IntegerField(default=-1, help_text='-1 to use plan default, -2 for unlimited, or specific number')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custom_quota', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(db_index=True, max_length=32)),
                ('color', models.CharField(default='indigo', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'tag_name')},
            },
        ),
    ]
