# Generated by Django 5.2.17 on 2026-10-09 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0013_add_image_compressor_tool'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperAdminLoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(db_index=True, max_length=64)),
                ('username', models.CharField(blank=True, db_index=True, max_length=150)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('last_failed_at', models.DateTimeField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Super Admin Login Security Record',
                'verbose_name_plural': 'Super Admin Login Security Records',
                'indexes': [models.Index(fields=['ip_address', 'is_locked'], name='superadmin__ip_addr_05046b_idx'), models.Index(fields=['username', 'is_locked'], name='superadmin__usernam_6fc1ee_idx')],
            },
        ),
    ]
