import json
from .models import (
    ConverterToolConfig,
    ConverterToolFAQ,
    WordToPdfToolConfig,
    WordToPdfFAQ,
    DEFAULT_COMPARISON_ROWS,
)

# ── ALL 31 AXOM AI TOOLS METADATA (Grouped by Category) ──
CONVERTER_TOOLS_METADATA = {
    # ── 1. Document & PDF Tools ──
    'word-to-pdf': {
        'name': 'Word to PDF',
        'cat': 'Document & PDF',
        'icon': 'fa-solid fa-file-pdf text-red-400',
        'subtitle': 'DOCX/DOC → PDF',
        'badge': 'Hero, How-To, Specs & FAQs',
        'target_url': 'https://aiaxom.co.in/tools/word-to-pdf',
        'inputs': '.docx, .doc, .rtf, .txt, .odt',
        'output': 'PDF 1.7 / ISO 32000-1 (Vector)',
    },
    'pdf-to-word': {
        'name': 'PDF to Word',
        'cat': 'Document & PDF',
        'icon': 'fa-solid fa-file-word text-blue-400',
        'subtitle': 'PDF → Editable DOCX',
        'badge': 'Hero, How-To, Specs & FAQs',
        'target_url': 'https://aiaxom.co.in/tools/pdf-to-word',
        'inputs': '.pdf (PDF 1.0 - 2.0)',
        'output': 'Microsoft Word (.docx)',
    },
    'image-to-pdf': {
        'name': 'Image to PDF',
        'cat': 'Document & PDF',
        'icon': 'fa-solid fa-file-image text-emerald-400',
        'subtitle': 'JPG/PNG/WebP → PDF',
        'badge': 'Hero, How-To, Specs & FAQs',
        'target_url': 'https://aiaxom.co.in/tools/image-to-pdf',
        'inputs': 'JPG, PNG, WebP, GIF, BMP, AVIF',
        'output': 'PDF 1.7 (Vector/Raster)',
    },
    'pdf-to-jpg': {
        'name': 'PDF to JPG',
        'cat': 'Document & PDF',
        'icon': 'fa-solid fa-image text-amber-400',
        'subtitle': 'PDF → High-Res JPG',
        'badge': 'Hero, How-To, Specs & FAQs',
        'target_url': 'https://aiaxom.co.in/tools/pdf-to-jpg',
        'inputs': '.pdf',
        'output': 'JPEG (300 DPI High-Res)',
    },
    'pdf-to-png': {
        'name': 'PDF to PNG',
        'cat': 'Document & PDF',
        'icon': 'fa-solid fa-images text-cyan-400',
        'subtitle': 'PDF → Lossless PNG',
        'badge': 'Hero, How-To, Specs & FAQs',
        'target_url': 'https://aiaxom.co.in/tools/pdf-to-png',
        'inputs': '.pdf',
        'output': 'PNG (Lossless 24-bit/32-bit)',
    },
    'ppt-to-pdf': {
        'name': 'PowerPoint to PDF',
        'cat': 'Document & PDF',
        'icon': 'fa-solid fa-file-powerpoint text-orange-400',
        'subtitle': 'PPTX/PPT → PDF',
        'badge': 'Hero, How-To, Specs & FAQs',
        'target_url': 'https://aiaxom.co.in/tools/ppt-to-pdf',
        'inputs': '.pptx, .ppt, .odp',
        'output': 'PDF 1.7 Presentation Vector',
    },
    'excel-to-pdf': {
        'name': 'Excel to PDF',
        'cat': 'Document & PDF',
        'icon': 'fa-solid fa-file-excel text-emerald-500',
        'subtitle': 'XLSX/XLS → PDF',
        'badge': 'Hero, How-To, Specs & FAQs',
        'target_url': 'https://aiaxom.co.in/tools/excel-to-pdf',
        'inputs': '.xlsx, .xls, .csv, .ods',
        'output': 'PDF 1.7 Table Grid',
    },
    'compress-pdf': {
        'name': 'Compress PDF',
        'cat': 'Document & PDF',
        'icon': 'fa-solid fa-file-zipper text-teal-400',
        'subtitle': 'Reduce PDF file size',
        'badge': 'Hero, How-To, Specs & FAQs',
        'target_url': 'https://aiaxom.co.in/tools/compress-pdf',
        'inputs': '.pdf',
        'output': 'Compressed PDF (Optimized Streams)',
    },
    'merge-pdf': {
        'name': 'Merge PDF',
        'cat': 'Document & PDF',
        'icon': 'fa-solid fa-object-group text-indigo-400',
        'subtitle': 'Combine multiple PDFs',
        'badge': 'Hero, How-To, Specs & FAQs',
        'target_url': 'https://aiaxom.co.in/tools/merge-pdf',
        'inputs': '.pdf (Multiple)',
        'output': 'Single Merged PDF',
    },
    'split-pdf': {
        'name': 'Split PDF',
        'cat': 'Document & PDF',
        'icon': 'fa-solid fa-scissors text-pink-400',
        'subtitle': 'Separate pages from PDF',
        'badge': 'Hero, How-To, Specs & FAQs',
        'target_url': 'https://aiaxom.co.in/tools/split-pdf',
        'inputs': '.pdf',
        'output': 'Individual Page PDFs / ZIP',
    },
    'protect-pdf': {
        'name': 'Protect PDF',
        'cat': 'Document & PDF',
        'icon': 'fa-solid fa-lock text-rose-400',
        'subtitle': 'Encrypt & password protect',
        'badge': 'Hero, How-To, Specs & FAQs',
        'target_url': 'https://aiaxom.co.in/tools/protect-pdf',
        'inputs': '.pdf',
        'output': 'AES-256 Encrypted PDF',
    },
    'watermark-pdf': {
        'name': 'Watermark PDF',
        'cat': 'Document & PDF',
        'icon': 'fa-solid fa-stamp text-sky-400',
        'subtitle': 'Add text/image watermark',
        'badge': 'Hero, How-To, Specs & FAQs',
        'target_url': 'https://aiaxom.co.in/tools/watermark-pdf',
        'inputs': '.pdf, text/stamp image',
        'output': 'Watermarked PDF',
    },
    'edit-pdf': {
        'name': 'Edit PDF',
        'cat': 'Document & PDF',
        'icon': 'fa-solid fa-pen-to-square text-violet-400',
        'subtitle': 'Annotate, draw & edit',
        'badge': 'Hero, How-To, Specs & FAQs',
        'target_url': 'https://aiaxom.co.in/tools/edit-pdf',
        'inputs': '.pdf',
        'output': 'Annotated & Modified PDF',
    },
    'sign-pdf': {
        'name': 'Sign PDF',
        'cat': 'Document & PDF',
        'icon': 'fa-solid fa-signature text-amber-500',
        'subtitle': 'Electronic signatures',
        'badge': 'Hero, How-To, Specs & FAQs',
        'target_url': 'https://aiaxom.co.in/tools/sign-pdf',
        'inputs': '.pdf, signature drawing/image',
        'output': 'Digitally Signed PDF',
    },
    'chat-with-pdf': {
        'name': 'Chat with PDF',
        'cat': 'Document & PDF',
        'icon': 'fa-solid fa-comments text-blue-500',
        'subtitle': 'AI-powered PDF Q&A',
        'badge': 'Hero, How-To, Specs & FAQs',
        'target_url': 'https://aiaxom.co.in/tools/chat-with-pdf',
        'inputs': '.pdf, .txt, .docx',
        'output': 'Interactive AI Semantic Answers',
    },

    # ── 2. Image & Media Tools ──
    'image-compressor': {
        'name': 'Image Compressor',
        'cat': 'Image & Media',
        'icon': 'fa-solid fa-minimize text-emerald-400',
        'subtitle': 'Reduce JPG, PNG, WebP size',
        'badge': 'Hero, How-To, Specs & FAQs',
        'target_url': 'https://aiaxom.co.in/tools/image-compressor',
        'inputs': 'JPG, PNG, WebP, GIF, BMP, AVIF',
        'output': 'Compressed JPG, WebP, PNG',
    },
    'image-format-converter': {
        'name': 'Image Format Converter',
        'cat': 'Image & Media',
        'icon': 'fa-solid fa-arrows-rotate text-purple-400',
        'subtitle': 'WebP, JFIF, SVG, PNG',
        'badge': 'Hero, How-To, Specs & FAQs',
        'target_url': 'https://aiaxom.co.in/tools/image-format-converter',
        'inputs': 'JFIF, WebP, SVG, BMP, TIFF, AVIF, HEIC, PNG, JPG',
        'output': 'PNG, JPG, WebP, SVG, BMP',
    },
    'background-remover': {
        'name': 'Background Remover',
        'cat': 'Image & Media',
        'icon': 'fa-solid fa-wand-magic-sparkles text-fuchsia-400',
        'subtitle': '1-Click AI BG removal',
        'badge': 'Hero, How-To, Specs & FAQs',
        'target_url': 'https://aiaxom.co.in/tools/background-remover',
        'inputs': 'JPG, PNG, WebP, BMP',
        'output': 'Transparent PNG / WebP',
    },
    'svg-editor': {
        'name': 'SVG Editor',
        'cat': 'Image & Media',
        'icon': 'fa-solid fa-bezier-curve text-purple-400',
        'subtitle': 'Vector graphic editor',
        'badge': 'Hero, How-To, Specs & FAQs',
        'target_url': 'https://aiaxom.co.in/tools/svg-editor',
        'inputs': 'SVG, Vector Paths',
        'output': 'SVG (Clean XML), PNG Export',
    },
    'color-palette-generator': {
        'name': 'Color Palette Generator',
        'cat': 'Image & Media',
        'icon': 'fa-solid fa-palette text-amber-400',
        'subtitle': 'Harmonious palettes',
        'badge': 'Hero, How-To, Specs & FAQs',
        'target_url': 'https://aiaxom.co.in/tools/color-palette-generator',
        'inputs': 'Hex, RGB, HSL, Image Upload',
        'output': 'Palette CSS, Hex Codes, JSON',
    },
    'meme-generator': {
        'name': 'Meme Generator',
        'cat': 'Image & Media',
        'icon': 'fa-solid fa-face-laugh-squint text-yellow-500',
        'subtitle': 'Create viral memes',
        'badge': 'Hero, How-To, Specs & FAQs',
        'target_url': 'https://aiaxom.co.in/tools/meme-generator',
        'inputs': 'Custom Image or Templates',
        'output': 'High-Res JPEG/PNG Meme',
    },
    'screenshot-to-code': {
        'name': 'Screenshot to Code',
        'cat': 'Image & Media',
        'icon': 'fa-solid fa-code text-blue-400',
        'subtitle': 'UI Image to HTML/React',
        'badge': 'Hero, How-To, Specs & FAQs',
        'target_url': 'https://aiaxom.co.in/tools/screenshot-to-code',
        'inputs': 'PNG, JPG UI Screenshots',
        'output': 'HTML / Tailwind CSS / React Code',
    },
    'qr-code-generator': {
        'name': 'QR Code Generator',
        'cat': 'Image & Media',
        'icon': 'fa-solid fa-qrcode text-emerald-400',
        'subtitle': 'Custom QR codes',
        'badge': 'Hero, How-To, Specs & FAQs',
        'target_url': 'https://aiaxom.co.in/tools/qr-code-generator',
        'inputs': 'URL, Text, WiFi, UPI, VCard',
        'output': 'PNG, SVG Vector QR Code',
    },

    # ── 3. AI & Video Tools ──
    'ai-notes-generator': {
        'name': 'AI Notes Generator',
        'cat': 'AI & Video',
        'icon': 'fa-solid fa-book-open-reader text-yellow-400',
        'subtitle': 'Auto-generate study notes',
        'badge': 'Hero, How-To, Specs & FAQs',
        'target_url': 'https://aiaxom.co.in/tools/ai-notes-generator',
        'inputs': 'PDF, DOCX, TXT, Scans',
        'output': 'Structured Notes, Flashcards, Mindmaps',
    },
    'ai-image-generator': {
        'name': 'AI Image Generator',
        'cat': 'AI & Video',
        'icon': 'fa-solid fa-paintbrush text-pink-500',
        'subtitle': 'Text to AI images',
        'badge': 'Hero, How-To, Specs & FAQs',
        'target_url': 'https://aiaxom.co.in/tools/ai-image-generator',
        'inputs': 'Text Prompt & Art Style',
        'output': 'Ultra-HD AI Generated Images',
    },
    'ai-image-finder': {
        'name': 'AI Image Finder',
        'cat': 'AI & Video',
        'icon': 'fa-solid fa-magnifying-glass text-indigo-400',
        'subtitle': 'Search 4K stock images',
        'badge': 'Hero, How-To, Specs & FAQs',
        'target_url': 'https://aiaxom.co.in/tools/ai-image-finder',
        'inputs': 'Search query, Category, Orientation',
        'output': 'Commercial-Free High-Res Images',
    },
    'ai-video-finder': {
        'name': 'AI Video Finder',
        'cat': 'AI & Video',
        'icon': 'fa-solid fa-video text-teal-400',
        'subtitle': 'Search HD video stock',
        'badge': 'Hero, How-To, Specs & FAQs',
        'target_url': 'https://aiaxom.co.in/tools/ai-video-finder',
        'inputs': 'Search keywords, Aspect ratio',
        'output': 'HD/4K Stock Video Clips',
    },
    'ai-diagram-generator': {
        'name': 'AI Diagram Generator',
        'cat': 'AI & Video',
        'icon': 'fa-solid fa-diagram-project text-cyan-400',
        'subtitle': 'Mermaid & flowcharts',
        'badge': 'Hero, How-To, Specs & FAQs',
        'target_url': 'https://aiaxom.co.in/tools/ai-diagram-generator',
        'inputs': 'Process prompt / System architecture',
        'output': 'Mermaid Diagram, SVG, PNG',
    },
    'video-compressor': {
        'name': 'Video Compressor',
        'cat': 'AI & Video',
        'icon': 'fa-solid fa-film text-red-500',
        'subtitle': 'Compress MP4/MOV',
        'badge': 'Hero, How-To, Specs & FAQs',
        'target_url': 'https://aiaxom.co.in/tools/video-compressor',
        'inputs': 'MP4, MOV, MKV, WebM, AVI',
        'output': 'Compressed MP4 (H.264/AAC)',
    },
    'video-downloader': {
        'name': 'Video Downloader',
        'cat': 'AI & Video',
        'icon': 'fa-solid fa-download text-green-400',
        'subtitle': 'Download web videos',
        'badge': 'Hero, How-To, Specs & FAQs',
        'target_url': 'https://aiaxom.co.in/tools/video-downloader',
        'inputs': 'Direct Video URL / Web link',
        'output': 'MP4 Video, High Bitrate Audio',
    },
    'youtube-video-downloader': {
        'name': 'YouTube Downloader',
        'cat': 'AI & Video',
        'icon': 'fa-brands fa-youtube text-red-600',
        'subtitle': 'Download YT MP4/Audio',
        'badge': 'Hero, How-To, Specs & FAQs',
        'target_url': 'https://aiaxom.co.in/tools/youtube-video-downloader',
        'inputs': 'YouTube Video / Shorts Link',
        'output': '1080p/720p MP4, MP3 Audio',
    },
}


def generate_tool_defaults(tool_slug):
    """Dynamically generates comprehensive defaults for any tool slug."""
    meta = CONVERTER_TOOLS_METADATA.get(tool_slug, {})
    name = meta.get('name', tool_slug.replace('-', ' ').title())
    inputs = meta.get('inputs', 'Standard files (.pdf, .jpg, .png, .docx)')
    output = meta.get('output', 'Standard output format')

    return {
        'tool_name': name,
        'hero_badge_text': f'⚡ Free Online Tool • 🛡️ 100% Secure & Private • Powered by Axom AI',
        'hero_heading_prefix': 'Free',
        'hero_heading_highlight': name,
        'hero_heading_suffix': 'Online Tool',
        'hero_description': f'Use {name} online for free. Experience ultra-fast, high-precision processing with complete data privacy and zero watermarks.',
        'free_daily_limit': 20,
        'pro_batch_limit': 20,
        'max_file_size_mb': 50,
        'how_it_works_title': f'How to Use {name} in 3 Easy Steps',
        'how_it_works_subheading': 'No complex software installation or account creation required. Fast and frictionless.',
        'step_1_title': 'Select Files or Input',
        'step_1_desc': f'Upload your file or provide input to begin with {name}.',
        'step_2_title': 'Instant Processing',
        'step_2_desc': 'Our optimized cloud & browser engine processes your request in seconds.',
        'step_3_title': 'Download Result',
        'step_3_desc': 'Save your clean, high-quality result directly to your local device.',
        'why_title': f'Why Axom AI {name} is the Superior Choice',
        'why_subheading': 'Engineered for students, educators, creators, and businesses who demand accuracy and privacy.',
        'benefit_1_title': 'High Precision & Quality',
        'benefit_1_desc': 'State-of-the-art algorithms ensure maximum fidelity and optimal results every single time.',
        'benefit_2_title': '100% Privacy & Data Security',
        'benefit_2_desc': 'Files and data are processed with SSL encryption and never stored without your permission.',
        'benefit_3_title': 'Fast & Lightweight',
        'benefit_3_desc': 'Optimized for lightning speed with minimal data consumption on mobile and desktop.',
        'benefit_4_title': 'Universal Device Support',
        'benefit_4_desc': 'Works smoothly across Android, iOS, Windows, Mac, and Linux web browsers.',
        'benefit_5_title': 'Zero Watermarks, 100% Free',
        'benefit_5_desc': 'Enjoy unrestricted output without obstructive watermarks or hidden payment traps.',
        'benefit_6_title': 'Made for Assam & India',
        'benefit_6_desc': 'Optimized for Indian users with support for regional workflows and formats.',
        'comparison_badge': 'Direct Feature Comparison',
        'comparison_title': f'Axom AI vs. Traditional {name} Tools',
        'comparison_subheading': 'See why users choose Axom AI over paywalled and ad-heavy alternatives.',
        'comparison_matrix_json': DEFAULT_COMPARISON_ROWS,
        'tech_spec_title': 'Technical Specifications & Supported Standards',
        'tech_spec_inputs': inputs,
        'tech_spec_output': output,
        'tech_spec_max_size': '50 Megabytes (MB)',
        'tech_spec_security': 'TLS 1.3 / SSL 256-bit',
        'faq_section_title': 'Frequently Asked Questions',
        'faq_section_subheading': f'Got questions about {name}? Find verified answers below.',
        'cta_title': f'Get Started with {name} Today',
        'cta_desc': 'Experience fast, private, and watermark-free tools trusted across India.',
        'cta_btn_primary_text': f'Use {name} Now',
        'cta_btn_primary_url': f'https://aiaxom.co.in/tools/{tool_slug}',
        'cta_btn_secondary_text': 'Explore All AI & Document Tools',
        'cta_btn_secondary_url': 'https://aiaxom.co.in/tools',
        'meta_title': f'Free {name} Online — Fast & Secure | Axom AI',
        'meta_description': f'Use {name} online for free. Fast, high-quality, and secure processing without watermarks. Powered by Axom AI.',
        'meta_keywords': f'{name}, free {name} online, axom ai tools, online tools assam india',
        'canonical_url': f'https://aiaxom.co.in/tools/{tool_slug}',
        'og_image_url': 'https://aiaxom.co.in/static/dist/hero/assam.avif',
    }


def generate_tool_faqs(tool_slug):
    """Dynamically generates 6 structured FAQs for any tool slug."""
    meta = CONVERTER_TOOLS_METADATA.get(tool_slug, {})
    name = meta.get('name', tool_slug.replace('-', ' ').title())
    return [
        (f'Is {name} free to use on Axom AI?', f'Yes! Axom AI provides free access to {name} with generous daily allowances, zero watermarks, and full feature access.', 1),
        (f'Are my files and data safe when using {name}?', f'Absolutely. All transfers are encrypted with 256-bit SSL encryption. We adhere to strict data privacy policies and files are purged automatically after processing.', 2),
        (f'Can I use {name} on my mobile phone?', f'Yes. {name} is 100% responsive and works seamlessly on Safari (iOS), Chrome (Android), Firefox, and any modern mobile browser without installing extra apps.', 3),
        (f'Does Axom AI add any watermark to the output?', f'No. Axom AI never places promotional watermarks, stamps, or logos on your generated files. All outputs are 100% clean and ready for professional use.', 4),
        (f'How fast is the processing with {name}?', f'Most tasks complete in 2 to 5 seconds thanks to our high-performance cloud micro-services and client-side optimization.', 5),
        (f'Is Axom AI optimized for users in Assam and India?', f'Yes! Axom AI is designed right here in Assam for creators, students, businesses, and developers across India who require fast, sovereign AI and utility tools.', 6),
    ]


CONVERTER_TOOLS_DEFAULTS = {
    'word-to-pdf': {
        'tool_name': 'Word to PDF',
        'hero_badge_text': '⚡ Free: 20 Files / Day • 👑 Pro: Batch Convert 20 Files at Once',
        'hero_heading_prefix': 'Free',
        'hero_heading_highlight': 'Word to PDF',
        'hero_heading_suffix': 'Converter Online',
        'hero_description': 'Convert your Microsoft Word (.DOCX, .DOC), Rich Text, and text files into professional, print-ready PDF documents instantly. Free accounts can convert up to 20 files per day. Upgrade to Premium for unlimited daily conversions and Pro Batch Mode to convert up to 20 files simultaneously in 1 click!',
        'free_daily_limit': 20,
        'pro_batch_limit': 20,
        'max_file_size_mb': 25,
        'how_it_works_title': 'How to Convert Word to PDF in 3 Easy Steps',
        'how_it_works_subheading': 'No complex software installation or account creation required. Fast and frictionless.',
        'step_1_title': 'Upload Document',
        'step_1_desc': 'Drag and drop your DOCX or DOC file into the converter box above or choose it from your local storage.',
        'step_2_title': 'Instant Processing',
        'step_2_desc': 'Click Convert. Our high-fidelity document engine parses structures, styles, margins, and media in seconds.',
        'step_3_title': 'Download PDF',
        'step_3_desc': 'Download your clean, publication-ready PDF document directly to your device. No watermarks, ever.',
        'why_title': 'Why Axom AI Word to PDF is the Superior Choice',
        'why_subheading': 'Engineered for students, educators, legal professionals, and businesses who demand accuracy and privacy.',
        'benefit_1_title': 'Lossless Layout Fidelity',
        'benefit_1_desc': 'Headers, footers, footnotes, complex tables, embedded charts, and custom fonts stay strictly aligned without shifting pages.',
        'benefit_2_title': 'Zero Watermarks, 100% Free',
        'benefit_2_desc': 'No hidden subscription traps or promotional watermarks stamped across your pages. Clean documents ready for official submissions.',
        'benefit_3_title': 'Automatic File Purging',
        'benefit_3_desc': 'Documents are processed securely via SSL encryption and purged automatically from our server memory right after conversion.',
        'benefit_4_title': 'Universal Device Support',
        'benefit_4_desc': 'Works seamlessly on iOS, Android, macOS, Windows, and Linux. No apps or browser extensions needed.',
        'benefit_5_title': 'Sub-3-Second Speed',
        'benefit_5_desc': 'High-speed optimized micro-services convert standard documents in less than 3 seconds with minimal bandwidth usage.',
        'benefit_6_title': 'Multi-Format Compatibility',
        'benefit_6_desc': 'Handles DOCX, DOC, RTF, TXT, and ODT with automatic format detection and smart structure extraction.',
        'comparison_badge': 'Direct Feature Comparison',
        'comparison_title': 'Axom AI vs. Traditional Word to PDF Converters',
        'comparison_subheading': 'See why users choose Axom AI over paywalled and ad-heavy alternatives.',
        'comparison_matrix_json': DEFAULT_COMPARISON_ROWS,
        'tech_spec_title': 'Technical Specifications & Supported Standards',
        'tech_spec_inputs': '.docx, .doc, .rtf, .txt, .odt',
        'tech_spec_output': 'PDF 1.7 / ISO 32000-1 (Vector)',
        'tech_spec_max_size': '25 Megabytes (MB)',
        'tech_spec_security': 'TLS 1.3 / SSL 256-bit',
        'faq_section_title': 'Frequently Asked Questions',
        'faq_section_subheading': 'Got questions about Word to PDF conversion? Find verified answers below.',
        'cta_title': 'Convert Your Word Documents in Seconds',
        'cta_desc': 'Experience fast, private, and watermark-free conversions trusted by users across Assam and India.',
        'cta_btn_primary_text': 'Upload Word File Now',
        'cta_btn_primary_url': '#converter',
        'cta_btn_secondary_text': 'Explore All AI & Document Tools',
        'cta_btn_secondary_url': 'https://aiaxom.co.in/tools',
        'meta_title': 'Free Word to PDF Converter Online — Convert DOCX to PDF | Axom AI',
        'meta_description': 'Convert Microsoft Word (.docx, .doc) to PDF online for free in seconds. Preserve original formatting, tables, fonts, and images. 100% secure with automatic file deletion.',
        'meta_keywords': 'Word to PDF, Word to PDF converter, convert word to pdf online free, docx to pdf converter, doc to pdf, convert word document to pdf, best free word to pdf converter, word to pdf without watermark, axom ai tools, assam ai document converter, free docx to pdf high quality, Word to PDF converter India, PDF tools Assam',
        'canonical_url': 'https://aiaxom.co.in/tools/word-to-pdf',
        'og_image_url': 'https://aiaxom.co.in/static/dist/hero/assam.avif',
    },
    'pdf-to-word': {
        'tool_name': 'PDF to Word',
        'hero_badge_text': '⚡ Free: 20 Files / Day • 🛡️ No Watermark • 👑 Pro Batch Mode',
        'hero_heading_prefix': 'Free',
        'hero_heading_highlight': 'PDF to Word',
        'hero_heading_suffix': 'Converter Online',
        'hero_description': 'Turn any PDF file into an editable Microsoft Word document (.docx) with unmatched layout and table precision. Free users can convert up to 20 files daily with zero watermarks. Upgrade to Axom AI Pro for unlimited conversions and instant 20-file batch processing.',
        'free_daily_limit': 20,
        'pro_batch_limit': 20,
        'max_file_size_mb': 25,
        'how_it_works_title': 'How to Convert PDF to Word in 3 Easy Steps',
        'how_it_works_subheading': 'Effortlessly transform static PDF documents into fully editable Word documents in seconds.',
        'step_1_title': 'Upload Your PDF',
        'step_1_desc': 'Drag and drop your PDF document into the converter box above or choose it from your local computer or phone storage.',
        'step_2_title': 'Instant Structural Analysis',
        'step_2_desc': 'Click Convert to Word. Our deep layout engine recognizes headings, tables, columns, and graphics in seconds.',
        'step_3_title': 'Download Editable DOCX',
        'step_3_desc': 'Download your publication-grade, fully editable Microsoft Word document directly to your device without watermarks.',
        'why_title': 'Why Axom AI PDF to Word is the Superior Choice',
        'why_subheading': 'Engineered for students, legal teams, educators, and enterprise users who demand layout fidelity and data confidentiality.',
        'benefit_1_title': 'Native Editable Tables',
        'benefit_1_desc': 'Complex tables, budgets, and invoices are reconstructed as native Word table grids, not broken floating text boxes.',
        'benefit_2_title': 'Zero Watermarks, 100% Free',
        'benefit_2_desc': 'No advertising banners, hidden subscription traps, or promotional watermarks stamped across your pages.',
        'benefit_3_title': 'Automatic File Purging',
        'benefit_3_desc': 'Documents are processed securely via 256-bit SSL encryption and permanently deleted from server memory right after conversion.',
        'benefit_4_title': 'Universal Device Support',
        'benefit_4_desc': 'Works seamlessly on Android, iPhone, Windows, macOS, Linux, and ChromeOS without installing extra software.',
        'benefit_5_title': 'Sub-3-Second Speed',
        'benefit_5_desc': 'High-performance cloud document micro-services convert standard PDF files in less than 3 seconds.',
        'benefit_6_title': 'Font & Layout Preservation',
        'benefit_6_desc': 'Retains font styles, margins, bulleted lists, indentations, and embedded graphics faithfully.',
        'comparison_badge': 'Direct Feature Comparison',
        'comparison_title': 'Axom AI vs. Traditional PDF to Word Converters',
        'comparison_subheading': 'See why users choose Axom AI over paywalled and ad-heavy alternatives.',
        'comparison_matrix_json': DEFAULT_COMPARISON_ROWS,
        'tech_spec_title': 'Technical Specifications & Supported Standards',
        'tech_spec_inputs': '.pdf (PDF 1.0 - 2.0, Scanned & Vector)',
        'tech_spec_output': 'Microsoft Word (.docx / Office Open XML)',
        'tech_spec_max_size': '25 Megabytes (MB)',
        'tech_spec_security': 'TLS 1.3 / SSL 256-bit',
        'faq_section_title': 'Frequently Asked Questions',
        'faq_section_subheading': 'Got questions about converting PDF to Word? Find verified answers below.',
        'cta_title': 'Convert Your PDF to Editable Word Now',
        'cta_desc': 'Experience fast, private, and watermark-free PDF to DOCX conversions trusted by users across Assam and India.',
        'cta_btn_primary_text': 'Upload PDF File Now',
        'cta_btn_primary_url': '#converter',
        'cta_btn_secondary_text': 'Explore All AI & Document Tools',
        'cta_btn_secondary_url': 'https://aiaxom.co.in/tools',
        'meta_title': 'Free PDF to Word Converter Online — Convert PDF to DOCX | Axom AI',
        'meta_description': 'Convert PDF to editable Word document (.docx) online for free in seconds. Retain original formatting, tables, images, and fonts with zero watermarks. 100% private and secure.',
        'meta_keywords': 'pdf to word converter, convert pdf to word, pdf to docx converter, free pdf to word converter, pdf to editable word, pdf to word converter online India, Assam ai document converter, pdf to docx without watermark',
        'canonical_url': 'https://aiaxom.co.in/tools/pdf-to-word',
        'og_image_url': 'https://aiaxom.co.in/static/dist/hero/assam.avif',
    },
    'image-to-pdf': {
        'tool_name': 'Image to PDF',
        'hero_badge_text': '⚡ Free: 20 Files / Day • 🖼️ Multi-Image Merge • 👑 Pro Batch Mode',
        'hero_heading_prefix': 'Free',
        'hero_heading_highlight': 'Image to PDF',
        'hero_heading_suffix': 'Converter Online',
        'hero_description': 'Convert one or multiple image files (JPG, PNG, WebP, HEIC) into a clean, structured PDF document instantly. Merge photos, receipts, or notes in any order with zero loss in resolution and no watermarks.',
        'free_daily_limit': 20,
        'pro_batch_limit': 20,
        'max_file_size_mb': 25,
        'how_it_works_title': 'How to Convert Images to PDF in 3 Easy Steps',
        'how_it_works_subheading': 'Combine multiple photos or single pictures into professional PDF files in seconds.',
        'step_1_title': 'Upload Images',
        'step_1_desc': 'Select one or more JPG, PNG, or WebP images from your computer or smartphone.',
        'step_2_title': 'Arrange & Convert',
        'step_2_desc': 'Review and order your images as desired, then click Convert to PDF Now.',
        'step_3_title': 'Download PDF',
        'step_3_desc': 'Download your merged, publication-grade PDF file instantly to your device.',
        'why_title': 'Why Axom AI Image to PDF is the Superior Choice',
        'why_subheading': 'Designed for students, mobile photographers, accountants, and businesses across Assam and India.',
        'benefit_1_title': 'Multi-Image Merge',
        'benefit_1_desc': 'Easily combine up to 20 images into a single sequentially ordered PDF document with 1 click.',
        'benefit_2_title': 'Lossless Resolution',
        'benefit_2_desc': 'Retains 100% of original photo DPI, color gamut, and sharpness without blurry downsampling.',
        'benefit_3_title': 'Zero Watermarks, 100% Free',
        'benefit_3_desc': 'Completely clean PDF outputs ready for official government, academic, or corporate submission.',
        'benefit_4_title': 'Automatic File Purging',
        'benefit_4_desc': 'Your photos are processed in isolated transient RAM and permanently deleted immediately after conversion.',
        'benefit_5_title': 'Mobile-First Design',
        'benefit_5_desc': 'Works effortlessly on Android and iPhone browsers without requiring heavy third-party scanner apps.',
        'benefit_6_title': 'Cross-Format Support',
        'benefit_6_desc': 'Handles JPG, PNG, WebP, JFIF, and HEIC files with automatic orientation and aspect ratio detection.',
        'comparison_badge': 'Direct Feature Comparison',
        'comparison_title': 'Axom AI vs. Traditional Image to PDF Converters',
        'comparison_subheading': 'See why users choose Axom AI over paywalled and ad-heavy alternatives.',
        'comparison_matrix_json': DEFAULT_COMPARISON_ROWS,
        'tech_spec_title': 'Technical Specifications & Supported Standards',
        'tech_spec_inputs': '.jpg, .jpeg, .png, .webp, .jfif, .heic',
        'tech_spec_output': 'PDF 1.7 / ISO 32000-1 (Multi-page Vector)',
        'tech_spec_max_size': '25 Megabytes (MB)',
        'tech_spec_security': 'TLS 1.3 / SSL 256-bit',
        'faq_section_title': 'Frequently Asked Questions',
        'faq_section_subheading': 'Got questions about converting images to PDF? Find verified answers below.',
        'cta_title': 'Convert Your Images to PDF in Seconds',
        'cta_desc': 'Experience fast, private, and watermark-free conversions trusted by users across Assam and India.',
        'cta_btn_primary_text': 'Upload Images Now',
        'cta_btn_primary_url': '#converter',
        'cta_btn_secondary_text': 'Explore All AI & Document Tools',
        'cta_btn_secondary_url': 'https://aiaxom.co.in/tools',
        'meta_title': 'Free Image to PDF Converter Online — JPG & PNG to PDF | Axom AI',
        'meta_description': 'Convert JPG, PNG, WebP and HEIC images to PDF online for free in seconds. Combine multiple photos into one clean PDF with zero watermarks. 100% secure.',
        'meta_keywords': 'image to pdf, convert image to pdf, jpg to pdf, png to pdf, photo to pdf, picture to pdf converter, multiple images to pdf, free image to pdf converter India, best image to pdf Assam',
        'canonical_url': 'https://aiaxom.co.in/tools/image-to-pdf',
        'og_image_url': 'https://aiaxom.co.in/static/dist/hero/assam.avif',
    },
    'pdf-to-jpg': {
        'tool_name': 'PDF to JPG',
        'hero_badge_text': '⚡ Free: 20 Files / Day • 📸 300 DPI High-Res • 👑 Pro Batch Mode',
        'hero_heading_prefix': 'Free',
        'hero_heading_highlight': 'PDF to JPG',
        'hero_heading_suffix': 'Converter Online',
        'hero_description': 'Extract every page of your PDF into high-resolution, crystal-clear JPEG image files in seconds. Download individual page images or package everything into a single high-speed ZIP archive.',
        'free_daily_limit': 20,
        'pro_batch_limit': 20,
        'max_file_size_mb': 25,
        'how_it_works_title': 'How to Convert PDF to JPG in 3 Easy Steps',
        'how_it_works_subheading': 'Extract crystal-clear JPEG images from PDF pages in seconds.',
        'step_1_title': 'Upload PDF Document',
        'step_1_desc': 'Drag and drop your PDF document into the upload area above or select it from your local storage.',
        'step_2_title': 'High-Res Rasterization',
        'step_2_desc': 'Click Convert. Our high-resolution rasterization engine renders every page at up to 300 DPI.',
        'step_3_title': 'Download JPG Images',
        'step_3_desc': 'Download individual high-res JPG page images or grab the entire ZIP package in 1 click.',
        'why_title': 'Why Axom AI PDF to JPG is the Superior Choice',
        'why_subheading': 'Engineered for publishers, researchers, designers, and students needing high-fidelity image extractions.',
        'benefit_1_title': '300 DPI High-Res Clarity',
        'benefit_1_desc': 'Renders vector lines, tiny fonts, mathematical symbols, and illustrations with razor-sharp fidelity.',
        'benefit_2_title': '1-Click ZIP Download',
        'benefit_2_desc': 'Multi-page PDFs are automatically bundled into a single organized ZIP archive for instant downloading.',
        'benefit_3_title': 'Zero Watermarks, 100% Free',
        'benefit_3_desc': 'No advertising banners, promotional stamps, or resolution degradation. Pristine images ready to use.',
        'benefit_4_title': 'Automatic File Purging',
        'benefit_4_desc': 'Your PDF documents are encrypted in transit and purged automatically from server RAM right after conversion.',
        'benefit_5_title': 'Universal Device Support',
        'benefit_5_desc': 'Works seamlessly on Android, iOS, Windows, macOS, Linux, and ChromeOS without installing extra apps.',
        'benefit_6_title': 'Sub-3-Second Speed',
        'benefit_6_desc': 'High-speed cloud rasterization micro-services extract standard documents in less than 3 seconds.',
        'comparison_badge': 'Direct Feature Comparison',
        'comparison_title': 'Axom AI vs. Traditional PDF to JPG Converters',
        'comparison_subheading': 'See why users choose Axom AI over paywalled and ad-heavy alternatives.',
        'comparison_matrix_json': DEFAULT_COMPARISON_ROWS,
        'tech_spec_title': 'Technical Specifications & Supported Standards',
        'tech_spec_inputs': '.pdf (PDF 1.0 - 2.0, Multi-page)',
        'tech_spec_output': 'JPEG / JFIF (300 DPI High-Resolution)',
        'tech_spec_max_size': '25 Megabytes (MB)',
        'tech_spec_security': 'TLS 1.3 / SSL 256-bit',
        'faq_section_title': 'Frequently Asked Questions',
        'faq_section_subheading': 'Got questions about PDF to JPG conversion? Find verified answers below.',
        'cta_title': 'Extract Crystal-Clear JPG Images in Seconds',
        'cta_desc': 'Experience fast, private, and watermark-free PDF to JPG conversions trusted by users across Assam and India.',
        'cta_btn_primary_text': 'Upload PDF File Now',
        'cta_btn_primary_url': '#converter',
        'cta_btn_secondary_text': 'Explore All AI & Document Tools',
        'cta_btn_secondary_url': 'https://aiaxom.co.in/tools',
        'meta_title': 'Free PDF to JPG Converter Online — Extract High-Res JPG | Axom AI',
        'meta_description': 'Convert PDF to JPG images online for free in seconds. Extract high-resolution 300 DPI JPEG pictures from PDF pages with zero watermarks. 100% private and secure.',
        'meta_keywords': 'pdf to jpg, convert pdf to jpg, pdf to jpeg converter, free pdf to jpg, pdf to image converter, extract images from pdf, high resolution pdf to jpg, pdf to jpg online India, Assam ai document converter',
        'canonical_url': 'https://aiaxom.co.in/tools/pdf-to-jpg',
        'og_image_url': 'https://aiaxom.co.in/static/dist/hero/assam.avif',
    },
    'pdf-to-png': {
        'tool_name': 'PDF to PNG',
        'hero_badge_text': '⚡ Free: 20 Files / Day • 💎 Lossless & Transparent • 👑 Pro Batch Mode',
        'hero_heading_prefix': 'Free',
        'hero_heading_highlight': 'PDF to PNG',
        'hero_heading_suffix': 'Converter Online',
        'hero_description': 'Convert PDF pages into lossless, transparent PNG graphic files with pixel-perfect edge rendering. Ideal for designers, developers, and educators who demand high-fidelity transparency without compression artifacts.',
        'free_daily_limit': 20,
        'pro_batch_limit': 20,
        'max_file_size_mb': 25,
        'how_it_works_title': 'How to Convert PDF to PNG in 3 Easy Steps',
        'how_it_works_subheading': 'Extract lossless, transparent PNG images from PDF pages in seconds.',
        'step_1_title': 'Upload PDF Document',
        'step_1_desc': 'Drag and drop your PDF document into the converter box above or choose it from your local storage.',
        'step_2_title': 'Lossless Rendering',
        'step_2_desc': 'Click Convert. Our raster engine renders vector graphics, fonts, and transparency channels losslessly.',
        'step_3_title': 'Download PNG Images',
        'step_3_desc': 'Download individual transparent PNG images or grab the entire ZIP package in 1 click.',
        'why_title': 'Why Axom AI PDF to PNG is the Superior Choice',
        'why_subheading': 'Engineered for UI designers, developers, publishers, and educators who need lossless visual fidelity.',
        'benefit_1_title': 'Lossless Transparency',
        'benefit_1_desc': 'Preserves true alpha transparency channels for logos, icons, diagrams, and vector page elements.',
        'benefit_2_title': '1-Click ZIP Download',
        'benefit_2_desc': 'Multi-page PDFs are automatically bundled into a single organized ZIP archive for instant downloading.',
        'benefit_3_title': 'Zero Watermarks, 100% Free',
        'benefit_3_desc': 'No promotional stamps, logos, or forced signups. Output PNG images are 100% clean and print-ready.',
        'benefit_4_title': 'Automatic File Purging',
        'benefit_4_desc': 'Your PDF documents are encrypted in transit and purged automatically from server RAM right after conversion.',
        'benefit_5_title': 'Universal Device Support',
        'benefit_5_desc': 'Works seamlessly on Android, iOS, Windows, macOS, Linux, and ChromeOS without installing extra apps.',
        'benefit_6_title': 'Sub-3-Second Speed',
        'benefit_6_desc': 'High-speed cloud rasterization micro-services extract standard documents in less than 3 seconds.',
        'comparison_badge': 'Direct Feature Comparison',
        'comparison_title': 'Axom AI vs. Traditional PDF to PNG Converters',
        'comparison_subheading': 'See why users choose Axom AI over paywalled and ad-heavy alternatives.',
        'comparison_matrix_json': DEFAULT_COMPARISON_ROWS,
        'tech_spec_title': 'Technical Specifications & Supported Standards',
        'tech_spec_inputs': '.pdf (PDF 1.0 - 2.0, Multi-page)',
        'tech_spec_output': 'PNG (Lossless 24-bit/32-bit Alpha Transparency)',
        'tech_spec_max_size': '25 Megabytes (MB)',
        'tech_spec_security': 'TLS 1.3 / SSL 256-bit',
        'faq_section_title': 'Frequently Asked Questions',
        'faq_section_subheading': 'Got questions about PDF to PNG conversion? Find verified answers below.',
        'cta_title': 'Extract Lossless Transparent PNGs in Seconds',
        'cta_desc': 'Experience fast, private, and watermark-free PDF to PNG conversions trusted by users across Assam and India.',
        'cta_btn_primary_text': 'Upload PDF File Now',
        'cta_btn_primary_url': '#converter',
        'cta_btn_secondary_text': 'Explore All AI & Document Tools',
        'cta_btn_secondary_url': 'https://aiaxom.co.in/tools',
        'meta_title': 'Free PDF to PNG Converter Online — Lossless & Transparent | Axom AI',
        'meta_description': 'Convert PDF to PNG images online for free in seconds. Extract lossless, transparent PNG pictures from PDF pages with zero watermarks. 100% private and secure.',
        'meta_keywords': 'pdf to png, convert pdf to png, pdf to png converter, free pdf to png, pdf to transparent png, extract png from pdf, lossless pdf to png, pdf to png online India, Assam ai document converter',
        'canonical_url': 'https://aiaxom.co.in/tools/pdf-to-png',
        'og_image_url': 'https://aiaxom.co.in/static/dist/hero/assam.avif',
    },
    'image-format-converter': {
        'tool_name': 'Image Format Converter',
        'hero_badge_text': '⚡ Free: 20 Files / Day • 🔄 WebP, JFIF, SVG, PNG, JPG • 👑 Pro Batch Mode',
        'hero_heading_prefix': 'Free',
        'hero_heading_highlight': 'Image Format',
        'hero_heading_suffix': 'Converter Online',
        'hero_description': 'Convert any image format instantly in your browser. Convert WebP to PNG, JFIF to JPG, SVG to PNG, HEIC to JPG, BMP to PNG, and more. 100% free with lossless quality, zero watermarks, and bank-grade privacy.',
        'free_daily_limit': 20,
        'pro_batch_limit': 20,
        'max_file_size_mb': 25,
        'how_it_works_title': 'How to Convert Image Formats in 3 Easy Steps',
        'how_it_works_subheading': 'Fast, lossless image format conversion right in your browser.',
        'step_1_title': 'Upload Your Image',
        'step_1_desc': 'Drag and drop any image (WebP, JFIF, SVG, HEIC, PNG, JPG, BMP) into the converter.',
        'step_2_title': 'Choose Target Format',
        'step_2_desc': 'Select your desired output format (PNG for transparency, JPG for compatibility, WebP for web).',
        'step_3_title': 'Download Converted File',
        'step_3_desc': 'Click Convert Now and download your converted, watermark-free image immediately.',
        'why_title': 'Why Axom AI Image Format Converter is the Superior Choice',
        'why_subheading': 'Engineered for web developers, designers, photographers, and creators who need fast, lossless transcoding.',
        'benefit_1_title': 'Universal Format Support',
        'benefit_1_desc': 'Convert between JPG, PNG, WebP, SVG, JFIF, HEIC, BMP, TIFF, AVIF, and GIF with full compatibility.',
        'benefit_2_title': 'Lossless Color & Transparency',
        'benefit_2_desc': 'Preserves alpha transparency channels, color gamuts, and pixel sharpness across conversions.',
        'benefit_3_title': 'Zero Watermarks, 100% Free',
        'benefit_3_desc': 'No promotional stamps, logos, or forced subscriptions. Clean, ready-to-use images every time.',
        'benefit_4_title': 'Automatic File Purging',
        'benefit_4_desc': 'Your files are processed in isolated transient RAM and permanently deleted immediately after conversion.',
        'benefit_5_title': 'Universal Device Support',
        'benefit_5_desc': 'Works seamlessly on Android, iOS, Windows, macOS, Linux, and ChromeOS without installing extra apps.',
        'benefit_6_title': 'Sub-3-Second Speed',
        'benefit_6_desc': 'High-speed cloud image transcoding micro-services convert standard images in under 3 seconds.',
        'comparison_badge': 'Direct Feature Comparison',
        'comparison_title': 'Axom AI vs. Traditional Image Converters',
        'comparison_subheading': 'See why users choose Axom AI over paywalled and ad-heavy alternatives.',
        'comparison_matrix_json': DEFAULT_COMPARISON_ROWS,
        'tech_spec_title': 'Technical Specifications & Supported Standards',
        'tech_spec_inputs': 'JFIF, WebP, SVG, BMP, TIFF, AVIF, HEIC, PNG, JPG',
        'tech_spec_output': 'PNG, JPG, WebP, SVG, BMP',
        'tech_spec_max_size': '25 Megabytes (MB)',
        'tech_spec_security': 'TLS 1.3 / SSL 256-bit',
        'faq_section_title': 'Frequently Asked Questions',
        'faq_section_subheading': 'Got questions about image format conversion? Find verified answers below.',
        'cta_title': 'Convert Any Image Format in Seconds',
        'cta_desc': 'Experience fast, private, and watermark-free image conversions trusted by users across Assam and India.',
        'cta_btn_primary_text': 'Upload Image Now',
        'cta_btn_primary_url': '#converter',
        'cta_btn_secondary_text': 'Explore All AI & Document Tools',
        'cta_btn_secondary_url': 'https://aiaxom.co.in/tools',
        'meta_title': 'Free Image Format Converter Online — WebP, JFIF, SVG, PNG, JPG | Axom AI',
        'meta_description': 'Convert any image format online for free in seconds. Fast conversion between WebP, JFIF, SVG, PNG, JPG, AVIF, HEIC, and ICO. 100% private, no watermarks.',
        'meta_keywords': 'image format converter, webp to png converter, jfif to jpg converter, heic to jpg converter, svg to png converter, free image converter online India, best image converter Assam, next-gen image converter',
        'canonical_url': 'https://aiaxom.co.in/tools/image-format-converter',
        'og_image_url': 'https://aiaxom.co.in/static/dist/hero/assam.avif',
    },
    'image-compressor': {
        'tool_name': 'Image Compressor',
        'hero_badge_text': '⚡ Free Image Compressor — Private & In-Browser • 👑 20KB, 50KB, 100KB Target Presets',
        'hero_heading_prefix': 'Compress',
        'hero_heading_highlight': 'Images to Any Size',
        'hero_heading_suffix': 'in Your Browser',
        'hero_description': 'Make JPG, PNG, and WebP pictures smaller without a visible drop in quality. Pick a quality level or give a target size like 50 KB for exam forms and online portals. Compress many pictures at once and download them as a ZIP archive. Pictures never leave your device.',
        'free_daily_limit': 30,
        'pro_batch_limit': 30,
        'max_file_size_mb': 60,
        'how_it_works_title': 'How to Compress Images in 3 Easy Steps',
        'how_it_works_subheading': 'No complex software installation or account creation required. Fast and frictionless.',
        'step_1_title': 'Add Your Pictures',
        'step_1_desc': 'Drag and drop up to 30 pictures (JPG, PNG, WebP, GIF, BMP, AVIF) or click to browse from your phone or computer.',
        'step_2_title': 'Choose Quality or Target Size',
        'step_2_desc': 'Adjust the quality slider, or choose a target size like 20 KB, 50 KB, 100 KB for government & exam portals.',
        'step_3_title': 'Compress & Download',
        'step_3_desc': 'Inspect before and after file sizes, then download individual pictures or all of them together as a ZIP.',
        'why_title': 'Why Axom AI Image Compressor is the Superior Choice',
        'why_subheading': 'Engineered for students, educators, creators, and online applicants needing precise photo sizes.',
        'benefit_1_title': 'Target Size in KB',
        'benefit_1_desc': 'Type the exact size required by portals (20 KB, 50 KB, 100 KB). The engine finds the best quality that fits.',
        'benefit_2_title': 'Private by Design (Client-Side)',
        'benefit_2_desc': 'Compression runs locally in your web browser. Pictures are not uploaded to our servers, and EXIF data is removed.',
        'benefit_3_title': 'Batch + ZIP Download',
        'benefit_3_desc': 'Compress up to 30 images simultaneously with matching settings and download everything in one organized ZIP file.',
        'benefit_4_title': 'JPG, PNG, and WebP',
        'benefit_4_desc': 'Auto mode keeps JPG as JPG, uses WebP for transparent images, and JPG for the rest. Force any format anytime.',
        'benefit_5_title': 'Fast, No Queue',
        'benefit_5_desc': 'Zero upload waiting time. Instant high-performance in-browser canvas and WebAssembly compression.',
        'benefit_6_title': 'Never Bigger Guarantee',
        'benefit_6_desc': 'If an image is already well-optimized, the tool returns the original file instead of a larger re-encoded file.',
        'comparison_badge': 'Direct Feature Comparison',
        'comparison_title': 'Axom AI vs. Traditional Image Compressors',
        'comparison_subheading': 'See why users choose Axom AI over paywalled and ad-heavy alternatives.',
        'comparison_matrix_json': DEFAULT_COMPARISON_ROWS,
        'tech_spec_title': 'Technical Specifications & Supported Standards',
        'tech_spec_inputs': 'JPG, PNG, WebP, GIF, BMP, AVIF',
        'tech_spec_output': 'JPG, WebP, PNG',
        'tech_spec_max_size': '60 Megabytes (MB)',
        'tech_spec_security': '100% In-Browser (Zero Upload)',
        'faq_section_title': 'Frequently Asked Questions',
        'faq_section_subheading': 'Got questions about image compression? Find verified answers below.',
        'cta_title': 'Compress Your Images Now',
        'cta_desc': 'Reduce JPG, PNG, and WebP pictures to the exact size you need. Free, private, and instant.',
        'cta_btn_primary_text': 'Compress Images Now',
        'cta_btn_primary_url': '#converter',
        'cta_btn_secondary_text': 'Explore All AI & Document Tools',
        'cta_btn_secondary_url': 'https://aiaxom.co.in/tools',
        'meta_title': 'Image Compressor Online Free — Reduce JPG, PNG, WebP Size to 20KB, 50KB, 100KB | Axom AI',
        'meta_description': 'Compress JPG, PNG and WebP images online for free. Reduce a photo to 20 KB, 50 KB or 100 KB for exam forms, compress multiple pictures at once. 100% private in-browser.',
        'meta_keywords': 'image compressor, compress image online, reduce image size, compress jpg, compress png, compress webp, photo compressor, reduce photo size in kb, compress image to 50kb',
        'canonical_url': 'https://aiaxom.co.in/tools/image-compressor',
        'og_image_url': 'https://aiaxom.co.in/static/dist/hero/assam.avif',
    },
}


CONVERTER_DEFAULT_FAQS = {
    'word-to-pdf': [
        ('How do I convert Word to PDF online for free?', 'Simply drag and drop or upload your Microsoft Word file (.docx or .doc) into the Axom AI converter box above. Click "Convert to PDF Now", and within seconds, your high-resolution, fully formatted PDF will be ready to download. No registration, login, or payment is required.', 1),
        ('How many files can I convert for free per day?', 'Free users can convert up to 20 Word documents per day with zero watermarks and full quality preservation. Upgrade to Axom AI Pro for unlimited daily conversions and Pro Batch Mode.', 2),
        ('Can I convert multiple Word documents at once (Batch Conversion)?', 'Yes! Axom AI Pro subscribers have access to Pro Batch Mode, allowing you to convert up to 20 Word documents simultaneously with a single click.', 3),
        ('Will converting Word to PDF alter my original formatting, fonts, or tables?', 'No. Axom AI retains exact font families, text margins, bullet hierarchies, tables, image placements, headers, and footers.', 4),
        ('Is it safe to convert sensitive or confidential Word documents on Axom AI?', 'Yes, completely. All files are transferred using 256-bit SSL encryption and permanently deleted from our servers right after conversion.', 5),
        ('Does Axom AI add any watermark to the converted PDF?', 'No. Axom AI produces 100% clean, watermark-free PDFs suitable for legal, academic, professional, and corporate use.', 6),
    ],
    'pdf-to-word': [
        ('How to convert PDF to Word online for free?', 'Drag and drop your PDF document into the converter box above and click "Convert to Word Now". Within 2 to 3 seconds, your editable Microsoft Word document (.docx) will be ready for instant download.', 1),
        ('How can I convert PDF to DOCX without losing formatting?', 'Axom AI uses deep layout analysis algorithms that reconstruct native Microsoft Word table grids, headings, columns, and margins accurately.', 2),
        ('Can I convert PDF to Word on mobile (Android and iPhone)?', 'Yes. Axom AI PDF to Word Converter is 100% mobile-friendly on Chrome, Safari, or any mobile browser without installing extra apps.', 3),
        ('Does Axom AI add any watermark to the converted Word document?', 'No. Output files are clean, professional, and ready for legal submissions, corporate presentations, and university assignments.', 4),
    ],
    'image-to-pdf': [
        ('How to convert image to PDF online for free?', 'Drag and drop or select your JPG, PNG, JPEG, or WebP images in the converter box above, reorder as needed, and click "Convert to PDF Now".', 1),
        ('How to convert multiple images into one PDF?', 'Axom AI allows you to upload multiple images at once to merge them into a single multi-page PDF document in 1 click.', 2),
        ('Does converting images to PDF reduce quality?', 'No. Axom AI preserves 100% of the original photo resolution, DPI, and color depth.', 3),
    ],
    'pdf-to-jpg': [
        ('How to convert PDF to JPG online for free?', 'Upload your PDF document, choose standard or high-resolution extraction, and click "Convert to JPG Now". Download individual JPGs or a single ZIP archive.', 1),
        ('How to convert PDF to high-resolution 300 DPI JPG?', 'Axom AI renders vector text, embedded photographs, and complex charts at up to 300 DPI print-quality resolution.', 2),
    ],
    'pdf-to-png': [
        ('How to convert PDF to transparent PNG?', 'Axom AI natively preserves alpha channel transparency during conversion, making it ideal for web design, logos, and graphic composition.', 1),
        ('What is the difference between PDF to PNG and PDF to JPG?', 'PNG is a lossless format that supports transparency and crisp edges. JPG is optimal for photography where smaller file sizes are prioritized.', 2),
    ],
    'image-format-converter': [
        ('How do I convert image format online for free?', 'Drag and drop your image (JPG, PNG, WebP, HEIC, SVG, GIF, BMP, TIFF, JFIF, AVIF), select your target format, and click "Convert Now".', 1),
        ('How to convert WebP to JPG or WebP to PNG?', 'Upload the WebP file, choose JPG or PNG, and click Convert. The converted file works across all legacy image viewers and desktop apps.', 2),
    ],
    'image-compressor': [
        ('Is this image compressor free and private?', 'Yes. It is 100% free, needs no signup, adds no watermark, and runs entirely inside your browser so pictures never leave your device.', 1),
        ('How do I reduce a photo to 50 KB for an exam form?', 'Choose “To a target size”, select 50 KB (or type 50), add your photo, and click Compress. The tool optimizes the image to fit under 50 KB while preserving clarity.', 2),
        ('Can I compress multiple pictures at once and download a ZIP?', 'Yes! You can add up to 30 images simultaneously and download them individually or package all of them into a single ZIP archive.', 3),
        ('Does it remove EXIF and location data from photos?', 'Yes. The compressed copy automatically strips location GPS coordinates and camera EXIF metadata for maximum privacy.', 4),
    ],
}


def ensure_converter_tool_defaults(tool_slug):
    """
    Ensure the ConverterToolConfig and default FAQs exist for the specified tool_slug.
    If tool_slug == 'word-to-pdf' and WordToPdfToolConfig exists, migrates data across.
    Uses rich dynamic fallback generators so all 31 tools have full default configs.
    """
    config = ConverterToolConfig.objects.filter(tool_slug=tool_slug).first()

    if not config:
        if tool_slug == 'word-to-pdf':
            old_cfg = WordToPdfToolConfig.objects.first()
            if old_cfg:
                config = ConverterToolConfig.objects.create(
                    tool_slug='word-to-pdf',
                    tool_name='Word to PDF',
                    hero_badge_text=old_cfg.hero_badge_text,
                    hero_heading_prefix=old_cfg.hero_heading_prefix,
                    hero_heading_highlight=old_cfg.hero_heading_highlight,
                    hero_heading_suffix=old_cfg.hero_heading_suffix,
                    hero_description=old_cfg.hero_description,
                    free_daily_limit=old_cfg.free_daily_limit,
                    pro_batch_limit=old_cfg.pro_batch_limit,
                    max_file_size_mb=old_cfg.max_file_size_mb,
                    how_it_works_title=old_cfg.how_it_works_title,
                    how_it_works_subheading=old_cfg.how_it_works_subheading,
                    step_1_title=old_cfg.step_1_title,
                    step_1_desc=old_cfg.step_1_desc,
                    step_2_title=old_cfg.step_2_title,
                    step_2_desc=old_cfg.step_2_desc,
                    step_3_title=old_cfg.step_3_title,
                    step_3_desc=old_cfg.step_3_desc,
                    why_title=old_cfg.why_title,
                    why_subheading=old_cfg.why_subheading,
                    benefit_1_title=old_cfg.benefit_1_title,
                    benefit_1_desc=old_cfg.benefit_1_desc,
                    benefit_2_title=old_cfg.benefit_2_title,
                    benefit_2_desc=old_cfg.benefit_2_desc,
                    benefit_3_title=old_cfg.benefit_3_title,
                    benefit_3_desc=old_cfg.benefit_3_desc,
                    benefit_4_title=old_cfg.benefit_4_title,
                    benefit_4_desc=old_cfg.benefit_4_desc,
                    benefit_5_title=old_cfg.benefit_5_title,
                    benefit_5_desc=old_cfg.benefit_5_desc,
                    benefit_6_title=old_cfg.benefit_6_title,
                    benefit_6_desc=old_cfg.benefit_6_desc,
                    comparison_badge=old_cfg.comparison_badge,
                    comparison_title=old_cfg.comparison_title,
                    comparison_subheading=old_cfg.comparison_subheading,
                    comparison_matrix_json=old_cfg.comparison_matrix_json,
                    tech_spec_title=old_cfg.tech_spec_title,
                    tech_spec_inputs=old_cfg.tech_spec_inputs,
                    tech_spec_output=old_cfg.tech_spec_output,
                    tech_spec_max_size=old_cfg.tech_spec_max_size,
                    tech_spec_security=old_cfg.tech_spec_security,
                    faq_section_title=old_cfg.faq_section_title,
                    faq_section_subheading=old_cfg.faq_section_subheading,
                    cta_title=old_cfg.cta_title,
                    cta_desc=old_cfg.cta_desc,
                    cta_btn_primary_text=old_cfg.cta_btn_primary_text,
                    cta_btn_primary_url=old_cfg.cta_btn_primary_url,
                    cta_btn_secondary_text=old_cfg.cta_btn_secondary_text,
                    cta_btn_secondary_url=old_cfg.cta_btn_secondary_url,
                    meta_title=old_cfg.meta_title,
                    meta_description=old_cfg.meta_description,
                    meta_keywords=old_cfg.meta_keywords,
                    canonical_url=old_cfg.canonical_url,
                    og_image_url=old_cfg.og_image_url,
                )
                for f in WordToPdfFAQ.objects.filter(tool_config=old_cfg):
                    ConverterToolFAQ.objects.create(
                        tool_config=config,
                        question=f.question,
                        answer=f.answer,
                        order=f.order,
                        is_active=f.is_active,
                    )
                return config

        defaults = CONVERTER_TOOLS_DEFAULTS.get(tool_slug) or generate_tool_defaults(tool_slug)
        config = ConverterToolConfig.objects.create(
            tool_slug=tool_slug,
            **defaults
        )

    # Ensure FAQs exist
    if ConverterToolFAQ.objects.filter(tool_config=config).count() == 0:
        faq_list = CONVERTER_DEFAULT_FAQS.get(tool_slug) or generate_tool_faqs(tool_slug)
        for q, a, order in faq_list:
            ConverterToolFAQ.objects.create(
                tool_config=config,
                question=q,
                answer=a,
                order=order,
                is_active=True,
            )

    return config
