import json
from .models import (
    ConverterToolConfig,
    ConverterToolFAQ,
    WordToPdfToolConfig,
    WordToPdfFAQ,
    DEFAULT_COMPARISON_ROWS,
)

CONVERTER_TOOLS_METADATA = {
    'word-to-pdf': {
        'name': 'Word to PDF',
        'icon': 'fa-solid fa-file-pdf text-red-400',
        'badge': 'Hero, How-To, Specs & FAQs',
        'target_url': 'https://aiaxom.co.in/tools/word-to-pdf',
    },
    'pdf-to-word': {
        'name': 'PDF to Word',
        'icon': 'fa-solid fa-file-word text-blue-400',
        'badge': 'Hero, How-To, Specs & FAQs',
        'target_url': 'https://aiaxom.co.in/tools/pdf-to-word',
    },
    'image-to-pdf': {
        'name': 'Image to PDF',
        'icon': 'fa-solid fa-file-image text-emerald-400',
        'badge': 'Hero, How-To, Specs & FAQs',
        'target_url': 'https://aiaxom.co.in/tools/image-to-pdf',
    },
    'pdf-to-jpg': {
        'name': 'PDF to JPG',
        'icon': 'fa-solid fa-image text-amber-400',
        'badge': 'Hero, How-To, Specs & FAQs',
        'target_url': 'https://aiaxom.co.in/tools/pdf-to-jpg',
    },
    'pdf-to-png': {
        'name': 'PDF to PNG',
        'icon': 'fa-solid fa-images text-cyan-400',
        'badge': 'Hero, How-To, Specs & FAQs',
        'target_url': 'https://aiaxom.co.in/tools/pdf-to-png',
    },
    'image-format-converter': {
        'name': 'Image Format Converter',
        'icon': 'fa-solid fa-arrows-rotate text-purple-400',
        'badge': 'Hero, How-To, Specs & FAQs',
        'target_url': 'https://aiaxom.co.in/tools/image-format-converter',
    },
}

CONVERTER_TOOLS_DEFAULTS = {
    'word-to-pdf': {
        'tool_name': 'Word to PDF',
        'hero_badge_text': '⚡ Free: 20 Files / Day • 👑 Pro: Batch Convert 20 Files at Once',
        'hero_heading_prefix': 'Free',
        'hero_heading_highlight': 'Word to PDF',
        'hero_heading_suffix': 'Converter Online',
        'hero_description': 'Convert your Microsoft Word (.DOCX, .DOC), Rich Text, and text files into professional, print-ready PDF documents instantly. Free accounts can convert up to 20 files per day. Upgrade to Premium for unlimited daily conversions and Pro Batch Mode to convert up to 20 files simultaneously in 1 click!',
        'free_daily_limit': 20,
        'pro_batch_limit': 20,
        'max_file_size_mb': 25,
        'how_it_works_title': 'How to Convert Word to PDF in 3 Easy Steps',
        'how_it_works_subheading': 'No complex software installation or account creation required. Fast and frictionless.',
        'step_1_title': 'Upload Document',
        'step_1_desc': 'Drag and drop your DOCX or DOC file into the converter box above or choose it from your local storage.',
        'step_2_title': 'Instant Processing',
        'step_2_desc': 'Click Convert. Our high-fidelity document engine parses structures, styles, margins, and media in seconds.',
        'step_3_title': 'Download PDF',
        'step_3_desc': 'Download your clean, publication-ready PDF document directly to your device. No watermarks, ever.',
        'why_title': 'Why Axom AI Word to PDF is the Superior Choice',
        'why_subheading': 'Engineered for students, educators, legal professionals, and businesses who demand accuracy and privacy.',
        'benefit_1_title': 'Lossless Layout Fidelity',
        'benefit_1_desc': 'Headers, footers, footnotes, complex tables, embedded charts, and custom fonts stay strictly aligned without shifting pages.',
        'benefit_2_title': 'Zero Watermarks, 100% Free',
        'benefit_2_desc': 'No hidden subscription traps or promotional watermarks stamped across your pages. Clean documents ready for official submissions.',
        'benefit_3_title': 'Automatic File Purging',
        'benefit_3_desc': 'Documents are processed securely via SSL encryption and purged automatically from our server memory right after conversion.',
        'benefit_4_title': 'Universal Device Support',
        'benefit_4_desc': 'Works seamlessly on iOS, Android, macOS, Windows, and Linux. No apps or browser extensions needed.',
        'benefit_5_title': 'Sub-3-Second Speed',
        'benefit_5_desc': 'High-speed optimized micro-services convert standard documents in less than 3 seconds with minimal bandwidth usage.',
        'benefit_6_title': 'Multi-Format Compatibility',
        'benefit_6_desc': 'Handles DOCX, DOC, RTF, TXT, and ODT with automatic format detection and smart structure extraction.',
        'comparison_badge': 'Direct Feature Comparison',
        'comparison_title': 'Axom AI vs. Traditional Word to PDF Converters',
        'comparison_subheading': 'See why users choose Axom AI over paywalled and ad-heavy alternatives.',
        'comparison_matrix_json': DEFAULT_COMPARISON_ROWS,
        'tech_spec_title': 'Technical Specifications & Supported Standards',
        'tech_spec_inputs': '.docx, .doc, .rtf, .txt, .odt',
        'tech_spec_output': 'PDF 1.7 / ISO 32000-1 (Vector)',
        'tech_spec_max_size': '25 Megabytes (MB)',
        'tech_spec_security': 'TLS 1.3 / SSL 256-bit',
        'faq_section_title': 'Frequently Asked Questions',
        'faq_section_subheading': 'Got questions about Word to PDF conversion? Find verified answers below.',
        'cta_title': 'Convert Your Word Documents in Seconds',
        'cta_desc': 'Experience fast, private, and watermark-free conversions trusted by users across Assam and India.',
        'cta_btn_primary_text': 'Upload Word File Now',
        'cta_btn_primary_url': '#converter',
        'cta_btn_secondary_text': 'Explore All AI & Document Tools',
        'cta_btn_secondary_url': 'https://aiaxom.co.in/tools',
        'meta_title': 'Free Word to PDF Converter Online — Convert DOCX to PDF | Axom AI',
        'meta_description': 'Convert Microsoft Word (.docx, .doc) to PDF online for free in seconds. Preserve original formatting, tables, fonts, and images. 100% secure with automatic file deletion.',
        'meta_keywords': 'Word to PDF, Word to PDF converter, convert word to pdf online free, docx to pdf converter, doc to pdf, convert word document to pdf, best free word to pdf converter, word to pdf without watermark, axom ai tools, assam ai document converter, free docx to pdf high quality, Word to PDF converter India, PDF tools Assam',
        'canonical_url': 'https://aiaxom.co.in/tools/word-to-pdf',
        'og_image_url': 'https://aiaxom.co.in/static/dist/hero/assam.avif',
    },
    'pdf-to-word': {
        'tool_name': 'PDF to Word',
        'hero_badge_text': '⚡ Free: 20 Files / Day • 🛡️ No Watermark • 👑 Pro Batch Mode',
        'hero_heading_prefix': 'Free',
        'hero_heading_highlight': 'PDF to Word',
        'hero_heading_suffix': 'Converter Online',
        'hero_description': 'Turn any PDF file into an editable Microsoft Word document (.docx) with unmatched layout and table precision. Free users can convert up to 20 files daily with zero watermarks. Upgrade to Axom AI Pro for unlimited conversions and instant 20-file batch processing.',
        'free_daily_limit': 20,
        'pro_batch_limit': 20,
        'max_file_size_mb': 25,
        'how_it_works_title': 'How to Convert PDF to Word in 3 Easy Steps',
        'how_it_works_subheading': 'Effortlessly transform static PDF documents into fully editable Word documents in seconds.',
        'step_1_title': 'Upload Your PDF',
        'step_1_desc': 'Drag and drop your PDF document into the converter box above or choose it from your local computer or phone storage.',
        'step_2_title': 'Instant Structural Analysis',
        'step_2_desc': 'Click Convert to Word. Our deep layout engine recognizes headings, tables, columns, and graphics in seconds.',
        'step_3_title': 'Download Editable DOCX',
        'step_3_desc': 'Download your publication-grade, fully editable Microsoft Word document directly to your device without watermarks.',
        'why_title': 'Why Axom AI PDF to Word is the Superior Choice',
        'why_subheading': 'Engineered for students, legal teams, educators, and enterprise users who demand layout fidelity and data confidentiality.',
        'benefit_1_title': 'Native Editable Tables',
        'benefit_1_desc': 'Complex tables, budgets, and invoices are reconstructed as native Word table grids, not broken floating text boxes.',
        'benefit_2_title': 'Zero Watermarks, 100% Free',
        'benefit_2_desc': 'No advertising banners, hidden subscription traps, or promotional watermarks stamped across your pages.',
        'benefit_3_title': 'Automatic File Purging',
        'benefit_3_desc': 'Documents are processed securely via 256-bit SSL encryption and permanently deleted from server memory right after conversion.',
        'benefit_4_title': 'Universal Device Support',
        'benefit_4_desc': 'Works seamlessly on Android, iPhone, Windows, macOS, Linux, and ChromeOS without installing extra software.',
        'benefit_5_title': 'Sub-3-Second Speed',
        'benefit_5_desc': 'High-performance cloud document micro-services convert standard PDF files in less than 3 seconds.',
        'benefit_6_title': 'Font & Layout Preservation',
        'benefit_6_desc': 'Retains font styles, margins, bulleted lists, indentations, and embedded graphics faithfully.',
        'comparison_badge': 'Direct Feature Comparison',
        'comparison_title': 'Axom AI vs. Traditional PDF to Word Converters',
        'comparison_subheading': 'See why users choose Axom AI over paywalled and ad-heavy alternatives.',
        'comparison_matrix_json': DEFAULT_COMPARISON_ROWS,
        'tech_spec_title': 'Technical Specifications & Supported Standards',
        'tech_spec_inputs': '.pdf (PDF 1.0 - 2.0, Scanned & Vector)',
        'tech_spec_output': 'Microsoft Word (.docx / Office Open XML)',
        'tech_spec_max_size': '25 Megabytes (MB)',
        'tech_spec_security': 'TLS 1.3 / SSL 256-bit',
        'faq_section_title': 'Frequently Asked Questions',
        'faq_section_subheading': 'Got questions about converting PDF to Word? Find verified answers below.',
        'cta_title': 'Convert Your PDF to Editable Word Now',
        'cta_desc': 'Experience fast, private, and watermark-free PDF to DOCX conversions trusted by users across Assam and India.',
        'cta_btn_primary_text': 'Upload PDF File Now',
        'cta_btn_primary_url': '#converter',
        'cta_btn_secondary_text': 'Explore All AI & Document Tools',
        'cta_btn_secondary_url': 'https://aiaxom.co.in/tools',
        'meta_title': 'Free PDF to Word Converter Online — Convert PDF to DOCX | Axom AI',
        'meta_description': 'Convert PDF to editable Word document (.docx) online for free in seconds. Retain original formatting, tables, images, and fonts with zero watermarks. 100% private and secure.',
        'meta_keywords': 'pdf to word converter, convert pdf to word, pdf to docx converter, free pdf to word converter, pdf to editable word, pdf to word converter online India, Assam ai document converter, pdf to docx without watermark',
        'canonical_url': 'https://aiaxom.co.in/tools/pdf-to-word',
        'og_image_url': 'https://aiaxom.co.in/static/dist/hero/assam.avif',
    },
    'image-to-pdf': {
        'tool_name': 'Image to PDF',
        'hero_badge_text': '⚡ Free: 20 Files / Day • 🖼️ Multi-Image Merge • 👑 Pro Batch Mode',
        'hero_heading_prefix': 'Free',
        'hero_heading_highlight': 'Image to PDF',
        'hero_heading_suffix': 'Converter Online',
        'hero_description': 'Convert one or multiple image files (JPG, PNG, WebP, HEIC) into a clean, structured PDF document instantly. Merge photos, receipts, or notes in any order with zero loss in resolution and no watermarks.',
        'free_daily_limit': 20,
        'pro_batch_limit': 20,
        'max_file_size_mb': 25,
        'how_it_works_title': 'How to Convert Images to PDF in 3 Easy Steps',
        'how_it_works_subheading': 'Combine multiple photos or single pictures into professional PDF files in seconds.',
        'step_1_title': 'Upload Images',
        'step_1_desc': 'Select one or more JPG, PNG, or WebP images from your computer or smartphone.',
        'step_2_title': 'Arrange & Convert',
        'step_2_desc': 'Review and order your images as desired, then click Convert to PDF Now.',
        'step_3_title': 'Download PDF',
        'step_3_desc': 'Download your merged, publication-grade PDF file instantly to your device.',
        'why_title': 'Why Axom AI Image to PDF is the Superior Choice',
        'why_subheading': 'Designed for students, mobile photographers, accountants, and businesses across Assam and India.',
        'benefit_1_title': 'Multi-Image Merge',
        'benefit_1_desc': 'Easily combine up to 20 images into a single sequentially ordered PDF document with 1 click.',
        'benefit_2_title': 'Lossless Resolution',
        'benefit_2_desc': 'Retains 100% of original photo DPI, color gamut, and sharpness without blurry downsampling.',
        'benefit_3_title': 'Zero Watermarks, 100% Free',
        'benefit_3_desc': 'Completely clean PDF outputs ready for official government, academic, or corporate submission.',
        'benefit_4_title': 'Automatic File Purging',
        'benefit_4_desc': 'Your photos are processed in isolated transient RAM and permanently deleted immediately after conversion.',
        'benefit_5_title': 'Mobile-First Design',
        'benefit_5_desc': 'Works effortlessly on Android and iPhone browsers without requiring heavy third-party scanner apps.',
        'benefit_6_title': 'Cross-Format Support',
        'benefit_6_desc': 'Handles JPG, PNG, WebP, JFIF, and HEIC files with automatic orientation and aspect ratio detection.',
        'comparison_badge': 'Direct Feature Comparison',
        'comparison_title': 'Axom AI vs. Traditional Image to PDF Converters',
        'comparison_subheading': 'See why users choose Axom AI over paywalled and ad-heavy alternatives.',
        'comparison_matrix_json': DEFAULT_COMPARISON_ROWS,
        'tech_spec_title': 'Technical Specifications & Supported Standards',
        'tech_spec_inputs': '.jpg, .jpeg, .png, .webp, .jfif, .heic',
        'tech_spec_output': 'PDF 1.7 / ISO 32000-1 (Multi-page Vector)',
        'tech_spec_max_size': '25 Megabytes (MB)',
        'tech_spec_security': 'TLS 1.3 / SSL 256-bit',
        'faq_section_title': 'Frequently Asked Questions',
        'faq_section_subheading': 'Got questions about converting images to PDF? Find verified answers below.',
        'cta_title': 'Combine and Convert Your Images into PDF',
        'cta_desc': 'Experience fast, private, and watermark-free photo-to-PDF conversions trusted across Assam and India.',
        'cta_btn_primary_text': 'Upload Images Now',
        'cta_btn_primary_url': '#converter',
        'cta_btn_secondary_text': 'Explore All AI & Document Tools',
        'cta_btn_secondary_url': 'https://aiaxom.co.in/tools',
        'meta_title': 'Free Image to PDF Converter Online — Convert JPG & PNG to PDF | Axom AI',
        'meta_description': 'Convert JPG, PNG, WEBP and multiple photos into high-quality PDF documents online for free. Combine pictures into one clean PDF with zero watermarks or quality loss.',
        'meta_keywords': 'image to pdf converter, convert image to pdf, jpg to pdf converter, png to pdf converter, merge images into pdf, free image to pdf converter India, photos to pdf Assam, picture to pdf online free',
        'canonical_url': 'https://aiaxom.co.in/tools/image-to-pdf',
        'og_image_url': 'https://aiaxom.co.in/static/dist/hero/assam.avif',
    },
    'pdf-to-jpg': {
        'tool_name': 'PDF to JPG',
        'hero_badge_text': '⚡ Free: 20 Files / Day • 📸 300 DPI High-Res • 👑 Pro Batch Mode',
        'hero_heading_prefix': 'Free',
        'hero_heading_highlight': 'PDF to JPG',
        'hero_heading_suffix': 'Converter Online',
        'hero_description': 'Extract PDF pages into ultra-crisp, high-resolution JPEG image files at 300 DPI. Convert entire multi-page documents or single sheets with brilliant color fidelity and zero watermarks.',
        'free_daily_limit': 20,
        'pro_batch_limit': 20,
        'max_file_size_mb': 25,
        'how_it_works_title': 'How to Convert PDF to JPG in 3 Easy Steps',
        'how_it_works_subheading': 'Fast and effortless extraction of PDF pages into crystal-clear JPEG image files.',
        'step_1_title': 'Upload PDF',
        'step_1_desc': 'Drag and drop your PDF file into the converter box above or browse from your device.',
        'step_2_title': 'High-Res Extraction',
        'step_2_desc': 'Click Convert to JPG. Our engine renders every page at up to 300 DPI in seconds.',
        'step_3_title': 'Download Images',
        'step_3_desc': 'Download individual high-res JPG images or download all pages bundled in a single ZIP archive.',
        'why_title': 'Why Axom AI PDF to JPG is the Superior Choice',
        'why_subheading': 'Engineered for designers, educators, marketers, and students seeking publication-grade image extraction.',
        'benefit_1_title': '300 DPI Print Clarity',
        'benefit_1_desc': 'Renders vector text, equations, and charts with crystal-clear sharpness and zero blurriness.',
        'benefit_2_title': 'Batch ZIP Packaging',
        'benefit_2_desc': 'Multi-page PDFs are automatically packaged into a high-speed, organized ZIP download.',
        'benefit_3_title': 'Zero Watermarks, 100% Free',
        'benefit_3_desc': 'Your converted JPEG images are 100% clean and watermark-free, ready for client presentations.',
        'benefit_4_title': 'Automatic File Purging',
        'benefit_4_desc': 'Uploaded files are securely rendered in transient memory and deleted permanently right after conversion.',
        'benefit_5_title': 'Universal Device Support',
        'benefit_5_desc': 'Works on Chrome, Safari, and Edge across Android, iOS, Windows, macOS, and Linux.',
        'benefit_6_title': 'Vibrant Color Preservation',
        'benefit_6_desc': 'Supports sRGB and CMYK color profiles, preventing color shifting or washed-out images.',
        'comparison_badge': 'Direct Feature Comparison',
        'comparison_title': 'Axom AI vs. Traditional PDF to JPG Converters',
        'comparison_subheading': 'See why users choose Axom AI over paywalled and ad-heavy alternatives.',
        'comparison_matrix_json': DEFAULT_COMPARISON_ROWS,
        'tech_spec_title': 'Technical Specifications & Supported Standards',
        'tech_spec_inputs': '.pdf (PDF 1.0 - 2.0)',
        'tech_spec_output': 'JPEG / JPG (300 DPI RGB)',
        'tech_spec_max_size': '25 Megabytes (MB)',
        'tech_spec_security': 'TLS 1.3 / SSL 256-bit',
        'faq_section_title': 'Frequently Asked Questions',
        'faq_section_subheading': 'Got questions about converting PDF to JPG? Find verified answers below.',
        'cta_title': 'Extract High-Resolution JPGs from Your PDF',
        'cta_desc': 'Experience fast, private, and watermark-free PDF to JPG conversions trusted across Assam and India.',
        'cta_btn_primary_text': 'Upload PDF File Now',
        'cta_btn_primary_url': '#converter',
        'cta_btn_secondary_text': 'Explore All AI & Document Tools',
        'cta_btn_secondary_url': 'https://aiaxom.co.in/tools',
        'meta_title': 'Free PDF to JPG Converter Online — Extract PDF Pages to JPEG | Axom AI',
        'meta_description': 'Convert PDF pages into high-resolution JPG images online for free in seconds. Extract clear 300 DPI JPEG pictures from any PDF document without watermarks or quality loss.',
        'meta_keywords': 'pdf to jpg converter, convert pdf to jpg, pdf to jpeg converter online, free pdf to jpg converter, extract images from pdf, pdf to jpg online India, high resolution pdf to jpg Assam, pdf to image converter',
        'canonical_url': 'https://aiaxom.co.in/tools/pdf-to-jpg',
        'og_image_url': 'https://aiaxom.co.in/static/dist/hero/assam.avif',
    },
    'pdf-to-png': {
        'tool_name': 'PDF to PNG',
        'hero_badge_text': '⚡ Free: 20 Files / Day • 💎 Lossless Transparency • 👑 Pro Batch Mode',
        'hero_heading_prefix': 'Free',
        'hero_heading_highlight': 'PDF to PNG',
        'hero_heading_suffix': 'Converter Online',
        'hero_description': 'Convert PDF pages into lossless, transparent PNG graphic files. Ideal for illustrations, vector charts, presentations, and UI design work with pixel-perfect edge clarity and zero watermarks.',
        'free_daily_limit': 20,
        'pro_batch_limit': 20,
        'max_file_size_mb': 25,
        'how_it_works_title': 'How to Convert PDF to PNG in 3 Easy Steps',
        'how_it_works_subheading': 'Extract crystal-clear, lossless PNG graphics from your PDF in seconds.',
        'step_1_title': 'Upload PDF',
        'step_1_desc': 'Drag and drop your PDF document into the upload area above or select from your device.',
        'step_2_title': 'Lossless Rendering',
        'step_2_desc': 'Click Convert to PNG. Our engine rasterizes pages with full alpha channel and transparency support.',
        'step_3_title': 'Download PNGs',
        'step_3_desc': 'Save individual lossless PNG images or download all extracted pages in a single ZIP file.',
        'why_title': 'Why Axom AI PDF to PNG is the Superior Choice',
        'why_subheading': 'Preferred by UI/UX designers, developers, academic researchers, and publishers across Assam and India.',
        'benefit_1_title': 'Pixel-Perfect Lossless Quality',
        'benefit_1_desc': 'PNG format prevents JPEG artifacts, ensuring text anti-aliasing and diagrams stay razor sharp.',
        'benefit_2_title': 'Alpha Channel Transparency',
        'benefit_2_desc': 'Maintains transparent backgrounds for vector icons, logos, and charts without ugly white boxes.',
        'benefit_3_title': 'Zero Watermarks, 100% Free',
        'benefit_3_desc': 'No promotional overlays or brand logos stamped on your files. Clean, professional graphic assets.',
        'benefit_4_title': 'Automatic File Purging',
        'benefit_4_desc': 'Your PDF is rendered in transient RAM buffers and purged immediately after download.',
        'benefit_5_title': 'Batch Mode & ZIP Download',
        'benefit_5_desc': 'Convert multi-page PDF documents and download all extracted PNG pages bundled in 1 click.',
        'benefit_6_title': 'Universal Device Support',
        'benefit_6_desc': 'Runs natively in any modern web browser without desktop plugins or software downloads.',
        'comparison_badge': 'Direct Feature Comparison',
        'comparison_title': 'Axom AI vs. Traditional PDF to PNG Converters',
        'comparison_subheading': 'See why users choose Axom AI over paywalled and ad-heavy alternatives.',
        'comparison_matrix_json': DEFAULT_COMPARISON_ROWS,
        'tech_spec_title': 'Technical Specifications & Supported Standards',
        'tech_spec_inputs': '.pdf (PDF 1.0 - 2.0)',
        'tech_spec_output': 'PNG (Lossless 24-bit with Alpha Transparency)',
        'tech_spec_max_size': '25 Megabytes (MB)',
        'tech_spec_security': 'TLS 1.3 / SSL 256-bit',
        'faq_section_title': 'Frequently Asked Questions',
        'faq_section_subheading': 'Got questions about converting PDF to PNG? Find verified answers below.',
        'cta_title': 'Extract Lossless PNG Images from Your PDF',
        'cta_desc': 'Experience fast, private, and watermark-free PDF to PNG conversions trusted across Assam and India.',
        'cta_btn_primary_text': 'Upload PDF File Now',
        'cta_btn_primary_url': '#converter',
        'cta_btn_secondary_text': 'Explore All AI & Document Tools',
        'cta_btn_secondary_url': 'https://aiaxom.co.in/tools',
        'meta_title': 'Free PDF to PNG Converter Online — Lossless PNG Images | Axom AI',
        'meta_description': 'Convert PDF documents into lossless, transparent PNG images online for free. Retain sharp vector text, graphics, and transparency with zero compression artifacts.',
        'meta_keywords': 'pdf to png converter, convert pdf to png, pdf to transparent png, free pdf to png converter online, lossless pdf to image, pdf to png online India, Assam document to png converter',
        'canonical_url': 'https://aiaxom.co.in/tools/pdf-to-png',
        'og_image_url': 'https://aiaxom.co.in/static/dist/hero/assam.avif',
    },
    'image-format-converter': {
        'tool_name': 'Image Format Converter',
        'hero_badge_text': '⚡ Free: 20 Files / Day • 🔄 Supports 15+ Formats • 👑 Pro Batch Mode',
        'hero_heading_prefix': 'Free',
        'hero_heading_highlight': 'Image Format',
        'hero_heading_suffix': 'Converter Online',
        'hero_description': 'Convert between any image formats instantly — WebP to PNG, JFIF to JPG, SVG to PNG, HEIC to JPG, BMP to PNG, and more. Optimized for web developers, designers, and mobile photographers seeking fast, lossless conversions.',
        'free_daily_limit': 20,
        'pro_batch_limit': 20,
        'max_file_size_mb': 25,
        'how_it_works_title': 'How to Convert Image Formats in 3 Easy Steps',
        'how_it_works_subheading': 'Easily change file extensions and encode between 15+ modern and legacy image formats.',
        'step_1_title': 'Upload Any Image',
        'step_1_desc': 'Select your image file (WebP, JFIF, SVG, HEIC, PNG, JPG, BMP, TIFF, AVIF, GIF, ICO) from your device.',
        'step_2_title': 'Choose Target Format',
        'step_2_desc': 'Pick your desired output format — PNG (lossless), JPG (compact), WebP (modern web), or SVG.',
        'step_3_title': 'Download Converted Image',
        'step_3_desc': 'Click Convert Now and download your newly formatted image immediately with zero watermarks.',
        'why_title': 'Why Axom AI Image Format Converter is the Superior Choice',
        'why_subheading': 'Engineered for web developers, designers, photographers, and content creators across Assam and India.',
        'benefit_1_title': '15+ Formats Supported',
        'benefit_1_desc': 'Seamless conversion between WebP, JFIF, SVG, PNG, JPG, HEIC, AVIF, TIFF, BMP, and ICO.',
        'benefit_2_title': 'WebP Web Optimization',
        'benefit_2_desc': 'Reduce website payload by up to 35% with modern WebP compression for superior Core Web Vitals.',
        'benefit_3_title': 'Full Alpha Transparency',
        'benefit_3_desc': 'Preserves transparent backgrounds and vector sharpness when converting to PNG or WebP.',
        'benefit_4_title': 'Zero Watermarks, 100% Free',
        'benefit_4_desc': 'No advertising watermarks, forced signups, or reduced resolution on your output graphics.',
        'benefit_5_title': 'Automatic File Purging',
        'benefit_5_desc': 'Images are converted in isolated transient memory and deleted permanently right after conversion.',
        'benefit_6_title': 'Sub-3-Second Conversion',
        'benefit_6_desc': 'High-performance cloud image processing finishes conversions in less than 3 seconds.',
        'comparison_badge': 'Direct Feature Comparison',
        'comparison_title': 'Axom AI vs. Traditional Image Format Converters',
        'comparison_subheading': 'See why users choose Axom AI over paywalled and ad-heavy alternatives.',
        'comparison_matrix_json': DEFAULT_COMPARISON_ROWS,
        'tech_spec_title': 'Technical Specifications & Supported Standards',
        'tech_spec_inputs': 'JFIF, WebP, SVG, BMP, TIFF, AVIF, HEIC, PNG, JPG, GIF, ICO',
        'tech_spec_output': 'PNG, JPG, WebP, SVG, AVIF, BMP, ICO',
        'tech_spec_max_size': '25 Megabytes (MB)',
        'tech_spec_security': 'TLS 1.3 / SSL 256-bit',
        'faq_section_title': 'Frequently Asked Questions',
        'faq_section_subheading': 'Got questions about changing image formats? Find verified answers below.',
        'cta_title': 'Convert Any Image Format in Seconds',
        'cta_desc': 'Experience fast, private, and watermark-free image format conversions trusted across Assam and India.',
        'cta_btn_primary_text': 'Upload Image Now',
        'cta_btn_primary_url': '#converter',
        'cta_btn_secondary_text': 'Explore All AI & Document Tools',
        'cta_btn_secondary_url': 'https://aiaxom.co.in/tools',
        'meta_title': 'Free Image Format Converter Online — WebP, JFIF, SVG, PNG, JPG | Axom AI',
        'meta_description': 'Convert any image format online for free in seconds. Fast conversion between WebP, JFIF, SVG, PNG, JPG, AVIF, HEIC, and ICO. 100% private, no watermarks.',
        'meta_keywords': 'image format converter, webp to png converter, jfif to jpg converter, heic to jpg converter, svg to png converter, free image converter online India, best image converter Assam, next-gen image converter',
        'canonical_url': 'https://aiaxom.co.in/tools/image-format-converter',
        'og_image_url': 'https://aiaxom.co.in/static/dist/hero/assam.avif',
    },
}

CONVERTER_DEFAULT_FAQS = {
    'word-to-pdf': [
        ('How do I convert Word to PDF online for free?', 'Simply drag and drop or upload your Microsoft Word file (.docx or .doc) into the Axom AI converter box above. You can preview the document immediately. Click "Convert to PDF Now", and within seconds, your high-resolution, fully formatted PDF will be ready to download. No registration, login, or payment is required.', 1),
        ('How many files can I convert for free per day?', 'Free users can convert up to 20 Word documents per day with zero watermarks and full quality preservation. If you need to convert more than 20 files daily or convert multiple files at once, you can upgrade to an Axom AI Premium subscription for unlimited access and Pro Batch Mode.', 2),
        ('Can I convert multiple Word documents at once (Batch Conversion)?', 'Yes! Axom AI Premium subscribers have access to Pro Batch Mode, which allows you to upload and convert up to 20 Word documents simultaneously with a single click. All converted PDFs are automatically packaged into a high-speed ZIP download.', 3),
        ('Will converting Word to PDF alter my original formatting, fonts, or tables?', 'No. Axom AI utilizes advanced layout preservation algorithms that retain your exact font families, text margins, bullet hierarchies, tables, image placements, headers, and footers. The converted PDF looks identical to your original Word document.', 4),
        ('Is it safe to convert sensitive or confidential Word documents on Axom AI?', 'Yes, completely. Security and privacy are foundational to Axom AI. All files are transferred using 256-bit SSL encryption. Documents are processed in isolated, transient memory buffers and are automatically and permanently deleted from our servers right after conversion. We never store, read, or share your document data.', 5),
        ('What Word and document formats are supported?', 'Axom AI supports modern Microsoft Word (.docx), legacy Word (.doc), Rich Text Format (.rtf), OpenDocument Text (.odt), Markdown (.md), and plain text (.txt) files up to 25 MB in size.', 6),
        ('Does Axom AI add any watermark to the converted PDF?', 'No. Unlike other converters that place promotional stamps or watermarks on your files unless you buy a subscription, Axom AI produces 100% clean, watermark-free PDFs suitable for legal, academic, professional, and corporate use.', 7),
        ('Can I convert Word to PDF on my mobile phone (Android or iPhone)?', 'Yes. Axom AI Word to PDF Converter is fully responsive and optimized for mobile browsers including Chrome, Safari, Firefox, and Edge on iOS and Android devices. No app installation is required.', 8),
        ('How does Axom AI compare to Adobe Acrobat or Smallpdf?', 'Axom AI offers generous free daily allowances (20 files/day), lossless typography fidelity, and instant batch conversion for Pro members without annoying ads or complex installation.', 9),
        ('Is Axom AI optimized for students, legal teams, and businesses in Assam and India?', 'Yes! Axom AI is designed with sovereign Indian data privacy principles. It is heavily utilized by students at Gauhati University, Cotton University, and Assam Engineering College, as well as businesses and government exam applicants across Assam and India for quick, watermark-free submissions.', 10),
    ],
    'pdf-to-word': [
        ('How to convert PDF to Word online for free?', 'To convert PDF to Word online for free on Axom AI: 1) Drag and drop or upload your PDF document into the converter box above. 2) Click "Convert to Word Now". 3) Within 2 to 3 seconds, your editable Microsoft Word document (.docx) will be ready for instant download. No account registration, software installation, or credit card is required.', 1),
        ('How can I convert PDF to DOCX without losing formatting?', 'Axom AI uses deep layout analysis algorithms that detect text columns, tables, headers, footers, embedded graphics, and font families. Unlike basic converters that produce disjointed text boxes, Axom AI reconstructs native Microsoft Word elements so your tables stay editable, paragraphs flow naturally, and margins match the original PDF.', 2),
        ('How do I convert a PDF into an editable Word document?', 'Upload your PDF to Axom AI and click convert. The extraction engine processes vector text, structural hierarchy, and tables to produce a standard Office Open XML (.docx) file. You can open and edit this file in Microsoft Word, Google Docs, Apple Pages, LibreOffice, or WPS Office.', 3),
        ('How to convert PDF to Word without installing software?', 'Axom AI operates entirely in the cloud through your web browser. You can convert PDF files to Word on Windows, macOS, Linux, ChromeOS, iOS, or Android without downloading heavy desktop tools, printer drivers, or browser extensions. All document processing occurs securely on high-speed servers.', 4),
        ('How to convert PDF to DOCX without Microsoft Word?', 'You do not need Microsoft Word or Office 365 installed on your computer. Axom AI converts your PDF into a standard .docx file independently in your web browser. Once downloaded, the document can be viewed and edited in free tools like Google Docs, Word for the Web, or LibreOffice.', 5),
        ('Can I convert PDF to Word on mobile (Android and iPhone)?', 'Yes. Axom AI PDF to Word Converter is 100% mobile-friendly. You can open https://aiaxom.co.in/tools/pdf-to-word on Chrome, Safari, or any mobile browser on your Android smartphone, tablet, iPhone, or iPad, upload PDFs from your files or cloud storage, and download editable DOCX files immediately.', 6),
        ('Is PDF to Word conversion free on Axom AI?', 'Yes, Axom AI offers 100% free daily PDF to Word conversion for up to 20 files per day. Free users enjoy full quality layout retention, zero watermarks, and SSL encrypted security. For high-volume business workflows, Axom AI Pro offers unlimited daily conversions and batch conversion for up to 20 files at once.', 7),
        ('Can I convert multiple PDF files to Word online (Batch Mode)?', 'Yes! Axom AI Pro subscribers can enable Pro Batch Mode to upload and convert up to 20 PDF documents at once with a single click. All converted Word documents are compiled and downloaded together in a single convenient ZIP archive.', 8),
        ('Does Axom AI add any watermark to the converted Word document?', 'No. Axom AI never places promotional watermarks, stamps, or branding on your converted DOCX files. Output files are clean, professional, and ready for legal submissions, corporate presentations, academic papers, and official government applications.', 9),
        ('Can I convert scanned PDF documents to editable Word?', 'Yes. For standard PDFs containing digital text, Axom AI extracts and formats text instantly. For image-only or scanned PDFs, Axom AI recognizes text structures and reconstructs readable, editable text blocks and tables so you can edit the content in Microsoft Word.', 10),
        ('How does Axom AI preserve tables, images, and fonts when converting PDF to Word?', 'Axom AI incorporates advanced document geometry recognition. It accurately maps table grids into native Word table cells, retains high-resolution image placements, preserves paragraph alignments, and maps PDF fonts to standard typographic equivalents (Calibri, Arial, Times New Roman, Roboto).', 11),
        ('Is it safe to convert private, legal, or financial PDF documents?', 'Yes, completely safe and confidential. All file transfers are secured with bank-grade 256-bit TLS/SSL encryption. Documents are processed in isolated transient server memory and are automatically and permanently purged right after conversion. Axom AI does not store, inspect, or share your document data.', 12),
        ('Why choose Axom AI over Adobe Acrobat or other online PDF to Word converters?', 'Adobe Acrobat and competitors like Smallpdf or iLovePDF impose restrictive daily caps (1-2 files), mandatory paid subscriptions ($10-$20/month), or force users to register and view ads. Axom AI offers 20 free daily conversions, superior table/layout retention, zero watermarks, and fast sub-3-second processing.', 13),
        ('Is Axom AI optimized for users in Assam and India?', 'Yes. Axom AI is designed in Assam for India, engineered with localized privacy protections, high speed across mobile networks, and compatibility with regional document formats, official exam forms (APSC, UPSC), court affidavits, and university assignments.', 14),
    ],
    'image-to-pdf': [
        ('How to convert image to PDF online for free?', 'To convert images to PDF online for free: 1) Drag and drop or select your JPG, PNG, JPEG, or WebP images in the converter box above. 2) Reorder or arrange your images as needed. 3) Click "Convert to PDF Now". Your crisp, watermark-free PDF will be generated in 2–3 seconds ready for instant download. No account registration or payment is needed.', 1),
        ('How to convert multiple images into one PDF?', 'Axom AI allows you to upload multiple images at once to merge them into a single multi-page PDF document. Each image is placed cleanly on its own page, preserving original dimensions, sharpness, and color profiles without distortion.', 2),
        ('How to convert JPG to PDF without losing quality?', 'Axom AI uses lossless image embedding that retains 100% of your source JPG photo resolution, DPI, and color depth. It embeds the image directly into standard vector-wrapped PDF pages without downscaling or introducing compression artifacts.', 3),
        ('How to convert PNG to PDF with transparent backgrounds?', 'When converting PNG images with alpha channel transparency, Axom AI seamlessly maps the transparent background onto standard clean white PDF canvas pages, ensuring crisp logos, diagrams, and signatures without pixelated black borders.', 4),
        ('How to convert photos to PDF on iPhone and Android?', 'Open https://aiaxom.co.in/tools/image-to-pdf in Safari or Chrome on your mobile device. Tap to choose photos directly from your Camera Roll, Gallery, WhatsApp images, or Files app, and click convert. Your PDF downloads instantly to your mobile storage with zero app installation.', 5),
        ('Does converting images to PDF reduce quality?', 'No. Axom AI preserves the original resolution and quality of your photos. Whether you upload high-resolution camera shots, mobile receipts, or graphic art, each image retains its native sharpness and print-ready quality in the generated PDF.', 6),
        ('How to convert images to PDF without installing software?', 'Axom AI runs 100% in the cloud through any modern web browser. You do not need to install desktop software, Adobe Acrobat, printer drivers, or mobile apps. Everything processes smoothly on Windows, macOS, Android, iOS, and Linux.', 7),
        ('Can I convert WebP images to PDF?', 'Yes. In addition to standard JPG and PNG formats, Axom AI provides native support for modern Google WebP (.webp) image files, converting them directly into standard PDF pages in seconds.', 8),
        ('Is an online image to PDF converter safe and private?', 'Yes, completely safe. Axom AI protects every upload with bank-grade 256-bit TLS/SSL encryption. Uploaded images are processed in isolated transient memory and are automatically and permanently purged from server storage immediately after conversion.', 9),
        ('Does Axom AI add any watermark to the converted PDF?', 'No. Unlike many free converters that stamp promotional watermarks on your documents unless you buy a subscription, Axom AI produces 100% clean, watermark-free PDFs suitable for official, academic, and business submissions.', 10),
        ('Is Axom AI optimized for students, job aspirants, and users in Assam and India?', 'Yes! It is frequently used for government competitive exam uploads (UPSC, APSC, SSC), job applications, PAN/Aadhaar document scans, and university submissions across Assam and India where multiple image pages must be combined into a single lightweight PDF.', 11),
    ],
    'pdf-to-jpg': [
        ('How to convert PDF to JPG online for free?', 'To convert PDF to JPG online for free: 1) Drag and drop or upload your PDF document into the converter box above. 2) Choose whether you want standard or high-resolution extraction. 3) Click "Convert to JPG Now". Within 2–3 seconds, your PDF pages will be extracted as crisp, watermark-free JPG images ready for instant single-image or ZIP archive download. No signup or credit card required.', 1),
        ('How can I convert PDF pages to separate JPG images?', 'Axom AI automatically detects every individual page in your PDF and renders each page into a separate high-resolution JPG image. If your PDF contains 10 pages, you receive 10 individually numbered, crisp JPG images that can be downloaded individually or together as a single ZIP archive.', 2),
        ('How to convert PDF to high-resolution 300 DPI JPG?', 'Axom AI uses a high-fidelity rasterization engine that extracts and renders vector text, embedded photographs, and complex charts at up to 300 DPI print-quality resolution. Text lines remain sharp and legible without blurry pixelation or compression degradation.', 3),
        ('How to convert a multi-page PDF to JPG?', 'Upload your multi-page PDF document to Axom AI and click convert. The engine extracts all pages simultaneously and compiles them into a convenient, structured ZIP file. You can download the entire batch with one click or view and download specific page images.', 4),
        ('How do I convert PDF to JPEG?', 'JPG and JPEG refer to the exact same image format. Converting a PDF to JPEG on Axom AI produces standard .jpg files fully compatible with all operating systems, photo viewers, web browsers, and graphic editing software.', 5),
        ('How to convert PDF to JPG without losing image quality?', 'Axom AI preserves native visual clarity by using lossless color mapping and high DPI raster rendering. Vector lines, fonts, mathematical symbols, and illustrations stay sharp and true to the original PDF.', 6),
        ('How to convert PDF to JPG on mobile (Android and iPhone)?', 'Open https://aiaxom.co.in/tools/pdf-to-jpg in Chrome or Safari on your Android smartphone, iPhone, or iPad. Upload your PDF from your phone files or Google Drive/iCloud, convert in seconds, and save individual JPG photos to your Camera Roll or download the complete ZIP file.', 7),
        ('Does Axom AI add any watermark to the converted JPG images?', 'No. Axom AI never places promotional watermarks, stamps, or logos on your converted images. Converted JPG images are 100% clean, professional, and ready for commercial presentations, printing, and publishing.', 8),
        ('Can I download all converted JPG pages as a single ZIP file?', 'Yes. For any multi-page PDF, Axom AI provides a "Download All as ZIP" button so you can download all extracted page images at once without clicking each image individually.', 9),
        ('Is PDF to JPG conversion safe, private, and encrypted?', 'Yes, completely secure. All file uploads and downloads are protected with bank-grade 256-bit TLS/SSL encryption. Documents are processed in isolated transient memory buffers and are automatically and permanently purged right after conversion.', 10),
        ('Is Axom AI PDF to JPG optimized for India and Assam?', 'Yes. Whether extracting scanned book pages for Assam university syllabus notes or converting tax documents and identity proofs in India, Axom AI provides lightning-fast image extraction without quality degradation.', 11),
    ],
    'pdf-to-png': [
        ('How to convert PDF to PNG online for free?', 'To convert PDF to PNG online for free: 1) Drag and drop or upload your PDF file into the converter box above. 2) Click "Convert to PNG Now". Within 2–3 seconds, each page of your PDF will be extracted as a lossless, high-resolution PNG image with transparency support, ready for single-image or ZIP archive download. No registration or credit card required.', 1),
        ('How do I convert PDF pages to separate PNG images?', 'Axom AI automatically detects every page in your PDF document and renders each page into a separate high-resolution PNG file. A 10-page PDF produces 10 sequentially numbered PNG images that can be downloaded individually or packaged together in a single ZIP archive.', 2),
        ('How to convert PDF to transparent PNG?', 'Axom AI natively preserves alpha channel transparency during conversion. If your PDF pages contain transparent elements, vector graphics, logos, or icons without background fills, they are rendered with a true transparent PNG background, making them ideal for web design and graphic composition.', 3),
        ('How to convert PDF to lossless, pixel-perfect PNG without quality loss?', 'Unlike lossy JPG compression, PNG uses lossless compression. Axom AI renders PDF pages at 300 DPI with pixel-perfect edge rendering. Text outlines, thin lines, mathematical equations, and fine illustrations retain their exact sharpness without compression artifacts.', 4),
        ('How to convert a multi-page PDF to PNG?', 'Simply upload your multi-page PDF into the converter. Axom AI processes all pages simultaneously in parallel and bundles them into an organized ZIP archive. You can click "Download All as ZIP" to download every page image in 1 click.', 5),
        ('How to convert PDF to high-resolution PNG on mobile (Android and iPhone)?', 'Visit https://aiaxom.co.in/tools/pdf-to-png in Safari or Chrome on your iPhone, iPad, or Android phone. Upload your PDF from device storage or cloud drives, convert in 2–3 seconds, and save individual PNG images directly to your Photos/Gallery or download the complete ZIP file.', 6),
        ('Does Axom AI add any watermark to the converted PNG images?', 'No. Axom AI never places promotional watermarks, stamps, or logos on your converted PNG images. Converted images are 100% clean and ready for client presentations, apps, web graphics, and commercial publications.', 7),
        ('What is the difference between PDF to PNG and PDF to JPG?', 'PNG is a lossless format that supports alpha transparency and offers razor-sharp clarity for text, logos, diagrams, and line art without compression blur. JPG is best for photographic content where smaller file sizes are prioritized. Axom AI offers both converters for maximum flexibility.', 8),
        ('Why is PNG ideal for designers, developers, and web graphics?', 'Designers and developers prefer PNG because it preserves crisp text anti-aliasing, sharp vector lines, and transparent backgrounds. Converted PNG assets can be dropped directly into Figma, Photoshop, Canva, website code, or mobile apps without background cleanup.', 9),
        ('Is PDF to PNG conversion safe, private, and encrypted?', 'Yes, completely safe. Security is foundational to Axom AI. All transfers are encrypted with 256-bit TLS/SSL. Documents are rendered in transient isolated RAM buffers and are automatically and permanently purged right after conversion.', 10),
        ('Why choose Axom AI for PNG extraction in India and Assam?', 'Axom AI is Assam and India\'s sovereign document and AI platform, delivering ad-free, high-speed, 100% watermark-free conversions for students, startups, and developers.', 11),
    ],
    'image-format-converter': [
        ('How do I convert image format online for free?', 'Converting image formats on Axom AI is simple, free, and takes under 3 seconds: (1) Drag and drop your image (JPG, PNG, WebP, HEIC, SVG, GIF, BMP, TIFF, JFIF, AVIF) into the upload box above. (2) Select your desired target format — PNG (lossless transparency), JPG (compact size), or WebP (modern web performance). (3) Click "Convert Now" and download your converted, watermark-free image immediately to your device.', 1),
        ('How to convert an image to another format without software?', 'You can convert images directly inside any modern web browser (Google Chrome, Apple Safari, Mozilla Firefox, Microsoft Edge) using Axom AI. Because processing occurs securely in the cloud, you do not need to install heavy desktop software like Photoshop, GIMP, or browser extensions. Works on Windows, macOS, Linux, ChromeOS, iOS, and Android.', 2),
        ('How to change image format online?', 'To change an image format online, upload your source file to Axom AI Image Format Converter, choose a new extension format (such as PNG, JPG, or WebP) from the target dropdown, and click Convert. The tool recodes the image matrix, preserves color profiles and resolution, and outputs the newly formatted file ready for instant download.', 3),
        ('How to convert JPG to PNG with transparency?', 'Upload your JPG or JPEG file to Axom AI Image Format Converter, select "PNG" as the output format, and click Convert. Axom AI will convert the lossy JPG into a lossless 24-bit PNG with full support for alpha transparency and zero compression artifacts. It is ideal for design mockups, logos, and digital graphics.', 4),
        ('How to convert PNG to JPG online?', 'Upload your PNG image, choose "JPG" from the target format menu, and click Convert. Axom AI efficiently compresses the raster data into a lightweight JPEG image while maintaining crisp sharpness and realistic color depth, making it suitable for email attachments, web publishing, and fast photo sharing.', 5),
        ('How to convert JPG to WebP for website optimization?', 'To boost page speed and Core Web Vitals, upload your JPG file and select "WebP" as the target format. WebP offers 25%–35% smaller file sizes than standard JPEGs at equivalent visual quality. Download the converted .webp file and serve it on your website for faster page load times and higher Google PageSpeed scores.', 6),
        ('How to convert PNG to WebP online?', 'Upload your PNG file to the converter and choose "WebP". Axom AI converts both opaque and transparent PNG graphics into lossless or high-fidelity lossy WebP format. This drastically reduces bandwidth without sacrificing transparency, making it the preferred choice for modern web developers and UI designers.', 7),
        ('How to convert WebP to JPG or WebP to PNG?', 'If you downloaded a .webp file from the web and need it in a traditional format, upload the WebP file to Axom AI. Select "JPG" for general photography or "PNG" to preserve transparency and graphic sharpness. Click Convert to receive a universally compatible file that opens in all legacy image viewers and desktop apps.', 8),
        ('How can I convert images online safely and privately?', 'Axom AI ensures complete privacy with end-to-end 256-bit TLS/SSL encryption. Files are processed in isolated transient server buffers and automatically purged immediately after conversion. We do not store, index, sell, or inspect your personal photos or proprietary graphics.', 9),
        ('Can I convert image formats for free with no watermarks?', 'Yes, 100%. Axom AI provides 20 free image conversions per day with zero promotional watermarks, stamps, or degraded resolutions. Converted files are completely clean and ready for commercial, professional, academic, or personal use.', 10),
        ('How to convert HEIC or HEIF photos from an iPhone to JPG?', 'Upload your iPhone .heic or .heif photos directly into Axom AI, select "JPG" as output, and click Convert. Axom AI decodes Apple\'s high-efficiency image container into standard, universally viewable JPEG photos in under 2 seconds.', 11),
        ('Is Axom AI Image Format Converter optimized for India and Assam?', 'Yes. Axom AI is engineered right here in Assam for creators, e-commerce sellers, businesses, and developers across India who need fast, zero-watermark image transcoding with local server speed and complete data confidentiality.', 12),
    ],
}


def ensure_converter_tool_defaults(tool_slug):
    """
    Ensure the ConverterToolConfig and default FAQs exist for the specified tool_slug.
    If tool_slug == 'word-to-pdf' and WordToPdfToolConfig exists, migrates data across.
    """
    config = ConverterToolConfig.objects.filter(tool_slug=tool_slug).first()

    if not config:
        if tool_slug == 'word-to-pdf':
            old_cfg = WordToPdfToolConfig.objects.first()
            if old_cfg:
                config = ConverterToolConfig.objects.create(
                    tool_slug='word-to-pdf',
                    tool_name='Word to PDF',
                    hero_badge_text=old_cfg.hero_badge_text,
                    hero_heading_prefix=old_cfg.hero_heading_prefix,
                    hero_heading_highlight=old_cfg.hero_heading_highlight,
                    hero_heading_suffix=old_cfg.hero_heading_suffix,
                    hero_description=old_cfg.hero_description,
                    free_daily_limit=old_cfg.free_daily_limit,
                    pro_batch_limit=old_cfg.pro_batch_limit,
                    max_file_size_mb=old_cfg.max_file_size_mb,
                    how_it_works_title=old_cfg.how_it_works_title,
                    how_it_works_subheading=old_cfg.how_it_works_subheading,
                    step_1_title=old_cfg.step_1_title,
                    step_1_desc=old_cfg.step_1_desc,
                    step_2_title=old_cfg.step_2_title,
                    step_2_desc=old_cfg.step_2_desc,
                    step_3_title=old_cfg.step_3_title,
                    step_3_desc=old_cfg.step_3_desc,
                    why_title=old_cfg.why_title,
                    why_subheading=old_cfg.why_subheading,
                    benefit_1_title=old_cfg.benefit_1_title,
                    benefit_1_desc=old_cfg.benefit_1_desc,
                    benefit_2_title=old_cfg.benefit_2_title,
                    benefit_2_desc=old_cfg.benefit_2_desc,
                    benefit_3_title=old_cfg.benefit_3_title,
                    benefit_3_desc=old_cfg.benefit_3_desc,
                    benefit_4_title=old_cfg.benefit_4_title,
                    benefit_4_desc=old_cfg.benefit_4_desc,
                    benefit_5_title=old_cfg.benefit_5_title,
                    benefit_5_desc=old_cfg.benefit_5_desc,
                    benefit_6_title=old_cfg.benefit_6_title,
                    benefit_6_desc=old_cfg.benefit_6_desc,
                    comparison_badge=old_cfg.comparison_badge,
                    comparison_title=old_cfg.comparison_title,
                    comparison_subheading=old_cfg.comparison_subheading,
                    comparison_matrix_json=old_cfg.comparison_matrix_json,
                    tech_spec_title=old_cfg.tech_spec_title,
                    tech_spec_inputs=old_cfg.tech_spec_inputs,
                    tech_spec_output=old_cfg.tech_spec_output,
                    tech_spec_max_size=old_cfg.tech_spec_max_size,
                    tech_spec_security=old_cfg.tech_spec_security,
                    faq_section_title=old_cfg.faq_section_title,
                    faq_section_subheading=old_cfg.faq_section_subheading,
                    cta_title=old_cfg.cta_title,
                    cta_desc=old_cfg.cta_desc,
                    cta_btn_primary_text=old_cfg.cta_btn_primary_text,
                    cta_btn_primary_url=old_cfg.cta_btn_primary_url,
                    cta_btn_secondary_text=old_cfg.cta_btn_secondary_text,
                    cta_btn_secondary_url=old_cfg.cta_btn_secondary_url,
                    meta_title=old_cfg.meta_title,
                    meta_description=old_cfg.meta_description,
                    meta_keywords=old_cfg.meta_keywords,
                    canonical_url=old_cfg.canonical_url,
                    og_image_url=old_cfg.og_image_url,
                )
                for f in WordToPdfFAQ.objects.filter(tool_config=old_cfg):
                    ConverterToolFAQ.objects.create(
                        tool_config=config,
                        question=f.question,
                        answer=f.answer,
                        order=f.order,
                        is_active=f.is_active,
                    )
                return config

        defaults = CONVERTER_TOOLS_DEFAULTS.get(tool_slug, {})
        config = ConverterToolConfig.objects.create(
            tool_slug=tool_slug,
            **defaults
        )

    # Ensure FAQs exist
    if ConverterToolFAQ.objects.filter(tool_config=config).count() == 0:
        faq_list = CONVERTER_DEFAULT_FAQS.get(tool_slug, [])
        for q, a, order in faq_list:
            ConverterToolFAQ.objects.create(
                tool_config=config,
                question=q,
                answer=a,
                order=order,
                is_active=True,
            )

    return config
