from django.urls import path
from django.views.generic import RedirectView
from . import views

app_name = 'contentcms'

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('hero/', views.hero_editor, name='hero_editor'),
    path('hero/save/', views.save_hero_api, name='save_hero_api'),
    path('logos/save/', views.save_logo_api, name='save_logo_api'),
    path('logos/delete/<int:logo_id>/', views.delete_logo_api, name='delete_logo_api'),
    path('banner/save/', views.save_banner_api, name='save_banner_api'),
    path('articles/', views.articles_page, name='articles_page'),
    path('articles/header/save/', views.save_insights_header_api, name='save_insights_header_api'),
    path('articles/upload-image/', views.upload_article_image_api, name='upload_article_image_api'),
    path('articles/new/', views.article_edit_page, name='article_new'),
    path('articles/edit/<int:article_id>/', views.article_edit_page, name='article_edit'),
    path('articles/save/', views.save_article_api, name='save_article_api'),
    path('articles/delete/<int:article_id>/', views.delete_article_api, name='delete_article_api'),
    path('articles/toggle/<int:article_id>/', views.toggle_article_status_api, name='toggle_article_status_api'),
    path('explore/', views.features_page, name='explore_page'),
    path('explore/header/save/', views.save_explore_header_api, name='save_explore_header_api'),
    path('explore/save/', views.save_feature_api, name='save_feature_api'),
    path('explore/delete/<int:feature_id>/', views.delete_feature_api, name='delete_feature_api'),
    path('features/', RedirectView.as_view(url='/axomai-content/explore/', permanent=True)),
    path('usecases/', views.usecases_page, name='usecases_page'),
    path('usecases/header/save/', views.save_usecases_header_api, name='save_usecases_header_api'),
    path('usecases/save/', views.save_usecase_api, name='save_usecase_api'),
    path('usecases/delete/<int:usecase_id>/', views.delete_usecase_api, name='delete_usecase_api'),
    path('testimonials/', views.testimonials_page, name='testimonials_page'),
    path('testimonials/header/save/', views.save_testimonials_header_api, name='save_testimonials_header_api'),
    path('testimonials-faqs/', RedirectView.as_view(url='/axomai-content/testimonials/', permanent=True)),
    path('testimonials/save/', views.save_testimonial_api, name='save_testimonial_api'),
    path('testimonials/delete/<int:testimonial_id>/', views.delete_testimonial_api, name='delete_testimonial_api'),
    path('pricing/', views.pricing_page, name='pricing_page'),
    path('pricing/header/save/', views.save_pricing_header_api, name='save_pricing_header_api'),
    path('pricing/save/', views.save_pricing_plan_api, name='save_pricing_plan_api'),
    path('pricing/toggle/<int:plan_id>/', views.toggle_pricing_plan_api, name='toggle_pricing_plan_api'),
    path('pricing/delete/<int:plan_id>/', views.delete_pricing_plan_api, name='delete_pricing_plan_api'),
    
    # Standalone Pages: About Us Page Manager
    path('pages/about/', views.about_editor, name='about_editor'),
    path('pages/about/save/', views.save_about_page_api, name='save_about_page_api'),

    # Standalone Pages: FAQ Page Manager
    path('pages/faq/', views.faq_manager_page, name='faq_manager_page'),
    path('pages/faq/config/save/', views.save_faq_page_config_api, name='save_faq_page_config_api'),
    path('pages/faq/save/', views.save_faq_item_api, name='save_faq_item_api'),
    path('pages/faq/delete/<int:faq_id>/', views.delete_faq_item_api, name='delete_faq_item_api'),
    path('pages/faq/toggle-homepage/<int:faq_id>/', views.toggle_faq_homepage_api, name='toggle_faq_homepage_api'),
    path('pages/faq/toggle-status/<int:faq_id>/', views.toggle_faq_status_api, name='toggle_faq_status_api'),
    path('faqs/save/', views.save_faq_api, name='save_faq_api'),
    path('faqs/delete/<int:faq_id>/', views.delete_faq_api, name='delete_faq_api'),
    path('seo/', views.seo_page, name='seo_page'),
    path('seo/save/', views.save_seo_api, name='save_seo_api'),
    # Header Settings
    path('settings/header/', views.header_settings_page, name='header_settings_page'),
    path('settings/header/save/', views.save_header_settings_api, name='save_header_settings_api'),
    path('settings/header/upload-logo/', views.upload_brand_logo_api, name='upload_brand_logo_api'),
    path('settings/header/nav/save/', views.save_header_nav_item_api, name='save_header_nav_item_api'),
    path('settings/header/nav/delete/<int:item_id>/', views.delete_header_nav_item_api, name='delete_header_nav_item_api'),
    path('settings/header/nav/toggle/<int:item_id>/', views.toggle_header_nav_item_api, name='toggle_header_nav_item_api'),
    path('settings/header/mega/save/', views.save_mega_menu_item_api, name='save_mega_menu_item_api'),
    path('settings/header/mega/delete/<int:item_id>/', views.delete_mega_menu_item_api, name='delete_mega_menu_item_api'),
    path('settings/header/mega/toggle/<int:item_id>/', views.toggle_mega_menu_item_api, name='toggle_mega_menu_item_api'),
    # Footer Settings
    path('settings/footer/', views.footer_settings_page, name='footer_settings_page'),
    path('settings/footer/save/', views.save_footer_settings_api, name='save_footer_settings_api'),
    path('settings/footer/column/save/', views.save_footer_column_api, name='save_footer_column_api'),
    path('settings/footer/column/delete/<int:column_id>/', views.delete_footer_column_api, name='delete_footer_column_api'),
    path('settings/footer/link/save/', views.save_footer_link_api, name='save_footer_link_api'),
    path('settings/footer/link/delete/<int:link_id>/', views.delete_footer_link_api, name='delete_footer_link_api'),
    path('settings/footer/link/toggle/<int:link_id>/', views.toggle_footer_link_api, name='toggle_footer_link_api'),
    path('settings/footer/social/save/', views.save_footer_social_api, name='save_footer_social_api'),
    path('settings/footer/social/delete/<int:social_id>/', views.delete_footer_social_api, name='delete_footer_social_api'),
    path('settings/footer/social/toggle/<int:social_id>/', views.toggle_footer_social_api, name='toggle_footer_social_api'),
]
