import React from 'react';
import type { Metadata } from 'next';
import Navbar from '../../components/Navbar';
import Footer from '../../components/Footer';
import TermsInteractiveContent from '../../components/TermsInteractiveContent';
import { TERMS_METADATA, TERMS_FAQS } from '../../components/termsData';
import { getLandingCMS, getTermsCMS, TermsCMSData } from '../../lib/api';
import {
  Scale,
  Calendar,
  CheckCircle2,
  FileCheck2,
} from 'lucide-react';

export const dynamic = 'force-dynamic';
export const revalidate = 0;

const DEFAULT_KEYWORDS = [
  'Axom AI Terms of Service',
  'Axom AI terms',
  'Axom AI terms and conditions',
  'Axom AI terms of use',
  'Axom AI user agreement',
  'Axom AI service terms',
  'Axom AI commercial rights',
  'Axom AI content ownership',
  'AI platform terms of service',
  'AI chatbot terms of service',
  'What are the Terms of Service for Axom AI',
  'Can I use Axom AI for commercial purposes',
  'Who owns content generated by Axom AI',
  'AI-generated content ownership',
  'Information Technology Act 2000 compliant AI',
  'DPDP Act 2023 compliant terms',
  'Axom AI legal terms India',
  'Assam AI terms of service'
];

export async function generateMetadata(): Promise<Metadata> {
  const termsData = await getTermsCMS().catch(() => null);
  const config = termsData?.config;

  const title = config?.meta_title || 'Axom AI Terms of Service — User Agreement, Commercial Rights & IP Policy';
  const description =
    config?.meta_description ||
    'Axom AI Terms of Service: Understand our usage rules, commercial exploitation rights, AI output ownership, liability disclaimers, and subscription terms under Indian law.';
  const keywordsStr = config?.meta_keywords || DEFAULT_KEYWORDS.join(', ');
  const keywords = keywordsStr.split(',').map((k) => k.trim()).filter(Boolean);
  const ogImage = config?.og_image || 'https://aiaxom.co.in/static/dist/hero/assam.avif';

  return {
    title,
    description,
    keywords,
    alternates: {
      canonical: 'https://aiaxom.co.in/terms/',
    },
    openGraph: {
      title,
      description,
      url: 'https://aiaxom.co.in/terms/',
      siteName: 'Axom AI',
      locale: 'en_IN',
      images: [
        {
          url: ogImage,
          width: 1200,
          height: 630,
          alt: 'Axom AI Terms of Service and User Agreement',
        },
      ],
      type: 'website',
    },
    twitter: {
      card: 'summary_large_image',
      title,
      description,
      images: [ogImage],
    },
  };
}

export default async function TermsPage() {
  const [landingData, termsData] = await Promise.all([
    getLandingCMS().catch(() => null),
    getTermsCMS().catch(() => null),
  ]);

  const cfg = termsData?.config;

  const pageTitle = cfg?.hero_title_highlight
    ? `${cfg.hero_title_prefix || 'Axom AI'} ${cfg.hero_title_highlight}`
    : 'Axom AI Terms of Service';
  const pageDesc = cfg?.hero_subheading || 'Transparent, accountable, and legally grounded terms governing access, commercial exploitation rights, intellectual property ownership, and acceptable use.';
  const lastUpdated = cfg?.last_updated_date || TERMS_METADATA.lastUpdated;
  const version = cfg?.version_text || TERMS_METADATA.version;
  const jurisdiction = cfg?.jurisdiction_text || 'Guwahati, Assam (India)';

  const faqsList = termsData?.faqs && termsData.faqs.length > 0
    ? termsData.faqs
    : TERMS_FAQS;

  // Schema 1: WebPage / Terms of Service Schema
  const termsPageSchema = {
    '@context': 'https://schema.org',
    '@type': 'WebPage',
    name: cfg?.meta_title || 'Axom AI Terms of Service — User Agreement, Commercial Rights & IP Policy',
    url: 'https://aiaxom.co.in/terms/',
    description:
      cfg?.meta_description ||
      'Official Terms of Service governing access, commercial rights, intellectual property ownership, and acceptable use for Axom AI.',
    datePublished: '2025-01-01',
    dateModified: lastUpdated,
    inLanguage: ['en-IN', 'as-IN'],
    about: {
      '@type': 'Thing',
      name: 'Terms of Service and Commercial User Agreement',
      description:
        'Legal terms covering AI output ownership, commercial exploitation rights, acceptable use, billing, and governing jurisdiction in Guwahati, Assam.',
    },
    publisher: {
      '@type': 'Organization',
      name: 'Axom AI',
      alternateName: ['AI Axom', 'অসম এআই'],
      url: 'https://aiaxom.co.in',
      logo: 'https://aiaxom.co.in/axom-brand-logo.png',
      email: cfg?.legal_email || 'support@aiaxom.co.in',
      address: {
        '@type': 'PostalAddress',
        addressLocality: 'Guwahati',
        addressRegion: 'Assam',
        postalCode: '781001',
        addressCountry: 'IN',
      },
    },
  };

  // Schema 2: Organization Entity with Legal Contact Point
  const organizationSchema = {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Axom AI',
    alternateName: ['AI Axom', 'অসম এআই', 'Assam AI'],
    url: 'https://aiaxom.co.in',
    logo: 'https://aiaxom.co.in/axom-brand-logo.png',
    email: cfg?.legal_email || 'support@aiaxom.co.in',
    founder: {
      '@type': 'Person',
      name: 'Samarjit Kashyap',
      jobTitle: 'Founder & Lead Engineer',
      email: 'samarjitkashyp@gmail.com',
    },
    address: {
      '@type': 'PostalAddress',
      addressLocality: 'Guwahati',
      addressRegion: 'Assam',
      postalCode: '781001',
      addressCountry: 'IN',
    },
    contactPoint: {
      '@type': 'ContactPoint',
      contactType: 'legal and commercial terms desk',
      email: cfg?.legal_email || 'support@aiaxom.co.in',
      availableLanguage: ['English', 'Assamese', 'Hindi'],
    },
  };

  // Schema 3: FAQPage Schema for Terms Q&As
  const faqSchema = {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: faqsList.map((faq) => ({
      '@type': 'Question',
      name: faq.question,
      acceptedAnswer: {
        '@type': 'Answer',
        text: faq.answer,
      },
    })),
  };

  // Schema 4: BreadcrumbList
  const breadcrumbSchema = {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: [
      {
        '@type': 'ListItem',
        position: 1,
        name: 'Home',
        item: 'https://aiaxom.co.in/',
      },
      {
        '@type': 'ListItem',
        position: 2,
        name: 'Terms of Service',
        item: 'https://aiaxom.co.in/terms/',
      },
    ],
  };

  return (
    <>
      {/* Schema.org Injections */}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(termsPageSchema) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(organizationSchema) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbSchema) }}
      />

      <Navbar header={landingData?.header} />

      <main className="min-h-screen bg-[#f0fdf4] dark:bg-[#0b1220] text-slate-800 dark:text-slate-200 relative overflow-hidden pt-28 pb-20">
        {/* Ambient Gradient Glows (Matching use-cases) */}
        <div className="absolute top-0 left-1/2 -translate-x-1/2 w-full max-w-7xl h-[650px] pointer-events-none z-0">
          <div className="absolute top-10 left-1/4 w-[28rem] h-[28rem] bg-fuchsia-600/15 rounded-full blur-[140px]" />
          <div className="absolute top-20 right-1/4 w-[28rem] h-[28rem] bg-purple-600/15 rounded-full blur-[140px]" />
        </div>

        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
          {/* Header Section */}
          <div className="text-center max-w-4xl mx-auto mb-14 sm:mb-16">
            <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-gradient-to-r from-fuchsia-500/15 via-purple-500/10 to-indigo-500/15 border border-fuchsia-500/30 text-fuchsia-700 dark:text-fuchsia-300 text-xs font-semibold mb-5 shadow-sm">
              <Scale className="w-3.5 h-3.5 text-fuchsia-700 dark:text-fuchsia-400" />
              <span>{cfg?.hero_badge || 'Information Technology Act 2000 & DPDP Act 2023 Compliant'}</span>
            </div>
            <h1 className="text-3xl sm:text-4xl md:text-5xl lg:text-6xl font-black text-emerald-950 dark:text-white tracking-tight leading-tight mb-5">
              {cfg?.hero_title_prefix ? `${cfg.hero_title_prefix} ` : 'Axom AI '}
              <span className="bg-gradient-to-r from-fuchsia-600 dark:from-fuchsia-400 via-purple-600 dark:via-purple-300 to-indigo-600 dark:to-indigo-300 bg-clip-text text-transparent">
                {cfg?.hero_title_highlight || 'Terms of Service'}
              </span>
            </h1>
            <p className="text-base sm:text-lg text-slate-700 dark:text-slate-300 leading-relaxed max-w-3xl mx-auto mb-6">
              {pageDesc}
            </p>
            <div className="flex flex-wrap items-center justify-center gap-4 text-xs sm:text-sm text-slate-600 dark:text-slate-400">
              <span className="inline-flex items-center gap-1.5">
                <Calendar className="w-3.5 h-3.5 text-fuchsia-700 dark:text-fuchsia-400" />
                Last Updated: <strong className="text-slate-800 dark:text-slate-200">{lastUpdated}</strong>
              </span>
              <span>&bull;</span>
              <span>
                Version: <strong className="text-slate-800 dark:text-slate-200 font-mono">{version}</strong>
              </span>
              <span>&bull;</span>
              <span>
                Jurisdiction: <strong className="text-slate-800 dark:text-slate-200">{jurisdiction}</strong>
              </span>
            </div>
          </div>

          {/* AEO Direct Answer Summary Box (Engineered for Google SGE, Perplexity, ChatGPT & Claude) */}
          <section
            aria-label="Direct Terms Summary for AI Search Engines"
            className="mb-16 p-6 sm:p-8 rounded-3xl bg-gradient-to-r from-purple-100/40 dark:from-purple-950/40 via-white/60 dark:via-slate-900/60 to-indigo-100/40 dark:to-indigo-950/40 border border-purple-500/25 shadow-2xl relative overflow-hidden group"
          >
            <div className="absolute top-0 right-0 w-64 h-64 bg-purple-500/10 rounded-full blur-3xl pointer-events-none" />
            <div className="flex items-start gap-4 sm:gap-5 relative z-10">
              <div className="w-12 h-12 rounded-2xl bg-purple-500/20 border border-purple-500/30 flex items-center justify-center text-purple-700 dark:text-purple-300 shrink-0 mt-0.5 shadow-inner">
                <FileCheck2 className="w-6 h-6 text-fuchsia-700 dark:text-fuchsia-400" />
              </div>
              <div className="space-y-2.5">
                <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-purple-500/15 border border-purple-500/30 text-purple-700 dark:text-purple-300 text-xs font-semibold">
                  <span>{cfg?.aeo_box_badge || 'AEO Direct Summary • Axom AI User Agreement Overview'}</span>
                </div>
                <h2 className="text-xl sm:text-2xl font-bold text-emerald-950 dark:text-white tracking-tight">
                  {cfg?.aeo_box_title || 'What are the Terms of Service for Axom AI?'}
                </h2>
                <p className="text-sm sm:text-base text-slate-700 dark:text-slate-300 leading-relaxed">
                  {cfg?.aeo_box_content || (
                    <>
                      <strong>Axom AI&apos;s Terms of Service</strong> establish a binding user agreement under Indian law. Key highlights include: <strong className="text-emerald-950 dark:text-white">you own your prompts and generated outputs</strong>, and subscribers on paid tiers enjoy <strong className="text-fuchsia-700 dark:text-fuchsia-300">full commercial exploitation rights</strong> with zero royalty obligations. We do <strong className="text-emerald-950 dark:text-white">not train public foundation models on private user data</strong>. The platform is provided on an &quot;as is&quot; basis with standard disclaimers regarding AI hallucinations and non-professional advice. All disputes are subject to the exclusive jurisdiction of the competent courts of <strong className="text-emerald-950 dark:text-white">Guwahati, Assam, India</strong>.
                    </>
                  )}
                </p>
                <div className="pt-2 flex flex-wrap items-center gap-4 text-xs sm:text-sm text-slate-600 dark:text-slate-400">
                  <span className="flex items-center gap-1.5 text-emerald-700 dark:text-emerald-400 font-medium">
                    <CheckCircle2 size={16} /> Commercial Use Permitted (Paid Tiers)
                  </span>
                  <span className="flex items-center gap-1.5 text-emerald-700 dark:text-emerald-400 font-medium">
                    <CheckCircle2 size={16} /> 100% User Output Ownership
                  </span>
                  <span className="flex items-center gap-1.5 text-emerald-700 dark:text-emerald-400 font-medium">
                    <CheckCircle2 size={16} /> Indian IT Act 2000 & DPDP Compliant
                  </span>
                </div>
              </div>
            </div>
          </section>

          {/* Interactive Terms Content */}
          <TermsInteractiveContent cmsData={termsData} />
        </div>
      </main>

      <Footer footer={landingData?.footer} />
    </>
  );
}
