import React from 'react';
import type { Metadata } from 'next';
import Navbar from '../../components/Navbar';
import Footer from '../../components/Footer';
import TermsInteractiveContent from '../../components/TermsInteractiveContent';
import { TERMS_METADATA, TERMS_FAQS } from '../../components/termsData';
import { getLandingCMS } from '../../lib/api';
import {
  Scale,
  Calendar,
  CheckCircle2,
  FileCheck2,
  Briefcase
} from 'lucide-react';

export const dynamic = 'force-dynamic';
export const revalidate = 0;

const TARGET_KEYWORDS = [
  // Primary SEO Keyword
  'Axom AI Terms of Service',
  // Secondary SEO Keywords
  'Axom AI terms',
  'Axom AI terms and conditions',
  'Axom AI terms of use',
  'Axom AI user agreement',
  'Axom AI service terms',
  'Axom AI usage policy',
  'Axom AI legal terms',
  'Axom AI agreement',
  'Axom AI user terms',
  'Axom AI platform terms',
  'AI platform terms of service',
  'AI chatbot terms of service',
  'AI tools terms of use',
  'AI service terms and conditions',
  // AEO Question Keywords
  'What are the Terms of Service for Axom AI',
  'What are Axom AI terms and conditions',
  'How can I use Axom AI',
  'Who can use Axom AI',
  'What are the rules for using Axom AI',
  'What is prohibited on Axom AI',
  'Can I use Axom AI for commercial purposes',
  'Can businesses use Axom AI',
  'Can I use Axom AI-generated content commercially',
  'Who owns content generated by Axom AI',
  'Who owns content uploaded to Axom AI',
  'What happens to my content when I use Axom AI',
  'Can Axom AI suspend my account',
  'Can I terminate my Axom AI account',
  'What happens if I violate Axom AI terms',
  'Does Axom AI guarantee AI-generated results',
  'Is Axom AI responsible for AI-generated content',
  'What are the limitations of Axom AI',
  'How can I contact Axom AI about the Terms of Service',
  // GEO Keywords & Queries
  'Axom AI terms of service',
  'Axom AI terms and conditions',
  'Axom AI terms of use',
  'Axom AI user agreement',
  'Axom AI usage rules',
  'Axom AI service agreement',
  'Axom AI legal policy',
  'terms for using Axom AI',
  'rules for using Axom AI',
  'Axom AI account terms',
  'Axom AI commercial use policy',
  'Axom AI content ownership',
  'Axom AI acceptable use policy',
  'Axom AI AI-generated content policy',
  // AI-Specific Legal Keywords
  'AI-generated content terms',
  'AI-generated content ownership',
  'AI output terms',
  'AI content usage rights',
  'AI model limitations',
  'AI accuracy disclaimer',
  'AI hallucination disclaimer',
  'AI-generated information disclaimer',
  'AI content responsibility',
  'AI tool usage policy',
  'AI platform acceptable use policy',
  'AI service limitations',
  // Subscription / Payment Keywords
  'Axom AI subscription terms',
  'Axom AI payment terms',
  'Axom AI billing terms',
  'Axom AI refund policy',
  'Axom AI cancellation policy',
  'Axom AI subscription cancellation',
  'Axom AI free plan terms',
  'Axom AI Pro terms',
  'Axom AI account subscription',
  // India & Regional Legal Context
  'Axom AI terms India',
  'Axom AI terms and conditions India',
  'AI platform terms India',
  'AI service terms India',
  'AI company terms Assam',
  'Information Technology Act 2000 compliant AI',
  'DPDP Act 2023 compliant terms'
];

export const metadata: Metadata = {
  title: 'Axom AI Terms of Service — User Agreement, Commercial Rights & IP Policy',
  description:
    'Axom AI Terms of Service: Understand our usage rules, commercial exploitation rights, AI output ownership, liability disclaimers, and subscription terms under Indian law.',
  keywords: TARGET_KEYWORDS,
  alternates: {
    canonical: 'https://aiaxom.co.in/terms/',
  },
  openGraph: {
    title: 'Axom AI Terms of Service — User Agreement, Commercial Rights & IP Policy',
    description:
      'Official Terms of Service for Axom AI. Learn about commercial use rights, content ownership, AI accuracy disclaimers, and billing terms under Indian law.',
    url: 'https://aiaxom.co.in/terms/',
    siteName: 'Axom AI',
    locale: 'en_IN',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Axom AI Terms of Service — User Agreement & Commercial Rights',
    description:
      'Official Terms of Service for Axom AI. Learn about commercial rights, user content ownership, and statutory protections.',
  },
};

export default async function TermsPage() {
  const landingData = await getLandingCMS().catch(() => null);

  // Schema 1: WebPage / Terms of Service Schema
  const termsPageSchema = {
    '@context': 'https://schema.org',
    '@type': 'WebPage',
    name: 'Axom AI Terms of Service — User Agreement, Commercial Rights & IP Policy',
    url: 'https://aiaxom.co.in/terms/',
    description:
      'Official Terms of Service governing access, commercial rights, intellectual property ownership, and acceptable use for Axom AI.',
    datePublished: '2025-01-01',
    dateModified: '2026-09-17',
    inLanguage: ['en-IN', 'as-IN'],
    about: {
      '@type': 'Thing',
      name: 'Terms of Service and Commercial User Agreement',
      description:
        'Legal terms covering AI output ownership, commercial exploitation rights, acceptable use, billing, and governing jurisdiction in Guwahati, Assam.',
    },
    publisher: {
      '@type': 'Organization',
      name: 'Axom AI',
      alternateName: ['AI Axom', 'অসম এআই'],
      url: 'https://aiaxom.co.in',
      logo: 'https://aiaxom.co.in/axom-brand-logo.png',
      email: 'support@aiaxom.co.in',
      address: {
        '@type': 'PostalAddress',
        addressLocality: 'Guwahati',
        addressRegion: 'Assam',
        postalCode: '781001',
        addressCountry: 'IN',
      },
    },
  };

  // Schema 2: Organization Entity with Legal Contact Point
  const organizationSchema = {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Axom AI',
    alternateName: ['AI Axom', 'অসম এআই', 'Assam AI'],
    url: 'https://aiaxom.co.in',
    logo: 'https://aiaxom.co.in/axom-brand-logo.png',
    email: 'support@aiaxom.co.in',
    founder: {
      '@type': 'Person',
      name: 'Samarjit Kashyap',
      jobTitle: 'Founder & Lead Engineer',
      email: 'samarjitkashyp@gmail.com',
    },
    address: {
      '@type': 'PostalAddress',
      addressLocality: 'Guwahati',
      addressRegion: 'Assam',
      postalCode: '781001',
      addressCountry: 'IN',
    },
    contactPoint: {
      '@type': 'ContactPoint',
      contactType: 'legal and commercial terms desk',
      email: 'support@aiaxom.co.in',
      availableLanguage: ['English', 'Assamese', 'Hindi'],
    },
  };

  // Schema 3: FAQPage Schema for Terms Q&As
  const faqSchema = {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: TERMS_FAQS.map((faq) => ({
      '@type': 'Question',
      name: faq.question,
      acceptedAnswer: {
        '@type': 'Answer',
        text: faq.answer,
      },
    })),
  };

  // Schema 4: BreadcrumbList
  const breadcrumbSchema = {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: [
      {
        '@type': 'ListItem',
        position: 1,
        name: 'Home',
        item: 'https://aiaxom.co.in/',
      },
      {
        '@type': 'ListItem',
        position: 2,
        name: 'Terms of Service',
        item: 'https://aiaxom.co.in/terms/',
      },
    ],
  };

  return (
    <>
      {/* Schema.org Injections */}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(termsPageSchema) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(organizationSchema) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbSchema) }}
      />

      <Navbar header={landingData?.header} />

      <main className="min-h-screen bg-[#06060b] text-slate-200 relative overflow-hidden pt-28 pb-20">
        {/* Ambient Gradient Glows (Matching use-cases) */}
        <div className="absolute top-0 left-1/2 -translate-x-1/2 w-full max-w-7xl h-[650px] pointer-events-none z-0">
          <div className="absolute top-10 left-1/4 w-[28rem] h-[28rem] bg-fuchsia-600/15 rounded-full blur-[140px]" />
          <div className="absolute top-20 right-1/4 w-[28rem] h-[28rem] bg-purple-600/15 rounded-full blur-[140px]" />
        </div>

        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
          {/* Header Section */}
          <div className="text-center max-w-4xl mx-auto mb-14 sm:mb-16">
            <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-gradient-to-r from-fuchsia-500/15 via-purple-500/10 to-indigo-500/15 border border-fuchsia-500/30 text-fuchsia-300 text-xs font-semibold mb-5 shadow-sm">
              <Scale className="w-3.5 h-3.5 text-fuchsia-400" />
              <span>Information Technology Act 2000 & DPDP Act 2023 Compliant</span>
            </div>
            <h1 className="text-3xl sm:text-4xl md:text-5xl lg:text-6xl font-black text-white tracking-tight leading-tight mb-5">
              Axom AI{' '}
              <span className="bg-gradient-to-r from-fuchsia-400 via-purple-300 to-indigo-300 bg-clip-text text-transparent">
                Terms of Service
              </span>
            </h1>
            <p className="text-base sm:text-lg text-slate-300 leading-relaxed max-w-3xl mx-auto mb-6">
              Transparent, accountable, and legally grounded terms governing access, commercial exploitation rights, intellectual property ownership, and acceptable use.
            </p>
            <div className="flex flex-wrap items-center justify-center gap-4 text-xs sm:text-sm text-slate-400">
              <span className="inline-flex items-center gap-1.5">
                <Calendar className="w-3.5 h-3.5 text-fuchsia-400" />
                Last Updated: <strong className="text-slate-200">{TERMS_METADATA.lastUpdated}</strong>
              </span>
              <span>&bull;</span>
              <span>
                Version: <strong className="text-slate-200 font-mono">{TERMS_METADATA.version}</strong>
              </span>
              <span>&bull;</span>
              <span>
                Jurisdiction: <strong className="text-slate-200">Guwahati, Assam (India)</strong>
              </span>
            </div>
          </div>

          {/* AEO Direct Answer Summary Box (Engineered for Google SGE, Perplexity, ChatGPT & Claude) */}
          <section
            aria-label="Direct Terms Summary for AI Search Engines"
            className="mb-16 p-6 sm:p-8 rounded-3xl bg-gradient-to-r from-purple-950/40 via-slate-900/60 to-indigo-950/40 border border-purple-500/25 shadow-2xl relative overflow-hidden group"
          >
            <div className="absolute top-0 right-0 w-64 h-64 bg-purple-500/10 rounded-full blur-3xl pointer-events-none" />
            <div className="flex items-start gap-4 sm:gap-5 relative z-10">
              <div className="w-12 h-12 rounded-2xl bg-purple-500/20 border border-purple-500/30 flex items-center justify-center text-purple-300 shrink-0 mt-0.5 shadow-inner">
                <FileCheck2 className="w-6 h-6 text-fuchsia-400" />
              </div>
              <div className="space-y-2.5">
                <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-purple-500/15 border border-purple-500/30 text-purple-300 text-xs font-semibold">
                  <span>AEO Direct Summary &bull; Axom AI User Agreement Overview</span>
                </div>
                <h2 className="text-xl sm:text-2xl font-bold text-white tracking-tight">
                  What are the Terms of Service for Axom AI?
                </h2>
                <p className="text-sm sm:text-base text-slate-300 leading-relaxed">
                  <strong>Axom AI&apos;s Terms of Service</strong> establish a binding user agreement under Indian law. Key highlights include: <strong className="text-white">you own your prompts and generated outputs</strong>, and subscribers on paid tiers enjoy <strong className="text-fuchsia-300">full commercial exploitation rights</strong> with zero royalty obligations. We do <strong className="text-white">not train public foundation models on private user data</strong>. The platform is provided on an &quot;as is&quot; basis with standard disclaimers regarding AI hallucinations and non-professional advice. All disputes are subject to the exclusive jurisdiction of the competent courts of <strong className="text-white">Guwahati, Assam, India</strong>.
                </p>
                <div className="pt-2 flex flex-wrap items-center gap-4 text-xs sm:text-sm text-slate-400">
                  <span className="flex items-center gap-1.5 text-emerald-400 font-medium">
                    <CheckCircle2 size={16} /> Commercial Use Permitted (Paid Tiers)
                  </span>
                  <span className="flex items-center gap-1.5 text-emerald-400 font-medium">
                    <CheckCircle2 size={16} /> 100% User Output Ownership
                  </span>
                  <span className="flex items-center gap-1.5 text-emerald-400 font-medium">
                    <CheckCircle2 size={16} /> Indian IT Act 2000 & DPDP Compliant
                  </span>
                </div>
              </div>
            </div>
          </section>

          {/* Interactive Terms Content */}
          <TermsInteractiveContent />
        </div>
      </main>

      <Footer footer={landingData?.footer} />
    </>
  );
}
