import {
  FileType2,
  Image as ImageIcon,
  Combine,
  Scissors,
  FileOutput,
  Minimize2,
  Droplets,
  Lock,
  Unlock,
  Presentation,
  FileSpreadsheet,
  ScanText,
  MessagesSquare,
  Languages,
  Sparkles,
  PenTool,
  Signature,
} from 'lucide-react';

export const TOOL_CATEGORIES = [
  { id: 'all', name: 'All Tools' },
  { id: 'Convert', name: 'Convert', color: '#3b82f6', bg: 'rgba(59, 130, 246, 0.12)' },
  { id: 'Office', name: 'Office', color: '#f59e0b', bg: 'rgba(245, 158, 11, 0.12)' },
  { id: 'Organize', name: 'Organize', color: '#8b5cf6', bg: 'rgba(139, 92, 246, 0.12)' },
  { id: 'Optimize', name: 'Optimize', color: '#10b981', bg: 'rgba(16, 185, 129, 0.12)' },
  { id: 'Security', name: 'Security', color: '#ef4444', bg: 'rgba(239, 68, 68, 0.12)' },
  { id: 'OCR', name: 'OCR', color: '#eab308', bg: 'rgba(234, 179, 8, 0.12)' },
  { id: 'AI Tools', name: 'AI Tools', color: '#ec4899', bg: 'rgba(236, 72, 153, 0.12)' },
  { id: 'Edit', name: 'Edit', color: '#06b6d4', bg: 'rgba(6, 182, 212, 0.12)' },
];

export const ALL_TOOLS = [
  // Convert
  {
    id: 'word2pdf',
    name: 'Word → PDF',
    cat: 'Convert',
    icon: FileType2,
    ep: 'convert',
    target: 'pdf',
    accept: '.docx,.doc,.txt,.rtf,.md',
    multi: false,
    hint: 'DOCX, DOC, TXT, RTF, MD',
    desc: 'Convert Microsoft Word and text documents into high-quality PDF files instantly.',
  },
  {
    id: 'pdf2word',
    name: 'PDF → Word',
    cat: 'Convert',
    icon: FileType2,
    ep: 'convert',
    target: 'docx',
    accept: '.pdf',
    multi: false,
    hint: 'PDF file',
    desc: 'Turn any PDF file into an editable Microsoft Word document (.docx).',
  },
  {
    id: 'img2pdf',
    name: 'Image → PDF',
    cat: 'Convert',
    icon: ImageIcon,
    ep: 'convert',
    target: 'pdf',
    accept: '.png,.jpg,.jpeg,.webp',
    multi: true,
    hint: 'PNG, JPG, WEBP (one or many)',
    desc: 'Convert one or multiple image files into a single structured PDF document.',
  },
  {
    id: 'pdf2jpg',
    name: 'PDF → JPG',
    cat: 'Convert',
    icon: ImageIcon,
    ep: 'convert',
    target: 'jpg',
    accept: '.pdf',
    multi: false,
    hint: 'PDF file',
    desc: 'Extract PDF pages into clear, high-resolution JPEG image files.',
  },
  {
    id: 'pdf2png',
    name: 'PDF → PNG',
    cat: 'Convert',
    icon: ImageIcon,
    ep: 'convert',
    target: 'png',
    accept: '.pdf',
    multi: false,
    hint: 'PDF file',
    desc: 'Extract PDF pages as lossless, transparent PNG graphic files.',
  },

  // Office
  {
    id: 'ppt2pdf',
    name: 'PowerPoint → PDF',
    cat: 'Office',
    icon: Presentation,
    ep: 'convert',
    target: 'pdf',
    accept: '.pptx,.ppt,.odp',
    multi: false,
    hint: 'PPTX, PPT, ODP',
    desc: 'Convert PowerPoint presentations into clean, shareable PDF slides.',
  },
  {
    id: 'excel2pdf',
    name: 'Excel → PDF',
    cat: 'Office',
    icon: FileSpreadsheet,
    ep: 'convert',
    target: 'pdf',
    accept: '.xlsx,.xls,.ods,.csv',
    multi: false,
    hint: 'XLSX, XLS, ODS, CSV',
    desc: 'Turn Excel spreadsheets and CSV tables into neatly formatted PDF documents.',
  },
  {
    id: 'office2pdf',
    name: 'ODT / HTML / EPUB → PDF',
    cat: 'Office',
    icon: FileType2,
    ep: 'convert',
    target: 'pdf',
    accept: '.odt,.html,.htm,.epub,.rtf',
    multi: false,
    hint: 'ODT, HTML, EPUB, RTF',
    desc: 'Convert open formats, e-books, and web pages into readable PDF documents.',
  },

  // Organize
  {
    id: 'merge',
    name: 'Merge PDF',
    cat: 'Organize',
    icon: Combine,
    ep: 'pdf',
    op: 'merge',
    accept: '.pdf',
    multi: true,
    hint: 'Two or more PDFs',
    desc: 'Combine multiple PDF files into one complete, perfectly ordered document.',
  },
  {
    id: 'split',
    name: 'Split PDF',
    cat: 'Organize',
    icon: Scissors,
    ep: 'pdf',
    op: 'split',
    accept: '.pdf',
    multi: false,
    hint: 'PDF file',
    desc: 'Split a large PDF file into separate single-page PDF files.',
  },
  {
    id: 'extract',
    name: 'Extract Pages',
    cat: 'Organize',
    icon: FileOutput,
    ep: 'pdf',
    op: 'extract',
    accept: '.pdf',
    multi: false,
    param: 'pages',
    hint: 'PDF file',
    desc: 'Extract specific page ranges (e.g. 1, 3-5) into an independent PDF.',
  },

  // Optimize
  {
    id: 'compress',
    name: 'Compress PDF',
    cat: 'Optimize',
    icon: Minimize2,
    compressor: true,
    hint: 'PDF file',
    desc: 'Reduce PDF file size without noticeable loss of visual quality.',
  },
  {
    id: 'watermark',
    name: 'Watermark PDF',
    cat: 'Optimize',
    icon: Droplets,
    ep: 'pdf',
    op: 'watermark',
    accept: '.pdf',
    multi: false,
    param: 'text',
    hint: 'PDF file',
    desc: 'Add custom security or branding watermark text across all PDF pages.',
  },

  // Security
  {
    id: 'protect',
    name: 'Protect PDF',
    cat: 'Security',
    icon: Lock,
    ep: 'pdf',
    op: 'protect',
    accept: '.pdf',
    multi: false,
    param: 'password',
    hint: 'PDF file',
    desc: 'Encrypt and secure sensitive PDF documents with robust password protection.',
  },
  {
    id: 'unlock',
    name: 'Unlock PDF',
    cat: 'Security',
    icon: Unlock,
    ep: 'pdf',
    op: 'unlock',
    accept: '.pdf',
    multi: false,
    param: 'password',
    hint: 'Password-protected PDF',
    desc: 'Remove security passwords and restrictions from your protected PDF files.',
  },

  // OCR
  {
    id: 'ocr',
    name: 'OCR — Make Searchable',
    cat: 'OCR',
    icon: ScanText,
    ep: 'pdf',
    op: 'ocr',
    accept: '.pdf',
    multi: false,
    hint: 'Scanned PDF',
    desc: 'Convert scanned image PDFs into searchable, selectable text (English, Assamese & Hindi).',
  },

  // AI Tools
  {
    id: 'chatpdf',
    name: 'Chat with PDF',
    cat: 'AI Tools',
    icon: MessagesSquare,
    ep: 'ai',
    op: 'chat',
    accept: '.pdf',
    multi: false,
    param: 'question',
    hint: 'PDF file',
    desc: 'Ask questions and get instant, intelligent answers directly from your PDF document.',
  },
  {
    id: 'summarize',
    name: 'Summarize PDF',
    cat: 'AI Tools',
    icon: Sparkles,
    ep: 'ai',
    op: 'summarize',
    accept: '.pdf',
    multi: false,
    hint: 'PDF file',
    desc: 'Extract concise summaries, key insights, and action points using AI.',
  },
  {
    id: 'translatepdf',
    name: 'Translate PDF',
    cat: 'AI Tools',
    icon: Languages,
    ep: 'ai',
    op: 'translate',
    accept: '.pdf',
    multi: false,
    param: 'lang',
    hint: 'PDF file',
    desc: 'Translate PDF text into Assamese, Hindi, English, and more with AI.',
  },

  // Interactive Canvas Editor
  {
    id: 'edit',
    name: 'Edit PDF',
    cat: 'Edit',
    icon: PenTool,
    editor: true,
    hint: 'PDF file',
    desc: 'Annotate, draw, insert shapes, highlight and edit pages in a full interactive canvas.',
  },
  {
    id: 'sign',
    name: 'Sign PDF',
    cat: 'Edit',
    icon: Signature,
    editor: true,
    hint: 'PDF file',
    desc: 'Draw or insert your electronic signature and place it anywhere on your PDF.',
  },
];
